### ISSUE TITLE
Using my own dataset training model, how can tensorpack load only some parameters of the pre-training model?

### ISSUE THREAD

**Issue by liningxiao** [tensorpack/tensorpack#1015]
Use the model you provided as the pre-training model, but the categories are different, 46 classes instead of 80 classes of coco.The problem is as follows，How should I solve this problem?

Traceback (most recent call last):
  File "train.py", line 613, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/train/interface.py", line 97, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/train/base.py", line 341, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/train/base.py", line 312, in train
    self.initialize(session_creator, session_init)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/train/tower.py", line 144, in initialize
    super(TowerTrainer, self).initialize(session_creator, session_init)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/train/base.py", line 234, in initialize
    session_init._run_init(self.sess)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 221, in _run_init
    upd.update({name: value for name, value in six.iteritems(self._prms) if name in intersect})
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/tfutils/varmanip.py", line 106, in update
    SessionUpdate.load_value_to_var(v, value)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorpack/tfutils/varmanip.py", line 67, in load_value_to_var
    "{}: {}!={}".format(name, varshape, val.shape)
**AssertionError: fastrcnn/outputs/class/b: (47,)!=(81,)**
MultiProcessMapDataZMQ successfully cleaned-up.

**Comment by ppwwyyxx** [comment]
The config file currently has NUM_CATEGORY=80

**Comment by liningxiao** [comment]
> The config file currently has NUM_CATEGORY=80

I have changed the config.py file.Where else should I modify it?
_C.DATA.NUM_CATEGORY = 46

**Comment by ppwwyyxx** [comment]
That's the only place you need to modify.

**Comment by ppwwyyxx** [comment]
Oh I misread your issue. You're also loading a pre-trained model.
You can remove `fastrcnn/outputs/*`, `maskrcnn/conv/*` from the pre-trained model because it's impossible to load them when your dataset has different number of outputs.
Alternatively, you can rename them in the graph. If the names are different, these values won't be loaded.

**Comment by ppwwyyxx** [comment]
To modify the pre-trained model you can load it with `np.load` and save it with `np.savez`. Refer to numpy documentation for details.

**Comment by ppwwyyxx** [comment]
Closing due to lack of activity. Feel free to reopen if the problem was not solved.
