### ISSUE TITLE
How to use FasterRCNN without training

### ISSUE THREAD

**Issue by AngelinaRanhh** [tensorpack/tensorpack#1021]
As training will take a long time , I just do  predict . 

./tensorpack-master/examples/FasterRCNN/train.py --predict person.jpg --load ./tensorpack-master/examples/FasterRCNN/model_mrcnn.py --config MODE_MASK=True MODE_FPN=True BACKBONE.WEIGHTS=./tensorpack-master/ImageNet-R50-AlignPadding.npz

but the error shows like that:

2018-12-20 05:11:41.827526: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./tensorpack-master/examples/FasterRCNN/model_mrcnn.py: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "./tensorpack-master/examples/FasterRCNN/train.py", line 539, in <module>
    output_names=MODEL.get_inference_tensor_names()[1]))
  File "/home/huanhuan/anaconda3/lib/python3.6/site-packages/tensorpack/predict/base.py", line 153, in __init__
    config.session_init._setup_graph()
  File "/home/huanhuan/anaconda3/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 111, in _setup_graph
    dic = self._get_restore_dict()
  File "/home/huanhuan/anaconda3/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 160, in _get_restore_dict
    self._match_vars(f)
  File "/home/huanhuan/anaconda3/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 127, in _match_vars
    reader, chkpt_vars = SaverRestore._read_checkpoint_vars(self.path)
  File "/home/huanhuan/anaconda3/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 121, in _read_checkpoint_vars
    reader = tf.train.NewCheckpointReader(model_path)
  File "/home/huanhuan/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 326, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/home/huanhuan/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./tensorpack-master/examples/FasterRCNN/model_mrcnn.py: **Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?**

Can anyone help me, thanks!

**Comment by AngelinaRanhh** [comment]
I  have check this:
./tensorpack-master/examples/FasterRCNN/train.py --predict person.jpg --load ./tensorpack-master/examples/FasterRCNN/model_cascade.py --config MODE_MASK=True MODE_FPN=True FPN.CASCADE=True BACKBONE.RESNET_NUM_BLOCKS=[3,4,23,3] TEST.RESULT_SCORE_THRESH=1e-4 PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800] TRAIN.LR_SCHEDULE=[420000,500000,540000] BACKBONE.WEIGHTS=./tensorpack-master/COCO-R101FPN-MaskRCNN-BetterParams.npz


./tensorpack-master/examples/FasterRCNN/train.py --predict person.jpg --load ./tensorpack-master/examples/FasterRCNN/model_mrcnn.py --config MODE_MASK=True MODE_FPN=True FPN.CASCADE=True BACKBONE.RESNET_NUM_BLOCKS=[3,4,23,3] TEST.RESULT_SCORE_THRESH=1e-4 PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800] TRAIN.LR_SCHEDULE=[420000,500000,540000] BACKBONE.WEIGHTS=./tensorpack-master/COCO-R101FPN-MaskRCNN-BetterParams.npz

the error info is same.

**Comment by ppwwyyxx** [comment]
> The --load has to be a model you downloaded in the "results" table.

Not "model_cascade.py".

**Comment by AngelinaRanhh** [comment]
Is this "COCO-R101FPN-MaskRCNN-BetterParams.npz" ?

**Comment by ppwwyyxx** [comment]
Yes.
