### ISSUE TITLE
convert pretrained shufflenet *npz to regular TF *pb file

### ISSUE THREAD

**Issue by tingxingdong** [tensorpack/tensorpack#1029]
If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
 python ./shufflenet.py --load ShuffleNetV2-1x.npz --v2 -r=1
(2) **If you're using examples, have you made any changes to the examples? Paste them here:**
insert such following after line 249 of https://github.com/tensorpack/tensorpack/blob/master/examples/ImageNetModels/shufflenet.py

pred_config = PredictConfig(
    session_init=get_model_loader(args.load),
    model = Model()
    #, input_names=['input']
    #, output_names=['output']
    )
ModelExporter(pred_config).export_compact('/tmp/compact_graph.pb')

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It gvies me AssertionError: <type 'NoneType'> which is model=Model() on line 252 ,

However, line 249 is exactly the model=Model() which passed before this block.

### 3. What you expected, if not obvious.
expect a /tmp/compact_graph.pb appear 

### 4. Your environment:
  + Python version: 2.7
  + TF version: r1.12
  + Tensorpack version:  master branch
  + Hardware information, e.g. number of GPUs used. 1 NV GPU

**Comment by ppwwyyxx** [comment]
> (1) Include the ENTIRE logs here:

Please include the entire logs which will help with the investigation. Otherwise I'll have to modify the code and run it myself.  The logs is like this:
```
Traceback (most recent call last):
  File "./shufflenet.py", line 252, in <module>
    model = model,
  File "/home//tensorpack/tensorpack/predict/config.py", line 85, in __init__
    assert_type(self.output_names, list)
  File "/home//tensorpack/tensorpack/predict/config.py", line 57, in assert_type
    assert isinstance(v, tp), v.__class__
AssertionError: <class 'NoneType'>
```
which means you have to provide `output_names`.

**Comment by tingxingdong** [comment]
Thanks so much. I updated my local repo by checking in your new commits. 
I worked on linux machine which blocked the github.com so it is hard to paste all my log. But that is exactly the same error like you pasted here. 

I tried several words in the ['  '], like 'linear' (from line  153, fully connected operation), 'gap' (line 153, for Pooling), , 'linear output', or 'output', etc.   from the shufflenet.py.

`, output_names=[' ']`

but They all gives me similar error:

`KeyError: "The name 'linear:0' refers to a Tensor which does not exist. The operation, 'linear', does not exist in the graph. 
`
So I do not know what is the output_names?

**Comment by ppwwyyxx** [comment]
See the tutorial on https://tensorpack.readthedocs.io/tutorial/symbolic.html#access-relevant-tensors
The name of the output tensor of the 'linear' layer will be 'linear/output'.
In general you can print a tensor to see its name by `print(x)`.

**Comment by tingxingdong** [comment]
Thanks, linear/output works. But this time, it dies in line 259. 

tcut_dconv/W:0, stage3/block4/conv2/bn/beta:0, stage4/block0/conv2/bn/mean/EMA:0, stage2/block0/conv1/bn/variance/EMA:0, stage3/block5/conv2/bn/variance/EMA:0, stage4/block0/shortcut_conv/W:0, stage3/block4/conv2/W:0, stage4/block0/shortcut_dconv_bn/beta:0, stage3/block7/conv1/W:0, stage4/block1/conv1/bn/variance/EMA:0
[0103 15:08:42 @sessinit.py:217] Restoring from dict ...
Converted 282 variables to const ops.
Traceback (most recent call last):
  File "./shufflenet.py", line 259, in <module>
    ModelExporter(pred_config).export_compact('/tmp/compact_graph.pb')
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/export.py", line 74, in export_compact
    False)
TypeError: optimize_for_inference() takes exactly 4 arguments (5 given)

**Comment by ppwwyyxx** [comment]
TensorFlow's inference optimization tool only works for toco after TF 1.8: https://github.com/tensorflow/tensorflow/commit/c8e3d2b43e4cbf9a9e32567a2e59597916f5b0b9

The above commit adds support for exporting a TOCO-compatible graph if using TF>=1.8.

**Comment by tingxingdong** [comment]
I uninstall and reinstall again
sudo pip show tensorflow 
Name: tensorflow
Version: 1.12.0

Now, I have different errors

Traceback (most recent call last):
  File "./shufflenet.py", line 260, in <module>
    ModelExporter(pred_config).export_compact('./compact_graph.pb')
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/export.py", line 74, in export_compact
    False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/optimize_for_inference_lib.py", line 111, in optimize_for_inference
    placeholder_type_enum)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: set([u'label'])\n"

**Comment by ppwwyyxx** [comment]
Maybe you did not provide the `input_names`. By default the inputs are the one used by your model, which is both "input" and "label", as declared here: https://github.com/tensorpack/tensorpack/blob/860f7a382f8dc245e46c5f637866ef6384db1733/examples/ImageNetModels/imagenet_utils.py#L323-L325

However, when converting to toco, it appears that the conversion tool does not like it when an input is not used. In this case since you're asking for `linear/output`, it does not depend on 'label' so you should not add 'label' to the `input_names`.

**Comment by tingxingdong** [comment]
By ,input_names=['input'], it works, and I can get ./compact_graph.pb 

Yet, I am not able to use TOCO

tflite_convert --output_file=./shufflenet.tflite --graph_def_file=./compact_graph.pb --input_arrays=input --output_arrays=linear/output
2019-01-03 17:21:35.382450: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Traceback (most recent call last):
  File "/home/tim/tensorflow/bin/tflite_convert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 412, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 408, in run_main
    _convert_model(tflite_flags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 162, in _convert_model
    output_data = converter.convert()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/lite/python/lite.py", line 404, in convert
    "'{0}'.".format(_tensor_name(tensor)))
ValueError: Provide an input shape for input array 'input'.

**Comment by ppwwyyxx** [comment]
This is a tflite question that's unrelated to tensorpack.

It asks you to provide input shape so you should do it. Google tells me that you can do it with command line: https://github.com/rockchip-linux/tensorflow/blob/e1877bb157a775d76ec8c0b68467aef6d053bbb2/tensorflow/contrib/lite/python/tflite_convert.py#L231-L234

**Comment by tingxingdong** [comment]
Still many many thanks!

**Comment by tingxingdong** [comment]
one more question, is the obtained *pb file is a frozen one (frozen with trained weights in *ckpt) or it is merely a graph without weights in it?  Thanks again

**Comment by ppwwyyxx** [comment]
As mentioned in the tutorial: https://tensorpack.readthedocs.io/tutorial/inference.html#exporter , it is frozen.

**Comment by tingxingdong** [comment]
Is this trained *npz (and thus converted *pb) store weights in NHWC format or NCHW format?  because I see an error when using TOCO:  Unexpected value for attribute data format Expected NHWC

**Comment by tingxingdong** [comment]
Simply change shufflenet.py line  37, line 117 to NHWC and "channle_last" won't work as it will report Dimension not equal error.

**Comment by ppwwyyxx** [comment]
weights do not have NHWC or NCHW format.
The ops are in NCHW format as written in the code.

**Comment by tingxingdong** [comment]
Thanks, I changed the imagenet_utility.py data_format from NCHW and NHWC. I also change a couple of hard coded location of in_channel = in_shape[1] to in_shape[3]. I can proceed a little bit but died in shortcut_channel.

[0104 13:06:37 @shufflenet.py:144] #Channels: [24, 116, 232, 464]
[0104 13:06:37 @registry.py:121] conv1 input: [None, 224, 224, 3]
[0104 13:06:37 @registry.py:129] conv1 output: [None, 112, 112, 24]
[0104 13:06:37 @registry.py:121] pool1 input: [None, 112, 112, 24]
[0104 13:06:37 @registry.py:129] pool1 output: [None, 56, 56, 24]
[0104 13:06:37 @registry.py:121] stage2 input: [None, 56, 56, 24]
[0104 13:06:37 @registry.py:121] stage2/block0/conv1 input: [None, 56, 56, 24]
[0104 13:06:37 @registry.py:129] stage2/block0/conv1 output: [None, 56, 56, 58]
[0104 13:06:37 @registry.py:121] stage2/block0/dconv input: [None, 56, 56, 58]
[0104 13:06:37 @registry.py:129] stage2/block0/dconv output: [None, 56, 28, 58]
[0104 13:06:37 @registry.py:121] stage2/block0/conv2 input: [None, 56, 28, 58]
[0104 13:06:37 @registry.py:129] stage2/block0/conv2 output: [None, 56, 28, 60]
[0104 13:06:37 @registry.py:121] stage2/block0/shortcut_dconv input: [None, 56, 56, 24]
Traceback (most recent call last):
  File "./shufflenet.py", line 263, in <module>
    ModelExporter(pred_config).export_compact('./new_compact_graph-nhwc.pb')
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/export.py", line 48, in export_compact
    self.config.tower_func(*input.get_input_tensors())
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/tower.py", line 286, in __call__
    output = self._tower_fn(*args)
  File "/home/tim/tensorpack/examples/ImageNetModels/imagenet_utils.py", line 333, in build_graph
    logits = self.get_logits(image)
  File "./shufflenet.py", line 149, in get_logits
    l = shufflenet_stage('stage2', l, channels[0], 4, group)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "./shufflenet.py", line 109, in shufflenet_stage
    l = shufflenet_unit_v2(name, l, channel, 2 if i == 0 else 1)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "./shufflenet.py", line 95, in shufflenet_unit_v2
    shortcut = DepthConv('shortcut_dconv', shortcut, shortcut_channel, 3, stride=2)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "./shufflenet.py", line 29, in DepthConv
    assert out_channel % in_channel == 0, (out_channel, in_channel)
AssertionError: (56, 24)

For shortcut is complicated for me, as it is tangled with shape transposes

**Comment by ppwwyyxx** [comment]
The modification you need to do is completely in the tensorflow domain and not related to tensorpack much. So that's not something I can offer much help. You can just print the shapes of tensors to see where it goes wrong. From your log it appears this layer is already wrong:
```
[0104 13:06:37 @registry.py:121] stage2/block0/dconv input: [None, 56, 56, 58]
> [0104 13:06:37 @registry.py:129] stage2/block0/dconv output: [None, 56, 28, 58]
```

**Comment by tingxingdong** [comment]
Thanks, but is` line 36 shufflenet.py [1, 1, stride, stride] `a bug ?
according to the API (https://www.tensorflow.org/api_docs/python/tf/nn/depthwise_conv2d), should it be `[1, stride, stride, 1]`?

**Comment by ppwwyyxx** [comment]
It's not a bug. It should be changed according to the data format.

**Comment by ppwwyyxx** [comment]
```python
@under_name_scope()
def channel_shuffle(l, group):
    in_shape = l.get_shape().as_list()
    H, W, in_channel = in_shape[1:]  
    assert in_channel % group == 0, in_channel
    l = tf.reshape(l, [-1, H, W, in_channel // group, group]) //guess the reshape is critical
    l = tf.transpose(l, [0, 1, 2, 4, 3]) //guess, this tranpose need to change 
    l = tf.reshape(l, [-1, H, W, in_channel])
    return l
```

**Comment by tingxingdong** [comment]
Thanks so much. Now I can get a NHWC *pb successfully with everything is correct. I modified shufflenet.py a lot, and imagenet_utils.py by one line change from NCHW to NHWC.  I can contribute my code if needed.

**Comment by naufalboys** [comment]
> Thanks so much. Now I can get a NHWC *pb successfully with everything is correct. I modified shufflenet.py a lot, and imagenet_utils.py by one line change from NCHW to NHWC. I can contribute my code if needed.

need your code please
