### ISSUE TITLE
FasterRCNN training error outs (in tensorpack/dataflow/parallel_map.py)

### ISSUE THREAD

**Issue by jwnsu** [tensorpack/tensorpack#1034]
Pulled latest tensorpack today and run fasterRCNN training, got following error (after successful data loading and graph building on 8 GPUs):
```
Traceback (most recent call last):
  File "./train.py", line 514, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/interface.py", line 94, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/base.py", line 343, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/base.py", line 313, in train
    self.setup_callbacks(callbacks, monitors)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/train/base.py", line 210, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/callbacks/base.py", line 53, in setup_graph
    self._setup_graph()
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/callbacks/group.py", line 70, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/callbacks/base.py", line 53, in setup_graph
    self._setup_graph()
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/callbacks/base.py", line 309, in _setup_graph
    self._cb_setup_graph(self)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/input_source/input_source.py", line 36, in <lambda>
    return CallbackFactory(setup_graph=lambda _: df.reset_state())
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/dataflow/base.py", line 173, in reset_state
    self.ds.reset_state()
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/dataflow/parallel_map.py", line 280, in reset_state
    self._fill_buffer()     # pre-fill the bufer
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/dataflow/parallel_map.py", line 55, in _fill_buffer
    self._send(dp)
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/dataflow/parallel_map.py", line 283, in _send
    msg = [b"", dumps(dp)]
  File "/home/dsu/tf3/lib/python3.5/site-packages/tensorpack/utils/serialize.py", line 22, in dumps_msgpack
    return msgpack.dumps(obj, use_bin_type=True)
  File "/home/dsu/tf3/lib/python3.5/site-packages/msgpack_numpy.py", line 196, in packb
    return Packer(**kwargs).pack(o)
  File "/home/dsu/tf3/lib/python3.5/site-packages/msgpack_numpy.py", line 162, in __init__
    strict_types=strict_types)
  File "msgpack/_packer.pyx", line 136, in msgpack._packer.Packer.__init__
TypeError: expected bytes, str found


```

Detailed env is below in template:

If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
./train.py --load data/ImageNet-ResNet50.npz --logdir output/fr50
(2) **If you're using examples, have you made any changes to the examples? Paste them here:**
changed dataset config (location, class_names etc).
(3) **If not using examples, tell us what you did here:**

Note that we may not be able to investigate it if there is no reproducible code.
It's always better to paste what you did instead of describing them.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It's always better to paste what you observed instead of describing them.

A part of logs is sometimes enough, but it's always better to paste as much as possible.

You can run a command with `CMD 2>&1 | tee logs.txt` to save all stdout & stderr logs to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.
This happens before GPUs were loaded
### 3. What you expected, if not obvious.

If you expect higher accuracy, only in one of the two conditions can we help with it:
(1) You're unable to match the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to get high accuracy is a machine learning question and is
not our responsibility to figure out.

### 4. Your environment:
  + Python version: 3.5.2
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`. 1.12.0
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`. 0.9.0.1 latest
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used. 1080 Ti (8), Ubuntu 16.04.5

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment]
Which versions did you upgrade it from and to? There is an assertion on msgpack version at 
https://github.com/tensorpack/tensorpack/blob/4eaeed3f6f4651aece29181266194beb4960774f/tensorpack/utils/serialize.py#L77
It should assert the version during import and I wonder why it wasn't functional

**Comment by jwnsu** [comment]
If I remember it correctly, was running 0.5.8, which produced the error, upgrade to 0.6.0 resolved the issue.
