### ISSUE TITLE
error when I implement the code : python export-model.py 

### ISSUE THREAD

**Issue by vxgu86** [tensorpack/tensorpack#1055]
the things happened first after I git and install  is numpy telling:
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/array/__init__.py", line 7, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/array/routines.py", line 253, in <module>
    @wraps(np.matmul)
  File "/opt/anaconda2/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'

when I switch back from  uninstalled numpy-1.16.0 and installed numpy-1.15.4,the errors are :+1: 
ImportError: cannot import name ModelExporter
python export-model.py 
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "export-model.py", line 9, in <module>
    from tensorpack.tfutils.export import ModelExporter
ImportError: cannot import name ModelExporter

what should I do

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))
