### ISSUE TITLE
error when I implement the code : python export-model.py

### ISSUE THREAD

**Issue by vxgu86** [tensorpack/tensorpack#1056]
### 1. What you did:
(1) **If you're using examples, what's the command you run:**
error when I implement the code : python export-model.py

### 2. What you observed:
(1) **Include the ENTIRE logs here:**
the things happened first after I git and install  is numpy telling:
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/array/__init__.py", line 7, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/array/routines.py", line 253, in <module>
    @wraps(np.matmul)
  File "/opt/anaconda2/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'

when I switch back from  uninstalled numpy-1.16.0 and installed numpy-1.15.4,the errors are as follows:
python export-model.py 
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "export-model.py", line 9, in <module>
    from tensorpack.tfutils.export import ModelExporter
ImportError: cannot import name ModelExporter

(2) **Other observations, if any:**
I am using Titan V

### 4. Your environment:
  + Python version:2.7.14
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`. 
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Hardware information, e.g. number of GPUs used.

tensorboard (1.10.0)
tensorflow-gpu (1.10.0)
tensorpack (0.9.0.1)

**Comment by vxgu86** [comment]
and when I exec the code **python mnist-visualizations.py** 
the following errors dump:
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[0118 14:52:56 @logger.py:94] WRN Log directory train_log/mnist-visualizations exists! Please either backup/delete it, or use a new directory.
[0118 14:52:56 @logger.py:96] WRN If you're resuming from a previous run you can choose to keep it.
[0118 14:52:56 @logger.py:97] Select Action: k (keep) / b (backup) / d (delete) / n (new) / q (quit):
d
[0118 14:52:58 @logger.py:74] Argv: mnist-visualizations.py
[0118 14:52:58 @fs.py:89] WRN Env var $TENSORPACK_DATASET not set, using /home/lthpc/tensorpack_data for datasets.
Traceback (most recent call last):
  File "mnist-visualizations.py", line 128, in <module>
    model=Model(),
TypeError: Can't instantiate abstract class Model with abstract methods _get_inputs

**Comment by ppwwyyxx** [comment]
You're not importing a correct (latest) version of tensorpack. And it's likely you have multiple versions of tensorpack installed in your system. Please remove tensorpack by running `pip2 uninstall tensorpack`, `pip uninstall tensorpack` each for several times and clean your PYTHONPATH environment variables. Then install tensorpack following the issue template you posted above.

**Comment by ppwwyyxx** [comment]
You did not follow the issue template to post the output of `python -c 'import tensorpack; print(tensorpack.__version__);'`. 
Please do so and also print `tensorpack.__file__` which will help you find your installation problems.

**Comment by vxgu86** [comment]
I reinstalled the tensorpack and reboot, then the process aborted only before **import tensorpack**
**>>> import tensorpack**
/opt/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorpack/__init__.py", line 17, in <module>
    from tensorpack.models import *
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorpack/models/__init__.py", line 48, in <module>
    _global_import(module_name)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorpack/models/__init__.py", line 29, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorpack/models/regularize.py", line 24, in <module>
    l2_regularizer = tf.contrib.layers.l2_regularizer
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/opt/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 40, in <module>
    from tensorflow.contrib import distributions
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 38, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/__init__.py", line 95, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 35, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/opt/anaconda2/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/array/__init__.py", line 7, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/opt/anaconda2/lib/python2.7/site-packages/dask/array/routines.py", line 253, in <module>
    @wraps(np.matmul)
  File "/opt/anaconda2/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'


>>> import numpy
>>> numpy.__version__
'1.16.0'
>>>

**Comment by ppwwyyxx** [comment]
Since the issue comes from import tensorflow.contrib, this is not a tensorpack issue.
Since the stack trace eventually come from dask, you should try either upgrading dask or uninstalling dask

**Comment by vxgu86** [comment]
the problem solved with 
pip install numpy==1.15.4
