### ISSUE TITLE
XLA for Mask-RCNN

### ISSUE THREAD

**Issue by vsuthichai** [tensorpack/tensorpack#1067]
I'm having issues turning XLA on for mask-rcnn.  Specifically, here:

https://github.com/tensorpack/tensorpack/blob/62e24918205fcf7e8f779d66703e1b8e855803bf/tensorpack/train/tower.py#L179

I've enabled XLA by setting to flag to `True`, and starting a training job would result in this error.

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _run_fn
    self._extend_graph()
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1352, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Undeclared output of XLA computation. A common cause of this error is variable initializers that depend on the XLA computation. Edge: truediv_1:0 -> AccumGradOptimizer/train_op/Momentum/update_group1/block0/conv1/W/ResourceApplyMomentum/Switch_1:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/tensorpack-mask-rcnn/MaskRCNN-no-batch/train.py", line 452, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/train/interface.py", line 94, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/train/base.py", line 343, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/train/base.py", line 314, in train
    self.initialize(session_creator, session_init)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 443, in initialize
    super(HorovodTrainer, self).initialize(session_creator, session_init)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/train/tower.py", line 142, in initialize
    super(TowerTrainer, self).initialize(session_creator, session_init)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/train/base.py", line 231, in initialize
    self.sess = session_creator.create_session()
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorpack/tfutils/sesscreate.py", line 45, in create_session
    sess.run(tf.global_variables_initializer())
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/ubuntu/anaconda3/envs/tf_1.12_exp/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Undeclared output of XLA computation. A common cause of this error is variable initializers that depend on the XLA computation. Edge: truediv_1:0 -> AccumGradOptimizer/train_op/Momentum/update_group1/block0/conv1/W/ResourceApplyMomentum/Switch_1:0
```

From the sounds of the error message, it seems like a common problem but I'm not quite sure how to go about resolving this.

**Comment by ppwwyyxx** [comment]
As the documentation said:
```
    """ Use :func:`xla.compile` to compile the tower function.
    Note that XLA has very strong requirements on the tower function, e.g.:

    1. limited op support
    2. inferrable shape
    3. no summary support

    and many tower functions cannot be compiled by XLA.
    Don't use it if you don't understand it.
    """
```

To optimize mask rcnn you may need to manually pick a subgraph and use `xla.compile` yourself on it.

This question is unrelated to tensorpack and just due to tensorflow's limitation.

**Comment by vsuthichai** [comment]
I see, thank you.
