### ISSUE TITLE
'TrainConfig' object has no attribute 'nr_tower' (A3C)

### ISSUE THREAD

**Issue by JamesBrightman** [tensorpack/tensorpack#1077]
### 1. What I did:

I'm trying to train Breakout on google colab using the A3C implementation. Whenever I run 
`!python train-atari.py --env Breakout-v0 --gpu 0`
It causes an error;

Traceback (most recent call last):
  File "train-atari.py", line 301, in <module>
    train()
  File "train-atari.py", line 262, in train
    trainer = SimpleTrainer() if config.nr_tower == 1 else AsyncMultiGPUTrainer(train_tower)
AttributeError: 'TrainConfig' object has no attribute 'nr_tower'

It doesn't matter what Colab settings I use - normal, GPU enhanced or TPU enhanced, it happens on all.

Any ideas of a fix/ workaround? Previously I commented out from '# == 1 else AsyncMultiGPUTrainer(train_tower)' but as my epochs are taking hours to run and should apparently take ~20 mins, I feel this may be a problem.

Thanks.

**Comment by ppwwyyxx** [comment]
`config.nr_tower` should be `num_gpu` instead. Thanks for the report!

**Comment by JamesBrightman** [comment]
Fixes that issue, thanks. Doesn't fix the fact that it's forecast to train 1 epoch in over 10 hours with an it/s speed of ~10. Any thoughts on why this might be?

**Comment by ppwwyyxx** [comment]
If it/s is really 10, and STEPS_PER_EPOCH is defined 6000 (https://github.com/tensorpack/tensorpack/blob/49675590da8a39c649b5f0f5ba522a22b90e2d69/examples/A3C-Gym/train-atari.py#L40 )

Then you should finish 1 epoch in 10 minutes, right?

**Comment by JamesBrightman** [comment]
Yeah. that's exactly why i'm confused!

I just lowered it to 1000 STEPS_PER_EPOCH (to see if anything would change) and as you can see for them attached pic, I have 10 it/s but apparently, it will still take nearly 3 hours. 

![image](https://user-images.githubusercontent.com/35103224/52583366-51a6d100-2e27-11e9-88b3-24d40035561e.png)

**Comment by ppwwyyxx** [comment]
You have 10s/it, not 10it/s.

From your log it does not appear that you're using GPU. Normally tensorflow should print something GPU-related when creating the session.

**Comment by JamesBrightman** [comment]
welp, my bad. As for the GPU training it seems you're right if it's as long as 10s/it. Looking though the messages I do get this;
`[0211 18:01:46 @gpu.py:43] WRN Found non-empty CUDA_VISIBLE_DEVICES. But TensorFlow was not built with CUDA `support!``
when I run it with;
`!python train-atari.py --env Breakout-v0 --gpu 1` or `!python train-atari.py --env Breakout-v0 --gpu 0`

Is there a different set up that is needed for training in tensorflow to allow GPU training?

**Comment by ppwwyyxx** [comment]
Apparently it's telling you that your tensorflow does not support CUDA. You need a different version of tensorflow and I'm not familiar with how it work in colab

**Comment by JamesBrightman** [comment]
Ok thanks, I'll look to change tensorflow version. If anyone runs into this problem my current Colab library versions are;
```
tensor2tensor            1.11.0               
tensorboard              1.12.2               
tensorboardcolab         0.0.22               
tensorflow               1.13.0rc0            
tensorflow-estimator     1.10.12              
tensorflow-hub           0.2.0                
tensorflow-metadata      0.9.0                
tensorflow-probability   0.5.0                
tensorflow-tensorboard   1.5.1                
tensorpack               0.9.1   
tf-estimator-nightly     1.14.0.dev2019021101 
tf-nightly               1.13.0.dev20190208   
tfds-nightly             0.0.2.dev201902070013
```

**Comment by ppwwyyxx** [comment]
You need either `tensorflow-gpu` or `tf-nightly-gpu` (and only one of them but not two).

**Comment by JamesBrightman** [comment]
Ah ok, and I assume this means removing traces of non-gpu tensorflow libraries? eg/ removing 
```
tensorflow-estimator     1.10.12              
tensorflow-hub           0.2.0                
tensorflow-metadata      0.9.0                
tensorflow-probability   0.5.0                
tensorflow-tensorboard   1.5.1
tf-estimator-nightly     1.14.0.dev2019021101 
tf-nightly               1.13.0.dev20190208
```
?

**Comment by ppwwyyxx** [comment]
I don't whether the other packages affect this but you can remove them all, and they will be automatically installed if tensorflow actually depends on them.

**Comment by JamesBrightman** [comment]
This was a **LOT** harder than I expected, I feel like i've been install and uninstalling packages for hours. I'll paste a list of **all** colab library versions so that if anyone else has this problem hopefully this will solve it.
Currently running at ~3s/it (not 3it/s! haha). 
Appreciate all the help, this stuff is hard to learn as a beginner! 
```
Package                  Version              
------------------------ ---------------------
absl-py                  0.7.0                
alabaster                0.7.12               
albumentations           0.1.12               
altair                   2.3.0                
astor                    0.7.1                
astropy                  3.0.5                
atari-py                 0.1.7                
atomicwrites             1.3.0                
attrs                    18.2.0               
audioread                2.1.6                
autograd                 1.2                  
Babel                    2.6.0                
backports.tempfile       1.0                  
backports.weakref        1.0.post1            
batchglm                 0.4.1                
beautifulsoup4           4.6.3                
bleach                   1.5.0                
bokeh                    1.0.4                
boto                     2.49.0               
boto3                    1.9.89               
botocore                 1.12.89              
Bottleneck               1.2.1                
bs4                      0.0.1                
bz2file                  0.98                 
cachetools               3.1.0                
certifi                  2018.11.29           
cffi                     1.11.5               
cftime                   1.0.3.4              
chainer                  5.0.0                
chardet                  3.0.4                
Click                    7.0                  
cloudpickle              0.6.1                
cmake                    3.12.0               
colorlover               0.3.0                
community                1.0.0b1              
contextlib2              0.5.5                
convertdate              2.1.3                
coverage                 3.7.1                
coveralls                0.5                  
crcmod                   1.7                  
cufflinks                0.14.6               
cupy-cuda100             5.2.0                
cvxopt                   1.2.3                
cvxpy                    1.0.14               
cycler                   0.10.0               
cymem                    2.0.2                
Cython                   0.29.4               
cytoolz                  0.9.0.1              
daft                     0.0.4                
dask                     0.20.2               
dataclasses              0.6                  
datascience              0.10.6               
decorator                4.3.2                
defusedxml               0.5.0                
diffxpy                  0.4.2                
dill                     0.2.9                
distributed              1.25.3               
Django                   2.1.5                
dlib                     19.16.0              
dm-sonnet                1.23                 
docopt                   0.6.2                
docutils                 0.14                 
dopamine-rl              1.0.5                
easydict                 1.9                  
ecos                     2.0.7.post1          
editdistance             0.5.2                
en-core-web-sm           2.0.0                
entrypoints              0.3                  
enum34                   1.1.6                
ephem                    3.7.6.0              
et-xmlfile               1.0.1                
fa2                      0.3.5                
fancyimpute              0.4.2                
fastai                   1.0.42               
fastcache                1.0.2                
fastdtw                  0.3.2                
fastprogress             0.1.18               
fastrlock                0.4                  
fbprophet                0.4.post2            
featuretools             0.4.1                
filelock                 3.0.10               
fix-yahoo-finance        0.0.22               
Flask                    1.0.2                
folium                   0.2.1                
future                   0.16.0               
gast                     0.2.2                
GDAL                     2.2.2                
gdown                    3.6.4                
gensim                   3.6.0                
geographiclib            1.49                 
geopy                    1.17.0               
gevent                   1.4.0                
gin-config               0.1.2                
glob2                    0.6                  
google                   2.0.1                
google-api-core          1.7.0                
google-api-python-client 1.6.7                
google-auth              1.4.2                
google-auth-httplib2     0.0.3                
google-auth-oauthlib     0.2.0                
google-cloud-bigquery    1.8.1                
google-cloud-core        0.29.1               
google-cloud-language    1.0.2                
google-cloud-storage     1.8.0                
google-cloud-translate   1.3.3                
google-colab             0.0.1a1              
google-pasta             0.1.1                
google-resumable-media   0.3.2                
googleapis-common-protos 1.5.6                
googledrivedownloader    0.3                  
graph-nets               1.0.2                
graphviz                 0.10.1               
greenlet                 0.4.15               
grpcio                   1.15.0               
gspread                  3.0.1                
gspread-dataframe        3.0.2                
gunicorn                 19.9.0               
gym                      0.10.11              
h5netcdf                 0.6.2                
h5py                     2.8.0                
HeapDict                 1.0.0                
holidays                 0.9.9                
html5lib                 0.9999999            
httpimport               0.5.16               
httplib2                 0.11.3               
humanize                 0.5.1                
hyperopt                 0.1.1                
ideep4py                 2.0.0.post3          
idna                     2.6                  
image                    1.5.27               
imageio                  2.4.1                
imagesize                1.1.0                
imbalanced-learn         0.4.3                
imblearn                 0.0                  
imgaug                   0.2.6                
imutils                  0.5.2                
inflect                  2.1.0                
intel-openmp             2019.0               
intervaltree             2.1.0                
ipykernel                4.6.1                
ipython                  5.5.0                
ipython-genutils         0.2.0                
ipython-sql              0.3.9                
ipywidgets               7.4.2                
itsdangerous             1.1.0                
jdcal                    1.4                  
jieba                    0.39                 
Jinja2                   2.10                 
jmespath                 0.9.3                
joblib                   0.13.1               
jpeg4py                  0.1.4                
jsonschema               2.6.0                
jupyter                  1.0.0                
jupyter-client           5.2.4                
jupyter-console          6.0.0                
jupyter-core             4.4.0                
kaggle                   1.5.2                
kapre                    0.1.3.1              
Keras                    2.2.4                
Keras-Applications       1.0.7                
Keras-Preprocessing      1.0.9                
keras-vis                0.4.1                
kiwisolver               1.0.1                
knnimpute                0.1.0                
librosa                  0.6.2                
lightgbm                 2.2.3                
llvmlite                 0.27.0               
lmdb                     0.94                 
lucid                    0.3.8                
lunardate                0.2.0                
lxml                     4.2.6                
magenta                  0.3.19               
Markdown                 3.0.1                
MarkupSafe               1.1.0                
matplotlib               3.0.2                
matplotlib-venn          0.11.5               
mesh-tensorflow          0.0.5                
mido                     1.2.6                
mir-eval                 0.5                  
missingno                0.4.1                
mistune                  0.8.4                
mkl                      2019.0               
mlxtend                  0.14.0               
mock                     2.0.0                
more-itertools           5.0.0                
moviepy                  0.2.3.5              
mpi4py                   3.0.0                
mpmath                   1.1.0                
msgpack                  0.5.6                
msgpack-numpy            0.4.4.2              
multiprocess             0.70.7               
multitasking             0.0.7                
murmurhash               1.0.1                
music21                  5.5.0                
natsort                  5.5.0                
nbconvert                5.4.0                
nbformat                 4.4.0                
netCDF4                  1.4.2                
networkx                 2.2                  
nibabel                  2.3.3                
nltk                     3.2.5                
nose                     1.3.7                
notebook                 5.2.2                
np-utils                 0.5.9.0              
numba                    0.40.1               
numexpr                  2.6.9                
numpy                    1.14.6               
nvidia-ml-py3            7.352.0              
oauth2client             4.1.3                
oauthlib                 3.0.1                
okgrade                  0.4.3                
olefile                  0.46                 
opencv-contrib-python    3.4.3.18             
opencv-python            3.4.5.20             
openpyxl                 2.5.9                
osqp                     0.5.0                
packaging                19.0                 
pandas                   0.22.0               
pandas-datareader        0.7.0                
pandas-gbq               0.4.1                
pandas-profiling         1.4.1                
pandocfilters            1.4.2                
pathlib                  1.0.1                
patsy                    0.5.1                
pbr                      5.1.2                
pexpect                  4.6.0                
pickleshare              0.7.5                
Pillow                   4.0.0                
pip                      19.0.1               
plac                     0.9.6                
plotly                   1.12.12              
pluggy                   0.8.1                
portpicker               1.2.0                
prefetch-generator       1.0.1                
preshed                  2.0.1                
pretty-midi              0.2.8                
prettytable              0.7.2                
progressbar2             3.38.0               
promise                  2.2.1                
prompt-toolkit           1.0.15               
protobuf                 3.6.1                
psutil                   5.4.8                
psycopg2                 2.7.6.1              
ptyprocess               0.6.0                
py                       1.7.0                
pyasn1                   0.4.5                
pyasn1-modules           0.2.4                
pycocotools              2.0.0                
pycparser                2.19                 
pydot                    1.3.0                
pydot-ng                 2.0.0                
pydotplus                2.0.2                
pyemd                    0.5.1                
pyglet                   1.3.2                
Pygments                 2.1.3                
pygobject                3.26.1               
pymc3                    3.6                  
pymongo                  3.7.2                
pymystem3                0.2.0                
PyOpenGL                 3.1.0                
pyparsing                2.3.1                
pysndfile                1.3.2                
PySocks                  1.6.8                
pystache                 0.5.4                
pystan                   2.18.1.0             
pytest                   3.10.1               
python-apt               1.6.3+ubuntu1        
python-chess             0.23.11              
python-dateutil          2.5.3                
python-louvain           0.13                 
python-rtmidi            1.2.1                
python-slugify           2.0.1                
python-utils             2.3.0                
pytz                     2018.9               
PyWavelets               1.0.1                
PyYAML                   3.13                 
pyzmq                    17.0.0               
qtconsole                4.4.3                
regex                    2018.1.10            
requests                 2.18.4               
requests-oauthlib        1.2.0                
resampy                  0.2.1                
rpy2                     2.9.5                
rsa                      4.0                  
s3fs                     0.2.0                
s3transfer               0.2.0                
scikit-image             0.13.1               
scikit-learn             0.20.2               
scipy                    1.1.0                
screen-resolution-extra  0.0.0                
scs                      2.0.2                
seaborn                  0.7.1                
setuptools               40.8.0               
setuptools-git           1.2                  
simplegeneric            0.8.1                
six                      1.11.0               
sklearn                  0.0                  
smart-open               1.8.0                
snowballstemmer          1.2.1                
sortedcontainers         2.1.0                
spacy                    2.0.18               
Sphinx                   1.8.4                
sphinxcontrib-websupport 1.1.0                
SQLAlchemy               1.2.17               
sqlparse                 0.2.4                
stable-baselines         2.2.1                
statsmodels              0.8.0                
sympy                    1.1.1                
tables                   3.4.4                
tabulate                 0.8.3                
tb-nightly               1.13.0a20190211      
tblib                    1.3.2                
tensor2tensor            1.11.0               
tensorboard              1.12.2               
tensorboardcolab         0.0.22               
tensorflow               1.12.0               
tensorflow-estimator     1.10.12              
tensorflow-hub           0.2.0                
tensorflow-metadata      0.9.0                
tensorflow-probability   0.5.0                
tensorpack               0.9.1                
termcolor                1.1.0                
terminado                0.8.1                
testpath                 0.4.2                
textblob                 0.15.2               
textgenrnn               1.4.1                
tf-estimator-nightly     1.14.0.dev2019021101 
tf-nightly-gpu           1.13.0.dev20190208   
tfds-nightly             0.0.2.dev201902070013
tflearn                  0.3.2                
Theano                   1.0.4                
thinc                    6.12.1               
toolz                    0.9.0                
torch                    1.0.0                
torchsummary             1.5.1                
torchtext                0.3.1                
torchvision              0.2.1                
tornado                  4.5.3                
tqdm                     4.28.1               
traitlets                4.3.2                
tweepy                   3.6.0                
typing                   3.6.6                
tzlocal                  1.5.1                
ujson                    1.35                 
umap-learn               0.3.7                
Unidecode                1.0.23               
uritemplate              3.0.0                
urllib3                  1.22                 
vega-datasets            0.7.0                
wcwidth                  0.1.7                
webencodings             0.5.1                
Werkzeug                 0.14.1               
wheel                    0.32.3               
widgetsnbextension       3.4.2                
wordcloud                1.5.0                
wrapt                    1.11.1               
xarray                   0.11.3               
xgboost                  0.7.post4            
xkit                     0.0.0                
xlrd                     1.1.0                
xlwt                     1.3.0                
yellowbrick              0.9.1                
zict                     0.1.3                
zmq                      0.0.0 
```

**Comment by ppwwyyxx** [comment]
3it/s is actually better than 3s/it

**Comment by JamesBrightman** [comment]
Yeah, I'm pleased with how it's all looking, holding 3it/s and targeting a ~20min epoch.
