### ISSUE TITLE
What is the correct way to batch data with the input pipeline in FRCNN example？

### ISSUE THREAD

**Issue by Yizhouw21** [tensorpack/tensorpack#1092]
Hi, 
I am new to TensorPack. I am trying to batch data based on tensorpack/examples/FasterRCNN/data.py pipeline on COCO dataset.  

Can I Simply add BatchData() and  PrefetchData after ds = MultiProcessMapDataZMQ(ds, 10, preprocess) in the original get_train_dataflow() function. For example:
```
def get_train_dataflow():
    ...........
    if cfg.TRAINER == 'horovod':
        ds = MultiThreadMapData(ds, 5, preprocess)
        # MPI does not like fork()
    else:
        ds = MultiProcessMapDataZMQ(ds, 10, preprocess)
    ds = BatchData(ds, 8)
    ds = PrefectchData(ds,500,1)
    return ds
```
And then use `StagingInput(QueueInput(train_dataflow),1)` like the ImageNet example did.
Would this be the correct way? 

Thanks!

**Comment by ppwwyyxx** [comment]
It would be incorrect because input data has different shapes and cannot be naively batched, and the model implementation does not handle >1 images.

**Comment by Yizhouw21** [comment]
Thanks for the reply! 
Yes, I just realized the shape of elements in `ret`  returned by `preprocess` are different among images.
For the model, because we are using another model implementation that can handle images > 1, I think that would not be a problem.  And besides those two problems, would the usage of TensorPack dataflow and input source API be correct?

I will try to find some solutions to solve the shape issue of the input data. Since it is not a TensorPack problem, I will close the issue. But it would be perfect if you can also share some thoughts about it.

Thanks!

**Comment by ppwwyyxx** [comment]
You will need to modify the `inputs` method of the model so that it matches whatever produced by the dataflow. And also write the model implementation which takes a list of `inputs`.

**Comment by Yizhouw21** [comment]
Hi, I managed to encode the inputs to the same shape by add some tensor operations in `preproc()`. And I batched them successfully using ``BatchData()`.
````
def get_train_dataflow(batch_size):
   ....
    ds = MapData(ds, preprocess)
    ds = BatchData(ds, batch_size, use_list=True)
    return ds
````

 As the result the dataflow will produce list of lists of tensors. 

````
batch_size = 32
ds.reset_state(batch_size)
for k in ds:
    print(k)

[0228 19:34:05 @common.py:816] DataFlow Info:
datapoint 0<100 with 4 components consists of
  0: list of len 32
    0: Tensor
    1: Tensor
    2: Tensor
    ...
  1: list of len 32
    0: Tensor
    1: Tensor
    2: Tensor
    ...
  2: list of len 32
    0: Tensor
    1: Tensor
    2: Tensor
    ...
  3: list of len 32
    0: Tensor
    1: Tensor
    2: Tensor
    ...

````
And maintained the ‘Inputs’ method returning a list of `tf.placeholder`. And feed the data with  `QueueInputs()`. But I am getting error like this
```
[0228 19:56:10 @base.py:242] Graph Finalized.
[0228 19:56:10 @concurrency.py:38] Starting EnqueueThread QueueInput/input_queue ...
[0228 19:56:10 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
[0228 19:56:11 @param.py:158] [HyperParamSetter] At global_step=0, learning_rate is set to 0.003300
[0228 19:56:11 @eval.py:219] [EvalCallback] Will evaluate every 25 epochs
[0228 19:56:12 @base.py:274] Start Epoch 1 ...
  0%|                                                                                                                                                                   |0/500[00:00<?,?it/s][0228 19:56:48 @input_source.py:170] ERR Exception in EnqueueThread QueueInput/input_queue:
Traceback (most recent call last):
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 162, in run
    self.op.run(feed_dict=feed)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2377, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5215, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1104, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
[0228 19:56:48 @input_source.py:176] EnqueueThread QueueInput/input_queue Exited.
[0228 19:56:48 @base.py:290] Training was stopped by exception FIFOQueue '_0_QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: QueueInput/input_deque = QueueDequeueV2[component_types=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](QueueInput/input_queue)]]
         [[Node: apply_gradients/AccumGradOptimizer/apply_grad_0/Momentum/update_group1/block0/conv1/W/ApplyMomentum/_624 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_7355_...lyMomentum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'QueueInput/input_deque', defined at:
  File "train_ssd.py", line 451, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/train/interface.py", line 84, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/train/tower.py", line 214, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 193, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 225, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 121, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 116, in call_for_each_tower
    ret.append(func())
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/train/tower.py", line 242, in get_grad_fn
    inputs = input.get_input_tensors()
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/input_source/input_source_base.py", line 82, in get_input_tensors
    return self._get_input_tensors()
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 267, in _get_input_tensors
    ret = self.queue.dequeue(name='input_deque')
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 440, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3734, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): FIFOQueue '_0_QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: QueueInput/input_deque = QueueDequeueV2[component_types=[DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](QueueInput/input_queue)]]
         [[Node: apply_gradients/AccumGradOptimizer/apply_grad_0/Momentum/update_group1/block0/conv1/W/ApplyMomentum/_624 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_7355_...lyMomentum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
.
```
I am not sure if this is caused by wrong usages of TensorPack functions. But it would be perfect if you can share some thoughts to figure out the bug.
Thanks very much!

**Comment by ppwwyyxx** [comment]
Tensorflow takes numpy arrays. So you cannot use `use_list=True`.

**Comment by ppwwyyxx** [comment]
More correctly, I think tensorflow may be able to accept lists, if the lists can be converted to a numpy array. But anyway it's still better for you to convert it so it fails early. Perhaps there are still certain field in the data that has different shapes and cannot be batched naively.

**Comment by Yizhouw21** [comment]
Thanks for the quick reply! I tried `use_list = False`. I think the problem is that our `Preproc()` function returns a list of `Tensor`, but `BatchData` and `numpy`cannot undertand `Tensor` elements, rather than the inconstant shapes. 

````
def get_train_dataflow(batch_size):
   ....
    ds = MapData(ds, preprocess)
    ds = BatchData(ds, batch_size, use_list=True)
    return ds

batch_size = 32
ds.reset_state(batch_size)
for k in ds:
    print(k)
`````
````
[0301 12:06:49 @common.py:142] ERR Cannot batch data. Perhaps they are of inconsistent shape?
Traceback (most recent call last):
  File "/home/shared/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 140, in _batch_numpy
    return np.asarray(data_list, dtype=dtype)
  File "/home/shared/anaconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: data type not understood
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

````

**Comment by ppwwyyxx** [comment]
Like I said you need to use numpy arrays, not Tensor

**Comment by zxpeter** [comment]
Hi, 
I'm also using FRCNN example and I noticed default batch_size=8 is mentioned in config.py.
And I didn't find the place to change batch_size param in config or other place, is that can be changed?

**Comment by ppwwyyxx** [comment]
> I'm also using FRCNN example and I noticed default batch_size=8 is mentioned in config.py

No, there is no default batch_size=8 in config.py.

You can change any config in the config file.

**Comment by zxpeter** [comment]
Hi, 
I mean I can find it in the commented line like:
`# LR_SCHEDULE means equivalent steps when the total batch size is 8.
`
So I assume the default is 8, and I 'm wondering if the config 'batch_size' can be changed ?

**Comment by ppwwyyxx** [comment]
The batch size is 1 per GPU as said in NOTES.md and cannot be changed.

**Comment by zxpeter** [comment]
Yes I find it. Thanks for the quick reply!
> We currently only support single image per GPU.
