### ISSUE TITLE
DeadlineExceededError training FRCNN

### ISSUE THREAD

**Issue by dcyoung** [tensorpack/tensorpack#1097]
I am attempting to train FRCNN on a custom dataset.

```bash
./train.py \
    --logdir=logs/$(date +%Y%m%dT%H%M%S) \
    --config \
    MODE_MASK=False \
    MODE_FPN=True \
    DATA.BASEDIR=/path/to/data \
    BACKBONE.WEIGHTS=/path/to/imagenet/ImageNet-R50-AlignPadding.npz
```

If I limit the `STEPS_PER_EPOCH` and `EVAL_PERIOD` to trivial values, i can verify that the network will train for many more epochs and evaluate properly. However, if I run with the default values, I encounter an unexpected error a few epochs into training. This is relatively repeatable (sometimes 7th, sometimes 8th epoch).

I'm assuming the error resides in code i have introduced to load and pre-process the custom dataset, however I'm not sure where to start debugging given the output logs below.

```bash
...

[0301 15:46:51 @base.py:274] Start Epoch 6 ...
100%|##########################################################################################################################|500/500[02:04<00:00, 4.03it/s]
[0301 15:48:55 @base.py:284] Epoch 6 (global_step 3000) finished, time:2 minutes 4 seconds.
[0301 15:48:55 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
[0301 15:48:55 @misc.py:109] Estimated Time Left: 4 days 3 hours 28 minutes 43 seconds
[0301 15:48:55 @monitor.py:467] GPUUtil/0: 81.114
[0301 15:48:55 @monitor.py:467] GPUUtil/1: 78.041
[0301 15:48:55 @monitor.py:467] PeakMemory(MB)/gpu:0: 6237.2
[0301 15:48:55 @monitor.py:467] QueueInput/queue_size: 49.153
[0301 15:48:55 @monitor.py:467] fastrcnn_losses/box_loss: 0.051342
[0301 15:48:55 @monitor.py:467] fastrcnn_losses/label_loss: 0.067238
[0301 15:48:55 @monitor.py:467] fastrcnn_losses/label_metrics/accuracy: 0.97825
[0301 15:48:55 @monitor.py:467] fastrcnn_losses/label_metrics/false_negative: 0.37059
[0301 15:48:55 @monitor.py:467] fastrcnn_losses/label_metrics/fg_accuracy: 0.58835
[0301 15:48:55 @monitor.py:467] fastrcnn_losses/num_fg_label: 29.729
[0301 15:48:55 @monitor.py:467] learning_rate: 0.01
[0301 15:48:55 @monitor.py:467] multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level2: 326.96
[0301 15:48:55 @monitor.py:467] multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level3: 104.09
[0301 15:48:55 @monitor.py:467] multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level4: 75.568
[0301 15:48:55 @monitor.py:467] multilevel_roi_align/fpn_map_rois_to_levels/num_roi_level5: 5.3747
[0301 15:48:55 @monitor.py:467] rpn_losses/box_loss: 0.016252
[0301 15:48:55 @monitor.py:467] rpn_losses/label_loss: 0.010862
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/box_loss: 0.010058
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/label_loss: 0.0044852
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/label_metrics/precision_th0.1: 0.49182
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/label_metrics/precision_th0.2: 0.52859
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/label_metrics/precision_th0.5: 0.61117
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/label_metrics/recall_th0.1: 0.6625
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/label_metrics/recall_th0.2: 0.66225
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/label_metrics/recall_th0.5: 0.66061
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/num_pos_anchor: 7.6518
[0301 15:48:55 @monitor.py:467] rpn_losses/level2/num_valid_anchor: 197.74
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/box_loss: 0.0014701
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/label_loss: 0.0027832
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/label_metrics/precision_th0.1: 0.6836
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/label_metrics/precision_th0.2: 0.7011
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/label_metrics/precision_th0.5: 0.72164
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/label_metrics/recall_th0.1: 0.77287
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/label_metrics/recall_th0.2: 0.7723
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/label_metrics/recall_th0.5: 0.77133
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/num_pos_anchor: 2.6371
[0301 15:48:55 @monitor.py:467] rpn_losses/level3/num_valid_anchor: 44.858
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/box_loss: 0.0033005
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/label_loss: 0.0025138
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/label_metrics/precision_th0.1: 0.54063
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/label_metrics/precision_th0.2: 0.57946
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/label_metrics/precision_th0.5: 0.58547
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/label_metrics/recall_th0.1: 0.60929
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/label_metrics/recall_th0.2: 0.60929
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/label_metrics/recall_th0.5: 0.60544
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/num_pos_anchor: 1.6743
[0301 15:48:55 @monitor.py:467] rpn_losses/level4/num_valid_anchor: 11.156
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/box_loss: 0.00032346
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/label_loss: 0.00064774
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/label_metrics/precision_th0.1: 0.41074
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/label_metrics/precision_th0.2: 0.44769
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/label_metrics/precision_th0.5: 0.49859
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/label_metrics/recall_th0.1: 0.51853
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/label_metrics/recall_th0.2: 0.51853
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/label_metrics/recall_th0.5: 0.51831
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/num_pos_anchor: 0.14426
[0301 15:48:55 @monitor.py:467] rpn_losses/level5/num_valid_anchor: 1.8522
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/box_loss: 0.0010992
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/label_loss: 0.00043163
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/label_metrics/precision_th0.1: 0.48196
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/label_metrics/precision_th0.2: 0.50243
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/label_metrics/precision_th0.5: 0.52389
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/label_metrics/recall_th0.1: 0.52154
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/label_metrics/recall_th0.2: 0.52154
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/label_metrics/recall_th0.5: 0.52154
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/num_pos_anchor: 0.29413
[0301 15:48:55 @monitor.py:467] rpn_losses/level6/num_valid_anchor: 0.39637
[0301 15:48:55 @monitor.py:467] sample_fast_rcnn_targets/num_bg: 482.27
[0301 15:48:55 @monitor.py:467] sample_fast_rcnn_targets/num_fg: 29.729
[0301 15:48:55 @monitor.py:467] sample_fast_rcnn_targets/proposal_metrics/best_iou_per_gt: 0.7819
[0301 15:48:55 @monitor.py:467] sample_fast_rcnn_targets/proposal_metrics/recall_iou0.3: 0.99787
[0301 15:48:55 @monitor.py:467] sample_fast_rcnn_targets/proposal_metrics/recall_iou0.5: 0.99712
[0301 15:48:55 @monitor.py:467] total_cost: 0.61077
[0301 15:48:55 @monitor.py:467] wd_cost: 0.46508
[0301 15:48:55 @base.py:274] Start Epoch 7 ...
 79%|################################################################################################8                         |397/500[03:03<00:47, 2.16it/s]
2019-03-01 15:51:59.721348: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DeadlineExceededError: Timed out waiting for notification

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 517, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorpack/train/interface.py", line 94, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorpack/train/base.py", line 343, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorpack/train/base.py", line 315, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorpack/train/base.py", line 280, in main_loop
    self.run_step()  # implemented by subclass
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorpack/train/base.py", line 180, in run_step
    self.hooked_sess.run(self.train_op)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/user/miniconda3/envs/rip-tensorpack/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DeadlineExceededError: Timed out waiting for notification
MultiProcessMapDataZMQ successfully cleaned-up.

```

If it helps, my environment is:
- Python version: 3.6
- TF version: 1.12
- Tensorpack version: latest
- Hardware information: 2 x 1080ti

I don't expect assistance debugging my custom code, but I'm wondering if I am missing something obvious from this log. And if not, I would greatly appreciate any advice on how to get additional debugging info in this situation.
Thanks!

**Comment by ppwwyyxx** [comment]
> If I limit the STEPS_PER_EPOCH and EVAL_PERIOD to trivial values,

what do you mean by trivial values?
Presumable changing these two values should not have an effect on failures.

For debugging I would start with (1) trying to run the dataflow in a loop to see if it fails after a while (2) train without custom callbacks

**Comment by dcyoung** [comment]
Thanks for the quick response. 

By "trivial" values i meant very small (to test that this wasn't an issue related to epoch transitions or epoch-based callbacks). More specifically I tried with `TRAIN.STEPS_PER_EPOCH=5` and `TRAIN.EVAL_PERIOD=3`, and observed the training session run for >40 epochs without issue before manually killing it.


My first thought would be that the issue is related to a rare data sample which wasn't encountered in that time. However I encountered no issues looping through the entirety of both training and eval dataflows. 

I tried removing callbacks to identify the culprit but no such luck.

Checking a resource monitor, it appears that main memory is filling up slowly during training, and hitting 100% (64GB) at the time of crash.... likely a slow down, which then causes a timeout via `SessionRunTimeout`. I'll investigate the source of the leak.

**Comment by dcyoung** [comment]
Training from a fresh tenorpack repo using COCO data results in stable memory consumption around ~40 GBs or so. With my own data, I could not avoid memory saturation when using `MultiProcessMapDataZMQ`. I switched to `MapData` instead which sits stable at ~17Gb. I'm closing for now as this is likely something specific to my own data preprocessing. Thanks again.

**Comment by ppwwyyxx** [comment]
`MultiProcessMapDataZMQ` has a `buffer_size` option which can control the memory consumption.

**Comment by dcyoung** [comment]
@ppwwyyxx  thanks for the suggestion.

I experimented with different params in `MultiProcessMapDataZMQ`. However, even with small values (`nr_proc=2` + `buffer_size=5`), I still saw rising memory usage until overflow during training.

I know referring to exact numbers is difficult with custom data... but do the following *relative* values make sense? That is to say, is it expected that a call like:

```python
ds = MultiProcessMapDataZMQ(ds, nr_proc=10, map_func=preprocess, buffer_size=5)
```
could yield > 64GB of memory usage during training, while the following call:

```python
ds = MapData(ds, preprocess)
```
yields a stable ~17Gb.

Additionally, why is it that memory usage would rise during training, but not when testing the dataflow in isolation, like so:
```python
ds = get_train_dataflow()

ds = PrintData(ds, 100)
TestDataSpeed(ds, 50000).start()
ds.reset_state()
for k in ds:
    pass
```

**Comment by ppwwyyxx** [comment]
The memory usage should not rise during training and you can probably see that it does not rise (and in my experiment, stays <20GB with multiprocessing) with the examples unmodified.

If running the dataflow alone does not increase memory usage, dataflow is probably unrelated to the growth in memory you observed.

**Comment by dcyoung** [comment]
Given that in all cases, testing the dataflow directly does not show rising memory usage, I would have assumed the same. However I'm witnessing the following, when testing on my own local machine:

#### 1) Default Example
Training from a fresh tensorpack repo using COCO data.
Results in stable memory consumption around ~40 GB or so during training. 

#### 2) Training with Custom dataflow, MultiProcessMapDataZMQ
Unmodified code, apart from a custom dataflow.
Results in memory overflow > 64GB, regardless of params supplied to `MultiProcessMapDataZMQ`

#### 3) Training with Custom dataflow, MapData
Unmodified code, apart from a custom dataflow. `MultiProcessMapDataZMQ` is replaced with `MapData`.
Results in staple memory consumption around ~17GB  or so during training.

Given the following:
- large difference in memory consumption between your experiment and my own using the default example (case **1** above) 
- only difference between the above cases **2** and **3**, is the map function, and yet they each yield dramatically different memory usage during training

I would think there could be something unexpected about how my system is running `MultiProcessMapDataZMQ`. Any recommendations for further debugging?

**Comment by dcyoung** [comment]
Edit: added 4th case above, which I think verifies this is related to my system, so I'll close the issue again...
