### ISSUE TITLE
My model was retrained after epoch 5 it went back to epoch 1

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [tensorpack/tensorpack#1123]
Hi was training my model 
```
100%|############################################################|10000/10000[1:48:07<00:00, 1.59it/s]
[0327 13:55:47 @base.py:260] Epoch 2 (global_step 20000) finished, time:1 hour 48 minutes 7 seconds.
[0327 13:55:48 @saver.py:77] Model saved to train_log/TGAN_synthesizer:KDD-0/model-20000.
[0327 13:55:48 @monitor.py:440] GAN_loss/discrim/accuracy_fake: 0.96
[0327 13:55:48 @monitor.py:440] GAN_loss/discrim/accuracy_real: 1
[0327 13:55:48 @monitor.py:440] GAN_loss/discrim/loss: 0.18884
[0327 13:55:48 @monitor.py:440] GAN_loss/gen/final-g-loss: 7.0647
[0327 13:55:48 @monitor.py:440] GAN_loss/gen/klloss: 2.444
[0327 13:55:48 @monitor.py:440] GAN_loss/gen/loss: 4.6207
[0327 13:55:48 @monitor.py:440] QueueInput/queue_size: 50
[0327 13:55:48 @base.py:250] Start Epoch 3 ...
100%|##############################################################|10000/10000[50:46<00:00, 3.48it/s]
[0327 14:22:41 @base.py:260] Epoch 5 (global_step 50000) finished, time:50 minutes 46 seconds.
[0327 14:22:41 @saver.py:77] Model saved to train_log/TGAN_synthesizer:KDD-2/model-50000.
[0327 14:22:41 @monitor.py:440] GAN_loss/discrim/accuracy_fake: 0.99
[0327 14:22:41 @monitor.py:440] GAN_loss/discrim/accuracy_real: 1
[0327 14:22:41 @monitor.py:440] GAN_loss/discrim/loss: 0.13903
[0327 14:22:41 @monitor.py:440] GAN_loss/gen/final-g-loss: 4.2788
[0327 14:22:41 @monitor.py:440] GAN_loss/gen/klloss: 0.28196
[0327 14:22:41 @monitor.py:440] GAN_loss/gen/loss: 3.9968
[0327 14:22:41 @monitor.py:440] QueueInput/queue_size: 50
[0327 14:22:41 @base.py:264] Training has finished!
```

but suddenly, it showed these error and it automatically went back to train epoch 1 again

```
2019-03-27 23:03:06.579435: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
 60%|########################################################################################################4                                                                    |3018/5000[46:27<25:53, 1.28it/s]Traceback (most recent call last):
  File "src/TGAN_synthesizer.py", line 313, in <module>
    sample(args.sample, Model(), args.load, output_filename=args.output)
  File "src/TGAN_synthesizer.py", line 234, in sample
    session_init=get_model_loader(model_path),
  File "/home/harry/Documents/GANs-demo/TGAN-master/py36_env/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 262, in get_model_loader
    return SaverRestore(filename)
  File "/home/harry/Documents/GANs-demo/TGAN-master/py36_env/lib/python3.6/site-packages/tensorpack/tfutils/sessinit.py", line 107, in __init__
    model_path = get_checkpoint_path(model_path)
  File "/home/harry/Documents/GANs-demo/TGAN-master/py36_env/lib/python3.6/site-packages/tensorpack/tfutils/varmanip.py", line 182, in get_checkpoint_path
    assert tf.gfile.Exists(model_path) or tf.gfile.Exists(model_path + '.index'), model_path
AssertionError: train_log/TGAN_synthesizer:KDD2-2/model-0

[0328 08:41:58 @base.py:187] Setup callbacks graph ...
[0328 08:41:58 @summary.py:38] Maintain moving average summary of 6 tensors in collection MOVING_SUMMARY_OPS.
[0328 08:41:58 @summary.py:75] Summarizing collection 'summaries' of size 9.
[0328 08:41:58 @graph.py:91] Applying collection UPDATE_OPS of 16 ops.
[0328 08:41:59 @base.py:205] Creating the session ...
2019-03-28 08:42:00.103178: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[0328 08:42:01 @base.py:211] Initializing the session ...
[0328 08:42:01 @base.py:218] Graph Finalized.
[0328 08:42:01 @concurrency.py:37] Starting EnqueueThread QueueInput/input_queue ...
[0328 08:42:01 @base.py:250] Start Epoch 1 ...
100%|########################################################

```
Please help me.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by TrinhDinhPhuc** [comment]
Sorry if it confuses you, This is exactly the same my error: https://github.com/tensorpack/tensorpack/issues/500

**Comment by ppwwyyxx** [comment]
Then is your issue solved by #500?

**Comment by TrinhDinhPhuc** [comment]
No. Why it was training like a loop. I chose epoch = 2. After successfully finished training
```
[0328 09:13:48 @base.py:250] Start Epoch 2 ...
100%|#############################################################################################################################################################################|5000/5000[31:50<00:00, 2.62it/s]
[0328 09:45:38 @base.py:260] Epoch 2 (global_step 10000) finished, time:31 minutes 50 seconds.

```
It went back to Epoch 1 and started training again
```

Total #vars=94, #params=1675875, size=6.39MB
[0328 10:11:46 @base.py:187] Setup callbacks graph ...
[0328 10:11:46 @summary.py:38] Maintain moving average summary of 6 tensors in collection MOVING_SUMMARY_OPS.
[0328 10:11:46 @summary.py:75] Summarizing collection 'summaries' of size 9.
[0328 10:11:46 @graph.py:91] Applying collection UPDATE_OPS of 12 ops.
[0328 10:11:47 @base.py:205] Creating the session ...
2019-03-28 10:11:47.894942: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[0328 10:11:48 @base.py:211] Initializing the session ...
[0328 10:11:48 @base.py:218] Graph Finalized.
[0328 10:11:48 @concurrency.py:37] Starting EnqueueThread QueueInput/input_queue ...
[0328 10:11:49 @base.py:250] Start Epoch 1 ...
```

**Comment by ppwwyyxx** [comment]
> Why it was training like a loop

The most likely explanation is that there is such a loop in the code you run.

Without code and other details that I asked for in the comment above, I am unable to understand your issue just from the partial logs.

**Comment by ppwwyyxx** [comment]
From the log, it appears that you're using this project: https://github.com/DAI-Lab/TGAN

It does have loops that trains another model after finishing training one: https://github.com/DAI-Lab/TGAN/blob/25fd2384eb38d13c53cd0eb20bf2c3577b7ff878/src/launcher_simple.py#L124-L125

Closing as this is unrelated to tensorpack. If you have questions about the usage of a different project, please ask at that project.
