### ISSUE TITLE
Debug using LocalCLIDebugWrapperSession through TrainConfig resulting Value error in device:CPU:0

### ISSUE THREAD

**Issue by zhou-git** [tensorpack/tensorpack#1142]
Hi,

Thank you very much for providing such an efficient framework for training with tensorflow, I learnt a lot simply by studying the code. Recently I try to debug a customized code based on  example/FasterRCNN and tfdbg, and an error occurred. Unfortunately I can only understand the deeper mechanism of handling graphs between CPU and GPU in a superficial level, so I would be grateful if you could help here. 

### 1. What you did:

(1) Debugging a code based on examples/FasterRCNN, The network I build is a segmentation network for point clouds data. 

(2) Following issue #191 , I pass the 
`SessionCreatorAdapter(NewSessionCreator(), lambda sess： tf_debug.LocalCLIDebugWrapperSession(sess))` to `TrainConfig` through `session_creator`:

(3)I then try to debug using terminal, the tfdbg start successfully. In the first run, I can only observe the tensor "global_step:0", in the second run, the following error occurs. 

### 2. What you observed:
Logs are provided in full length:
I can't understand the error message, tfdbg is complaining that the node `instance_seg_point_mlp1/W/Momentum` is not existed in `/job:localhost/replica:0/task:0/device:CPU:0`, which maybe is a replicate of the graph made by the debugger? 

 
`[0415 11:02:08 @train_fpnet.py:485] Warm Up Schedule (steps, value): [(0, 0.0033000000000000004), (1000, 0.01)]
[0415 11:02:08 @train_fpnet.py:486] LR Schedule (epochs, value): [(2, 0.01), (1920.0, 0.001), (2560.0, 0.00010000000000000002)]
[0415 11:02:18 @train_fpnet.py:490] Total passes of the training set is: 1253.8
[0415 11:02:18 @prof.py:46] WRN [GPUUtilizationTracker] Both devices and CUDA_VISIBLE_DEVICES are None! Will monitor all 2 visible GPUs!
[0415 11:02:18 @training.py:49] [DataParallel] Training a model of 2 towers.
[0415 11:02:18 @interface.py:43] Automatically applying StagingInput on the DataFlow.
[0415 11:02:18 @input_source.py:220] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0415 11:02:18 @training.py:109] Building graph for training tower 0 on device /gpu:0 ...
... some register staff...
[0415 11:02:19 @training.py:109] Building graph for training tower 1 on device /gpu:1 ...
[0415 11:02:21 @collection.py:164] These collections were modified but restored in tower1: (tf.GraphKeys.SUMMARIES: 11->12)
[0415 11:02:22 @training.py:347] 'sync_variables_from_main_tower' includes 138 operations.
[0415 11:02:22 @model_utils.py:64] Trainable Variables: 
name                          shape                 dim
----------------------------  -----------------  ------
instance_seg_point_mlp1/W:0   [1, 1, 3, 64]         192
instance_seg_point_mlp1/b:0   [64]                   64
instance_seg_point_mlp2/W:0   [1, 1, 64, 64]       4096
instance_seg_point_mlp2/b:0   [64]                   64
instance_seg_point_mlp3/W:0   [1, 1, 64, 64]       4096
instance_seg_point_mlp3/b:0   [64]                   64
instance_seg_global_mlp1/W:0  [1, 1, 64, 128]      8192
instance_seg_global_mlp1/b:0  [128]                 128
instance_seg_global_mlp2/W:0  [1, 1, 128, 1024]  131072
instance_seg_global_mlp2/b:0  [1024]               1024
instance_seg_full_mlp1/W:0    [1, 1, 1091, 512]  558592
instance_seg_full_mlp1/b:0    [512]                 512
instance_seg_full_mlp2/W:0    [1, 1, 512, 256]   131072
instance_seg_full_mlp2/b:0    [256]                 256
instance_seg_full_mlp3/W:0    [1, 1, 256, 128]    32768
instance_seg_full_mlp3/b:0    [128]                 128
instance_seg_full_mlp4/W:0    [1, 1, 128, 128]    16384
instance_seg_full_mlp4/b:0    [128]                 128
instance_seg_full_mlp5/W:0    [1, 1, 128, 2]        256
instance_seg_full_mlp5/b:0    [2]                     2
center_conv1_stage1/W:0       [1, 1, 3, 128]        384
center_conv1_stage1/b:0       [128]                 128
center_conv2_stage1/W:0       [1, 1, 128, 128]    16384
center_conv2_stage1/b:0       [128]                 128
center_conv3_stage1/W:0       [1, 1, 128, 256]    32768
center_conv3_stage1/b:0       [256]                 256
center_fc1_stage1/W:0         [259, 256]          66304
center_fc1_stage1/b:0         [256]                 256
center_fc2_stage1/W:0         [256, 128]          32768
center_fc2_stage1/b:0         [128]                 128
center_fc3_stage1/W:0         [128, 3]              384
center_fc3_stage1/b:0         [3]                     3
3D_box_mlp1/W:0               [1, 1, 3, 128]        384
3D_box_mlp1/b:0               [128]                 128
3D_box_mlp2/W:0               [1, 1, 128, 128]    16384
3D_box_mlp2/b:0               [128]                 128
3D_box_mlp3/W:0               [1, 1, 128, 256]    32768
3D_box_mlp3/b:0               [256]                 256
3D_box_mlp4/W:0               [1, 1, 256, 512]   131072
3D_box_mlp4/b:0               [512]                 512
3D_box_fc1/W:0                [515, 512]         263680
3D_box_fc1/b:0                [512]                 512
3D_box_fc2/W:0                [512, 256]         131072
3D_box_fc2/b:0                [256]                 256
3D_box_fc3/W:0                [256, 59]           15104
3D_box_fc3/b:0                [59]                   59
Total #vars=46, #params=1631296, size=6.22MB
[0415 11:02:22 @base.py:208] Setup callbacks graph ...
[0415 11:02:22 @tower.py:130] Building graph for predict tower 'tower-pred-0' on device /gpu:0 ...
[0415 11:02:23 @collection.py:164] These collections were modified but restored in tower-pred-0: (tf.GraphKeys.SUMMARIES: 11->12)
[0415 11:02:24 @summary.py:46] [MovingAverageSummary] 8 operations in collection 'MOVING_SUMMARY_OPS' will be run with session hooks.
[0415 11:02:24 @summary.py:93] Summarizing collection 'summaries' of size 11.
[0415 11:02:25 @base.py:229] Creating the session ...
2019-04-15 11:02:25.674833: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-04-15 11:02:25.859560: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56251d7adf40 executing computations on platform CUDA. Devices:
2019-04-15 11:02:25.859591: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-04-15 11:02:25.859599: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-04-15 11:02:25.880869: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-04-15 11:02:25.881386: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x56251d790c70 executing computations on platform Host. Devices:
2019-04-15 11:02:25.881424: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-04-15 11:02:25.882021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:17:00.0
totalMemory: 10.91GiB freeMemory: 9.79GiB
2019-04-15 11:02:25.882557: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:65:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2019-04-15 11:02:25.884238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0, 1
2019-04-15 11:02:25.887134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-15 11:02:25.887163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 1 
2019-04-15 11:02:25.887177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N Y 
2019-04-15 11:02:25.887186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 1:   Y N 
2019-04-15 11:02:25.888272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11063 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
2019-04-15 11:02:25.889176: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11066 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
[0415 11:02:27 @base.py:235] Initializing the session ...
[0415 11:02:27 @base.py:242] Graph Finalized.
[0415 11:02:58 @concurrency.py:38] Starting EnqueueThread QueueInput/input_queue ...
[0415 11:02:58 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
[0415 11:02:59 @input_source.py:170] ERR Exception in EnqueueThread QueueInput/input_queue:
Traceback (most recent call last):
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 162, in run
    self.op.run(feed_dict=feed)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2450, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5216, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/wrappers/framework.py", line 598, in run
    run_end_resp = self.on_run_end(run_end_req)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 339, in on_run_end
    self._dump_root, partition_graphs=partition_graphs)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 496, in __init__
    self._load_all_device_dumps(partition_graphs, validate)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 518, in _load_all_device_dumps
    self._load_partition_graphs(partition_graphs, validate)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 799, in _load_partition_graphs
    self._validate_dump_with_graphs(debug_graph.device_name)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 844, in _validate_dump_with_graphs
    "device %s." % (datum.node_name, device_name))
ValueError: Node name 'instance_seg_point_mlp1/W/AccumGrad' is not found in partition graphs of device /job:localhost/replica:0/task:0/device:CPU:0.
Traceback (most recent call last):
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorpack/train/base.py", line 268, in main_loop
    self._callbacks.before_train()
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 64, in before_train
    self._before_train()
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 74, in _before_train
    cb.before_train()
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 64, in before_train
    self._before_train()
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorpack/callbacks/graph.py", line 59, in _before_train
    self._op.run()
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2450, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5216, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/wrappers/framework.py", line 598, in run
    run_end_resp = self.on_run_end(run_end_req)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/wrappers/local_cli_wrapper.py", line 339, in on_run_end
    self._dump_root, partition_graphs=partition_graphs)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 496, in __init__
    self._load_all_device_dumps(partition_graphs, validate)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 518, in _load_all_device_dumps
    self._load_partition_graphs(partition_graphs, validate)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 799, in _load_partition_graphs
    self._validate_dump_with_graphs(debug_graph.device_name)
  File "/home/jin/anaconda3/envs/Mask/lib/python3.6/site-packages/tensorflow/python/debug/lib/debug_data.py", line 844, in _validate_dump_with_graphs
    "device %s." % (datum.node_name, device_name))
ValueError: Node name 'instance_seg_point_mlp1/W/AccumGrad' is not found in partition graphs of device /job:localhost/replica:0/task:0/device:CPU:0.`

### 4. Your environment:
  + Python version: 3.6.7
  + TF version: 1.13.1
  + Tensorpack version:0.9.1 
  + Number of GPU used: 2

**Comment by ppwwyyxx** [comment]
What did you enter in your debugger?

Could you launch debugger with this:
```python
 callbacks=[
            HookToCallback(tf_debug.LocalCLIDebugHook())
```
instead of the session wrapper?

**Comment by zhou-git** [comment]
After debugger started, it shows:
```
Session.run() call #1:
Fetch(es): global_step:0
Feed dict: (Empty)
```
I then enter `run` and the result is:

t(ms)   |   Size(B)   |   Op type    |   Tensor name   |
---------|---------------|----------------|----------------------|
|[0.000]     |190          |VariableV2    |global_step:0    |

Then I enter `run` again and the error occurs.

I will try the callback method and report back.

**Comment by ppwwyyxx** [comment]
It does not seem related to tensorpack, but I'm not sure what the warning means.

But if things are working for you I guess it doesn't matter.

**Comment by zhou-git** [comment]
Yes, I think so too, thank you very much for the help!
