### ISSUE TITLE
DeadlineExceededError: Timed out waiting for notification

### ISSUE THREAD

**Issue by sgambient** [tensorpack/tensorpack#1164]
### 1. What you did:

(1) **If you're using examples, what's the command you run:**

train.py as  exactly as in the  examples/FasterRCNN

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

No change.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

[0424 07:18:36 @sessinit.py:87] WRN The following variables are in the dict, but not found in the graph: linear/W, linear/b
[0424 07:18:36 @sessinit.py:218] Restoring 265 variables from dict ...
[0424 07:18:36 @base.py:243] Graph Finalized.
[0424 07:18:37 @concurrency.py:37] Starting EnqueueThread QueueInput/input_queue ...
[0424 07:18:37 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
[0424 07:18:45 @param.py:158] [HyperParamSetter] At global_step=0, learning_rate is set to 0.003300
[0424 07:18:47 @eval.py:222] [EvalCallback] Will evaluate every 25 epochs
[0424 07:18:51 @base.py:275] Start Epoch 1 ...
  0%|                                                             |0/500[00:00<?,?it/s]2019-04-24 07:19:12.312490: I tensorflow/stream_executor/dso_loader.cc:153] successfully opened CUDA library libcublas.so.10 locally
[0424 07:19:40 @param.py:161] [HyperParamSetter] At global_step=1, learning_rate changes from 0.003300 to 0.003307
  2%|8                                                    |8/500[01:00<36:53, 0.22it/s]2019-04-24 07:19:54.051077: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 6.58G (7063158016 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
 29%|##############7                                    |145/500[03:35<21:08, 0.28it/s]00000
2019-04-24 07:26:26.840079: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.DeadlineExceededError: Timed out waiting for notification

During handling of the above exception, another exception occurred:

### 4. Your environment:
  + Paste the output of this command: `python3 -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'`
 
tensorpack/examples/FasterRCNN# python3 -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'

--------------------  -------------------------------------------------------------------
sys.platform          linux
Python                3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
Tensorpack            0.9.4
Numpy                 1.14.5
TensorFlow            1.13.1/b'unknown'
TF Compiler Version   5.4.0 20160609
TF CUDA support       True
TF MKL support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.418.56
CUDA                  /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so.10.1.105
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
NCCL                  /usr/lib/x86_64-linux-gnu/libnccl.so.2.4.3
CUDA_VISIBLE_DEVICES  None
GPU 0                 Tesla T4
Free RAM              14.17/15.66 GB
CPU Count             4
horovod               0.16.0
cv2                   4.1.0
msgpack               0.6.1
python-prctl          True
--------------------  -------------------------------------------------------------------
You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment]
The operation system might execute an out-of-memory kill since the amount of CPU memory on your system is small.
After the crash, could you check `dmesg` to see whether the kernel killed any processes due to out-of-memory?

If out-of-memory is indeed an issue, could you upgrade your FasterRCNN examples to [this commit](5982977058218f6aae47e74dad6deb898bbb3062)? With this commit, you'll have the option to reduce memory usage by setting `DATA.NUM_WORKERS` to 1 or 0.
When setting `NUM_WORKERS` to 0, the training consumes only about 8G CPU memory on my machine (although the training might get slower).

**Comment by ppwwyyxx** [comment]
Closing as there is no response. The most likely cause is out-of-memory on the host, since the example running with the default parameters may use around 16GB host memory. 
Feel free to reopen if you still have issues.
