### ISSUE TITLE
When I use AccumGradOptimizer, an error occured.

### ISSUE THREAD

**Issue by BigFishMaster** [tensorpack/tensorpack#1177]
The error is:
```
Traceback (most recent call last):
  File "/mnt/yardcephfs/mmyard/g_wxg_td_prc/chriscxyan/competition/webvision/traintf/webvision-2.0-benchmarks-master/imagenet_resnet_toy.py", line 185, in <module>
    launch_train_with_config(config, trainer)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/train/interface.py", line 84, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/train/tower.py", line 214, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 194, in _setup_graph
    self.train_op, post_init_op = self._builder.build(grad_list, get_opt_fn)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 299, in build
    grad_and_vars, name='apply_grad_{}'.format(idx)))
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/tfutils/optimizer.py", line 209, in apply_gradients
    op = tf.cond(pred, update_grad, tf.no_op, name=name).op
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
   return func(*args, **kwargs)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2040, in cond
    return cond_v2_impl.cond_v2(pred, true_fn, false_fn, name)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/cond_v2_impl.py", line 70, in cond_v2
    true_name, true_fn, [], {})
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 945, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorpack/tfutils/optimizer.py", line 200, in update_grad
    update_op = self._opt.apply_gradients(slots_and_vars)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 610, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 115, in update_op
    update_op = optimizer._apply_dense(g, self._v)  # pylint: disable=protected-access
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/gradient_descent.py", line 60, in _apply_dense
    use_locking=self._use_locking).op
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/gen_training_ops.py", line 577, in apply_gradient_descent
    use_locking=use_locking, name=name)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 344, in create_op
    compute_device=compute_device)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/data1/qspace/chriscxyan/anaconda2/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1748, in __init__
    input_types))
TypeError: In op 'GradientDescent/update_conv0/W/ApplyGradientDescent', input types ([tf.float32, tf.float32, tf.float32]) are not compatible with expected types ([tf.float32_ref, tf.float32, tf.float32])
```
My environment is:
```
tensorpack 0.9.1
tensorflow-gpu 1.12.2
cudnn:7.1.4
cuda: 9.0
NVIDIA-SMI: 384.81
```
This code I use: is from ResNet example. I revise this optimizer function as:
```
    def optimizer(self):
        lr = tf.get_variable('learning_rate', initializer=0.1, trainable=False)
        tf.summary.scalar('learning_rate-summary', lr)
        opt = tf.train.GradientDescentOptimizer(lr)
        return optimizer.AccumGradOptimizer(opt, 4)
```

**Comment by BigFishMaster** [comment]
I review the code in [optimizer.py](https://github.com/tensorpack/tensorpack/commit/d8dd7ca93640c7299d2c2da064d57982fe56ff69#diff-11dc0f5801ffda9fc76942cf5ea4c217L222).
May it be caused by the following? The newest version of code has remove this line and use ```tf.identity```

```
op = tf.cond(pred, update_grad, tf.no_op, name=name).op	
```

**Comment by ppwwyyxx** [comment]
I do not know how to reproduce this issue. Please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by ppwwyyxx** [comment]
I now can successfully reproduce your issue. This is a tensorflow bug that has been workaround in latest tensorpack version. Upgrading tensorpack will solve your issue.

**Comment by ppwwyyxx** [comment]
The bug is now reported upstream at https://github.com/tensorflow/tensorflow/issues/28446.
