### ISSUE TITLE
Can we export Faster R-CNN weights to the npy/z format?

### ISSUE THREAD

**Issue by fuzzyBatman** [tensorpack/tensorpack#1184]
Is this possible? I tried using `scripts/dump-model-params.py`.

Command used:
```
python3 dump-model-params.py --meta graph-0511-131804.meta model-10000.data-00000-of-00001 model-10000.npz
```

Result
```
If your graph contains non-standard ops, you need to import the relevant library first.
Traceback (most recent call last):
  File "../../../../scripts/dump-model-params.py", line 26, in <module>
    tf.train.import_meta_graph(args.meta, clear_devices=True)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1457, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 399, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/home/fuzzybatman/.local/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 159, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'MaxBytesInUse'
```
Should I be importing specific libraries?

**Comment by ppwwyyxx** [comment]
run `from tensorflow.contrib.memory_stats import MaxBytesInUse` at the beginning of the script

**Comment by fuzzyBatman** [comment]
Amazing! Thank you so much.

**Comment by ppwwyyxx** [comment]
This is now added as a special case in the script (in https://github.com/tensorpack/tensorpack/commit/eafe564b69f53f9c91485324a9673aed0afea3db#diff-d2a0332f6e8a3bb8156ef2bdd3d52aac).

**Comment by fuzzyBatman** [comment]
Nice
