### ISSUE TITLE
AlexNet-DoreFa train fails

### ISSUE THREAD

**Issue by zhouchch3** [tensorpack/tensorpack#1210]
In DoreFa-Net, I train the alexnet using the command `./alexnet-dorefa.py --dorefa 1,8,32 --data /workspace/home/zhoucc/tensorflow/Dataset/ImageNet_ILSVRC2012/PATH/ --gpu 0,1
`
**Messages:**

[0524 10:36:03 @logger.py:125] WRN Log directory train_log/alexnet-dorefa-1,8,32 exists! Use 'd' to delete it.
[0524 10:36:03 @logger.py:128] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):d
[0524 10:36:08 @logger.py:90] Argv: ./alexnet-dorefa.py --dorefa 1,8,32 --data /workspace/home/zhoucc/tensorflow/Dataset/ImageNet_ILSVRC2012/PATH/ --gpu 0,1
[0524 10:36:08 @alexnet-dorefa.py:229] Batch per tower: 128
[0524 10:36:08 @fs.py:101] WRN Env var $TENSORPACK_DATASET not set, using /workspace/home/zhoucc/tensorpack_data for datasets.
[0524 10:36:10 @parallel.py:310] [PrefetchDataZMQ] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0524 10:36:10 @ilsvrc.py:128] [ILSVRC12] Assuming directory /workspace/home/zhoucc/tensorflow/Dataset/ImageNet_ILSVRC2012/PATH/val has 'original' structure.
[0524 10:36:10 @training.py:50] [DataParallel] Training a model of 2 towers.
[0524 10:36:10 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0524 10:36:10 @interface.py:43] Automatically applying StagingInput on the DataFlow.
[0524 10:36:10 @input_source.py:223] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
WARNING:tensorflow:From /usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
[0524 10:36:10 @training.py:110] Building graph for training tower 0 on device /gpu:0 ...
[0524 10:36:10 @registry.py:135] conv0 input: [None, 3, 224, 224]
[0524 10:36:10 @registry.py:143] conv0 output: [None, 96, 54, 54]
[0524 10:36:10 @registry.py:135] conv1 input: [None, 96, 54, 54]
[0524 10:36:10 @alexnet-dorefa.py:80] Quantizing weight conv1/W
[0524 10:36:10 @argtools.py:146] WRN CUDNN group convolution support is only available with https://github.com/tensorflow/tensorflow/pull/25818 . Will fall back to a loop-based slow implementation instead!
[0524 10:36:10 @registry.py:143] conv1 output: [None, 256, 54, 54]
[0524 10:36:10 @registry.py:135] pool1 input: [None, 256, 54, 54]
[0524 10:36:10 @registry.py:143] pool1 output: [None, 256, 27, 27]
[0524 10:36:10 @registry.py:135] conv2 input: [None, 256, 27, 27]
[0524 10:36:10 @alexnet-dorefa.py:80] Quantizing weight conv2/W
[0524 10:36:10 @registry.py:143] conv2 output: [None, 384, 27, 27]
[0524 10:36:10 @registry.py:135] pool2 input: [None, 384, 27, 27]
[0524 10:36:10 @registry.py:143] pool2 output: [None, 384, 14, 14]
[0524 10:36:10 @registry.py:135] conv3 input: [None, 384, 14, 14]
[0524 10:36:10 @alexnet-dorefa.py:80] Quantizing weight conv3/W
[0524 10:36:10 @registry.py:143] conv3 output: [None, 384, 14, 14]
[0524 10:36:10 @registry.py:135] conv4 input: [None, 384, 14, 14]
[0524 10:36:10 @alexnet-dorefa.py:80] Quantizing weight conv4/W
[0524 10:36:10 @registry.py:143] conv4 output: [None, 256, 14, 14]
[0524 10:36:10 @registry.py:135] pool4 input: [None, 256, 14, 14]
[0524 10:36:10 @registry.py:143] pool4 output: [None, 256, 6, 6]
[0524 10:36:10 @registry.py:135] fc0 input: [None, 256, 6, 6]
[0524 10:36:10 @alexnet-dorefa.py:80] Quantizing weight fc0/W
[0524 10:36:10 @registry.py:143] fc0 output: [None, 4096]
[0524 10:36:10 @registry.py:135] fc1 input: [None, 4096]
[0524 10:36:10 @alexnet-dorefa.py:80] Quantizing weight fc1/W
[0524 10:36:10 @registry.py:143] fc1 output: [None, 4096]
[0524 10:36:10 @registry.py:135] fct input: [None, 4096]
[0524 10:36:10 @registry.py:143] fct output: [None, 1000]
[0524 10:36:10 @regularize.py:97] regularize_cost() found 3 variables to regularize.
[0524 10:36:10 @regularize.py:21] The following tensors will be regularized: fc0/W:0, fc1/W:0, fct/W:0
WARNING:tensorflow:From /usr/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
[0524 10:36:11 @training.py:110] Building graph for training tower 1 on device /gpu:1 ...
[0524 10:36:11 @alexnet-dorefa.py:80] Quantizing weight tower1/conv1/W
[0524 10:36:11 @alexnet-dorefa.py:80] Quantizing weight tower1/conv2/W
[0524 10:36:11 @alexnet-dorefa.py:80] Quantizing weight tower1/conv3/W
[0524 10:36:11 @alexnet-dorefa.py:80] Quantizing weight tower1/conv4/W
[0524 10:36:11 @alexnet-dorefa.py:80] Quantizing weight tower1/fc0/W
[0524 10:36:11 @alexnet-dorefa.py:80] Quantizing weight tower1/fc1/W
[0524 10:36:11 @regularize.py:97] regularize_cost() found 3 variables to regularize.
[0524 10:36:12 @training.py:348] 'sync_variables_from_main_tower' includes 81 operations.
[0524 10:36:12 @model_utils.py:67] List of Trainable Variables:
name           shape               #elements
-------------  ----------------  -----------
conv0/W:0      [12, 12, 3, 96]         41472
conv0/b:0      [96]                       96
conv1/W:0      [5, 5, 48, 256]        307200
bn1/gamma:0    [256]                     256
bn1/beta:0     [256]                     256
conv2/W:0      [3, 3, 256, 384]       884736
bn2/gamma:0    [384]                     384
bn2/beta:0     [384]                     384
conv3/W:0      [3, 3, 192, 384]       663552
bn3/gamma:0    [384]                     384
bn3/beta:0     [384]                     384
conv4/W:0      [3, 3, 192, 256]       442368
bn4/gamma:0    [256]                     256
bn4/beta:0     [256]                     256
fc0/W:0        [9216, 4096]         37748736
fc0/b:0        [4096]                   4096
bnfc0/gamma:0  [4096]                   4096
bnfc0/beta:0   [4096]                   4096
fc1/W:0        [4096, 4096]         16777216
bnfc1/gamma:0  [4096]                   4096
bnfc1/beta:0   [4096]                   4096
fct/W:0        [4096, 1000]          4096000
fct/b:0        [1000]                   1000
Number of trainable variables: 23
Number of parameters (elements): 60985416
Storage space needed for all trainable variables: 232.64MB
[0524 10:36:12 @base.py:209] Setup callbacks graph ...
[0524 10:36:12 @argtools.py:146] WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra memory. Use 'forkserver' method (available after Py3.4) instead if you run into any issues. See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
[0524 10:36:12 @argtools.py:146] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.
[0524 10:36:13 @inference_runner.py:149] [InferenceRunner] Building tower 'InferenceTower' on device /gpu:0 ...
[0524 10:36:13 @alexnet-dorefa.py:80] Quantizing weight conv1/W
[0524 10:36:13 @alexnet-dorefa.py:80] Quantizing weight conv2/W
[0524 10:36:13 @alexnet-dorefa.py:80] Quantizing weight conv3/W
[0524 10:36:13 @alexnet-dorefa.py:80] Quantizing weight conv4/W
[0524 10:36:13 @alexnet-dorefa.py:80] Quantizing weight fc0/W
[0524 10:36:13 @alexnet-dorefa.py:80] Quantizing weight fc1/W
[0524 10:36:13 @summary.py:46] [MovingAverageSummary] 4 operations in collection 'MOVING_SUMMARY_OPS' will be run with session hooks.
[0524 10:36:13 @argtools.py:146] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.
[0524 10:36:13 @summary.py:93] Summarizing collection 'summaries' of size 21.
[0524 10:36:13 @graph.py:98] Applying collection UPDATE_OPS of 12 ops.
[0524 10:36:14 @base.py:230] Creating the session ...
2019-05-24 10:36:14.638189: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-05-24 10:36:16.943419: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW
2019-05-24 10:36:16.943621: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:161] retrieving CUDA diagnostic information for host: vlsi-02
2019-05-24 10:36:16.943644: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:168] hostname: vlsi-02
2019-05-24 10:36:16.944331: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:192] libcuda reported version is: 418.39.0
2019-05-24 10:36:16.944612: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:196] kernel reported version is: 410.48.0
2019-05-24 10:36:16.944687: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:306] kernel version 410.48.0 does not match DSO version 418.39.0 -- cannot find working devices in this configuration
2019-05-24 10:36:16.969750: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2019-05-24 10:36:16.974546: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x969e9d0 executing computations on platform Host. Devices:
2019-05-24 10:36:16.974634: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "./alexnet-dorefa.py", line 234, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerReplicated(nr_tower))
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/interface.py", line 101, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/base.py", line 344, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/base.py", line 315, in train
    self.initialize(session_creator, session_init)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/tower.py", line 152, in initialize
    super(TowerTrainer, self).initialize(session_creator, session_init)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/base.py", line 232, in initialize
    self.sess = session_creator.create_session()
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/tfutils/sesscreate.py", line 71, in create_session
    run(tf.global_variables_initializer())
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/tfutils/sesscreate.py", line 69, in run
    sess.run(op)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'NcclAllReduce' used by node AllReduceGrads/NcclAllReduce (defined at /workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/graph_builder/utils.py:160) with these attrs: [num_devices=2, reduction="sum", shared_name="c0", T=DT_FLOAT]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

         [[node AllReduceGrads/NcclAllReduce (defined at /workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/graph_builder/utils.py:160) ]]

Caused by op u'AllReduceGrads/NcclAllReduce', defined at:
  File "./alexnet-dorefa.py", line 234, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerReplicated(nr_tower))
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/interface.py", line 91, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/tower.py", line 224, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/train/trainers.py", line 190, in _setup_graph
    self.train_op, post_init_op = self._builder.build(grad_list, get_opt_fn)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 269, in build
    all_grads = allreduce_grads(all_grads, average=self._average)  # #gpu x #param
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/tfutils/scope_utils.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "/workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/graph_builder/utils.py", line 160, in allreduce_grads
    summed = nccl.all_sum(grads)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/nccl_ops.py", line 45, in all_sum
    return _apply_all_reduce('sum', tensors)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/nccl_ops.py", line 224, in _apply_all_reduce
    shared_name=shared_name))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_nccl_ops.py", line 84, in nccl_all_reduce
    name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'NcclAllReduce' used by node AllReduceGrads/NcclAllReduce (defined at /workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/graph_builder/utils.py:160) with these attrs: [num_devices=2, reduction="sum", shared_name="c0", T=DT_FLOAT]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  device='GPU'

         [[node AllReduceGrads/NcclAllReduce (defined at /workspace/home/zhoucc/.local/lib/python2.7/site-packages/tensorpack/graph_builder/utils.py:160) ]]

PrefetchDataZMQ successfully cleaned-up.
PrefetchDataZMQ successfully cleaned-up.

`
**Environment:**
`
[zhoucc@vlsi-02 DoReFa-Net]$ python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'
--------------------  ------------------------------------------------------------------------------
sys.platform          linux2
Python                2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Tensorpack            v0.9.4-65-g8879637-dirty
Numpy                 1.16.3
TensorFlow            1.13.1/v1.13.1-0-g6612da8951
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
Nvidia Driver         /usr/lib64/libnvidia-ml.so.418.39
CUDA                  /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
CUDNN                 /usr/lib64/libcudnn.so.7.5.1
NCCL
CUDA_VISIBLE_DEVICES  None
GPU                   Not found with NVML
Free RAM              31.00/125.00 GB
CPU Count             48
cv2                   4.1.0
msgpack               0.6.1
python-prctl          False
--------------------  ------------------------------------------------------------------------------
`
**Installed Cuda, not install CuDNN**
![image](https://user-images.githubusercontent.com/33385095/58299100-8eb03580-7e10-11e9-9816-7d7016a540e0.png)

**tensorflow-gpu has benn installed:**
![image](https://user-images.githubusercontent.com/33385095/58299149-c0290100-7e10-11e9-930d-747c7525da74.png)

What's the problem?

**Comment by ppwwyyxx** [comment]
>  E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE: forward compatibility was attempted on non supported HW

This is an issue in your GPU environment. You can find more information online, e.g., https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html

Closing as it's unrelated to tensorpack.

**Comment by zhouchch3** [comment]
@ppwwyyxx 

> This is an issue in your GPU environment. You can find more information online, e.g., https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html

`CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE = 804
This error indicates that the system was upgraded to run with forward compatibility but the visible hardware detected by CUDA does not support this configuration. Refer to the compatibility documentation for the supported hardware matrix or ensure that only supported hardware is visible during initialization via the CUDA_VISIBLE_DEVICES environment variable.`

My GPU is 1080ti and Cuda 10.0.
I can't find any solution to solve this problem.
Do you have any advice?

**Comment by ppwwyyxx** [comment]
You can try reboot.
Also, despite that you said you did not install cudnn, tensorflow finds cudnn at `/usr/lib64/libcudnn.so.7.5.1`.

You also need to make sure this cudnn is compatible with cuda 10.

**Comment by zhouchch3** [comment]
I will try. Thank you for your patient and professional reply. @ppwwyyxx
