### ISSUE TITLE
FasterRCNN pre-trained example usage

### ISSUE THREAD

**Issue by qvks** [tensorpack/tensorpack#1221]
Would greatly appreciate any advice on what I am doing wrong in the below:

When running ./predict.py --predict /coco/coco_val2014/COCO_val2014_000000000133.jpg /coco/coco_val2014/COCO_val2014_000000000136.jpg  --load COCO-MaskRCNN-R50C41x.npz --config MODE_MASK=True MODE_FPN=True

The result is an error:

[0601 23:47:04 @sessinit.py:87] WRN The following variables are in the graph, but not found in the dict: fastrcnn/fc6/W, fastrcnn/fc6/b, fastrcnn/fc7/W, fastrcnn/fc7/b, fastrcnn/outputs/box/W, fastrcnn/outputs/box/b, fastrcnn/outputs/class/W, fastrcnn/outputs/class/b, fpn/lateral_1x1_c2/W, fpn/lateral_1x1_c2/b, fpn/lateral_1x1_c3/W, fpn/lateral_1x1_c3/b, fpn/lateral_1x1_c4/W, fpn/lateral_1x1_c4/b, fpn/lateral_1x1_c5/W, fpn/lateral_1x1_c5/b, fpn/posthoc_3x3_p2/W, fpn/posthoc_3x3_p2/b, fpn/posthoc_3x3_p3/W, fpn/posthoc_3x3_p3/b, fpn/posthoc_3x3_p4/W, fpn/posthoc_3x3_p4/b, fpn/posthoc_3x3_p5/W, fpn/posthoc_3x3_p5/b, maskrcnn/fcn0/W, maskrcnn/fcn0/b, maskrcnn/fcn1/W, maskrcnn/fcn1/b, maskrcnn/fcn2/W, maskrcnn/fcn2/b, maskrcnn/fcn3/W, maskrcnn/fcn3/b
[0601 23:47:04 @sessinit.py:87] WRN The following variables are in the dict, but not found in the graph: fastrcnn/box/W, fastrcnn/box/b, fastrcnn/class/W, fastrcnn/class/b
[0601 23:47:04 @sessinit.py:218] Restoring 275 variables from dict ...
Traceback (most recent call last):
  File "./predict.py", line 142, in <module>
    predictor = OfflinePredictor(predcfg)
  File "/vol/bitbucket/rm2815/anaconda3/envs/tensorflow_gpuenv/lib/python3.7/site-packages/tensorpack/predict/base.py", line 167, in __init__
    config.session_init._run_init(sess)
  File "/vol/bitbucket/rm2815/anaconda3/envs/tensorflow_gpuenv/lib/python3.7/site-packages/tensorpack/tfutils/sessinit.py", line 219, in _run_init
    upd.update({name: value for name, value in six.iteritems(self._prms) if name in intersect})
  File "/vol/bitbucket/rm2815/anaconda3/envs/tensorflow_gpuenv/lib/python3.7/site-packages/tensorpack/tfutils/varmanip.py", line 120, in update
    feeds[var.initializer.inputs[1]] = SessionUpdate.relaxed_value_for_var(value, var)
  File "/vol/bitbucket/rm2815/anaconda3/envs/tensorflow_gpuenv/lib/python3.7/site-packages/tensorpack/tfutils/varmanip.py", line 73, in relaxed_value_for_var
    value.shape, name, varshape))
ValueError: Trying to load a tensor of shape (1024,) into the variable 'rpn/conv0/b' whose shape is (256,).

**Comment by ppwwyyxx** [comment]
You did not use the correct config.

**Comment by qvks** [comment]
Thanks! A suggestion - it might be helpful to include it in the table

**Comment by ppwwyyxx** [comment]
The tables says the config is the default.
