### ISSUE TITLE
Unknow Error,who can help me ?

### ISSUE THREAD

**Issue by Lovergx** [tensorpack/tensorpack#1223]
my environment is :
tensorflow 1.8
latest tensorpack
The error information : 
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    tf.app.run()
  File "/home/wubanggu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 42, in main
    run(model)
  File "/home/wubanggu/code/ChannelNet/tensor_net.py", line 81, in run
    launch_train_with_config(config, trainer)
  File "/home/wubanggu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    model.get_input_signature(), input,
  File "/home/wubanggu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/home/wubanggu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "/home/wubanggu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError

**Comment by ppwwyyxx** [comment]
The code you're running probably uses an ancient version of tensorpack. It is expecting methods that have been deprecated in tensorpack for >1 years. You can try tensorpack 0.9 or older versions which keeps the compatibility.

**Comment by Lovergx** [comment]
Thank you, I will try it.

**Comment by Lovergx** [comment]
@ppwwyyxx Thank you, I will try it
