### ISSUE TITLE
Does Tensorpack support Keras functional API??

### ISSUE THREAD

**Issue by dps42** [tensorpack/tensorpack#1237]
I'm trying to use Tensorpack for a model defined in Keras functional API.
I know that Tensorpack mainly supports Tensorflow, but I inherited a messy code defined in Keras functional API from somebody else. 

It seems that from the example codes, I could only find models defined in Sequential API. 

I tried to modify the keras MNIST example code (https://github.com/tensorpack/tensorpack/blob/master/examples/keras/mnist-keras.py) like the following but couldn't get it to work.

"""
@memoized  # this is necessary for sonnet/keras to work under tensorpack
def get_keras_model():
    with clear_tower0_name_scope():
    
        visible = Input(shape=(IMAGE_SIZE, IMAGE_SIZE, 1)) 
        conv1_1 = Conv2D(32, 3, activation='relu', input_shape=[IMAGE_SIZE, IMAGE_SIZE, 1], padding='same')(visible)
        pool1   = MaxPooling2D(pool_size=(2, 2))(conv1_1)
        conv2_1 = Conv2D(32, 3, activation='relu', padding='same')(pool1)
        conv2_2 = Conv2D(32, 3, activation='relu', padding='same')(conv2_1)
        pool2   = MaxPooling2D(pool_size=(2, 2))(conv2_2)
        conv3_1 = Conv2D(32, 3, padding='same', activation='relu')(pool2)
        flat    = Flatten()(conv3_1)
        hidden1 = Dense(512, activation='relu', kernel_regularizer=keras.regularizers.l2(1e-5))(flat)
        #drop    = Dropout(rate=0.5)(hidden1)
        output  = Dense(10, activation=None, kernel_regularizer=keras.regularizers.l2(1e-5))(hidden1)
        M  = Model(inputs=visible, outputs=output)
        
        """
        M = keras.models.Sequential()
        M.add(KL.Conv2D(32, 3, activation='relu', input_shape=[IMAGE_SIZE, IMAGE_SIZE, 1], padding='same'))
        M.add(KL.MaxPooling2D())
        M.add(KL.Conv2D(32, 3, activation='relu', padding='same'))
        M.add(KL.Conv2D(32, 3, activation='relu', padding='same'))
        M.add(KL.MaxPooling2D())
        M.add(KL.Conv2D(32, 3, padding='same', activation='relu'))
        M.add(KL.Flatten())
        M.add(KL.Dense(512, activation='relu', kernel_regularizer=keras.regularizers.l2(1e-5)))
        M.add(KL.Dropout(rate=0.5))
        M.add(KL.Dense(10, activation=None, kernel_regularizer=keras.regularizers.l2(1e-5)))
        """
        print(M.summary())
    return M
"""

So does Tensorpack support Keras functioanl API??
Or will modifying the other example code (https://github.com/tensorpack/tensorpack/blob/master/examples/keras/mnist-keras-v2.py) work with the Functional API ??

=======================================================
+ If you did something with tensorpack and it failed, PLEASE STOP HERE and use the "Unexpected Problems /
  Bugs" category.

+ Your question is probably answered in [tutorials](http://tensorpack.readthedocs.io/tutorial/index.html#user-tutorials). Read it first.

+ We answer "HOW to do X with Tensorpack" for a well-defined specific X.
  X must be something that you conceptually know how to do, but are unable to do due to lack of knowledge about Tensorpack.
  We don't answer vague questions like "How to do semantic segmentation in Tensorpack".

+ We also answer "HOW/WHY Tensorpack does X" for some X that Tensorpack or its examples are doing.

Some typical questions that we DO NOT answer:

+ "Could you improve/implement an example/paper?":

  We have no plans to do so. We don't consider feature
  requests for examples or implement a paper for you.
  If you don't know how to do something yourself, you may ask a usage question.

+ "The examples do not perform as expected after I change the models/dataset/parameters/etc.":

  Tensorpack maintainers make sure the examples perform well without modifications.
  But it's your job to pick the model and parameters that are suitable for your own situation.
  We cannot help with such questions unless they appear to be a bug in tensorpack.

+ "Why my own model doesn't perform well?", "I don't understand this paper you implement.",
  "How should I change the parameters for my own dataset?":

  We do not answer machine learning questions.

You can also use gitter (https://gitter.im/tensorpack/users) for more casual discussions.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/master/examples/keras/imagenet-resnet-keras.py uses the functional API.

**Comment by dps42** [comment]
thank you. I'll take a look. Sorry that I missed it.

**Comment by dps42** [comment]
Somehow, python imagenet-resnet-keras.py --fake doesn't seem to work on my machine..

"""
(dps42_dev) C:\Users\dps42\Desktop\dps42\tensorpack\examples\keras>python imagenet-resnet-keras.py --fake
Traceback (most recent call last):
  File "imagenet-resnet-keras.py", line 20, in <module>
    from imagenet_utils import fbresnet_augmentor, get_imagenet_dataflow
  File "C:\Users\dps42\Desktop\dps42\tensorpack\examples\keras\imagenet_utils.py", line 1
    ../ResNet/imagenet_utils.py
    ^
SyntaxError: invalid syntax
"""

Anyway, I tried to see if I could convert the simple MNIST Keras sequential model to a functional one. 
Here's the code: 
[keras_functional.zip](https://github.com/tensorpack/tensorpack/files/3307369/keras_functional.zip)

But I ran into a problem.

"""
(dps42_dev) C:\Users\dps42\Desktop\dps42\tensorpack\examples\keras>python mnist-keras-experiment-functional2.py
Using TensorFlow backend.
[0619 14:05:51 @logger.py:125] WRN Log directory train_log\mnist-keras-experiment-functional2 exists! Use 'd' to delete it.
[0619 14:05:51 @logger.py:128] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):d
[0619 14:06:01 @logger.py:90] Argv: mnist-keras-experiment-functional2.py
[0619 14:06:01 @fs.py:101] WRN Env var $TENSORPACK_DATASET not set, using C:\Users\dps42\tensorpack_data for datasets.
[0619 14:06:01 @concurrency.py:268] WRN Command 'nvidia-smi -L' failed, return code=1
[0619 14:06:01 @concurrency.py:269] WRN 'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.

[0619 14:06:01 @gpu.py:59] Loading local devices by TensorFlow ...
2019-06-19 14:06:01.474642: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-06-19 14:06:01.743960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:19:00.0
totalMemory: 11.00GiB freeMemory: 8.99GiB
2019-06-19 14:06:01.864999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 1 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:1a:00.0
totalMemory: 11.00GiB freeMemory: 8.99GiB
2019-06-19 14:06:01.997348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 2 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:67:00.0
totalMemory: 11.00GiB freeMemory: 8.99GiB
2019-06-19 14:06:02.231076: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 3 with properties:
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:68:00.0
totalMemory: 11.00GiB freeMemory: 8.99GiB
2019-06-19 14:06:02.238300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0, 1, 2, 3
2019-06-19 14:06:03.843315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-19 14:06:03.847226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 1 2 3
2019-06-19 14:06:03.849686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N N N N
2019-06-19 14:06:03.852069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 1:   N N N N
2019-06-19 14:06:03.855023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 2:   N N N N
2019-06-19 14:06:03.857381: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 3:   N N N N
2019-06-19 14:06:03.860107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:0 with 8668 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:19:00.0, compute capability: 7.5)
2019-06-19 14:06:04.979376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:1 with 8668 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:1a:00.0, compute capability: 7.5)
2019-06-19 14:06:06.093458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:2 with 8668 MB memory) -> physical GPU (device: 2, name: GeForce RTX 2080 Ti, pci bus id: 0000:67:00.0, compute capability: 7.5)
2019-06-19 14:06:07.446622: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/device:GPU:3 with 8667 MB memory) -> physical GPU (device: 3, name: GeForce RTX 2080 Ti, pci bus id: 0000:68:00.0, compute capability: 7.5)
[0619 14:06:10 @training.py:50] [DataParallel] Training a model of 4 towers.
[0619 14:06:10 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0619 14:06:10 @interface.py:43] Automatically applying StagingInput on the DataFlow.
[0619 14:06:10 @input_source.py:223] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0619 14:06:10 @training.py:110] Building graph for training tower 0 on device /gpu:0 ...
[0619 14:06:10 @registry.py:135] conv0 input: [None, 28, 28, 1]
[0619 14:06:10 @registry.py:143] conv0 output: [None, 28, 28, 32]
[0619 14:06:10 @registry.py:135] conv1_1 input: [None, 28, 14, 16]
[0619 14:06:10 @registry.py:143] conv1_1 output: [None, 28, 14, 32]
[0619 14:06:10 @registry.py:135] conv1_2 input: [None, 28, 14, 32]
[0619 14:06:10 @registry.py:143] conv1_2 output: [None, 28, 14, 32]
[0619 14:06:10 @registry.py:135] conv2_1 input: [None, 28, 7, 16]
[0619 14:06:10 @registry.py:143] conv2_1 output: [None, 28, 7, 32]
Traceback (most recent call last):
  File "mnist-keras-experiment-functional2.py", line 151, in <module>
    metrics='categorical_accuracy'
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\contrib\keras.py", line 282, in compile
    metrics=metrics)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\contrib\keras.py", line 219, in setup_keras_trainer
    lambda: optimizer)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\utils\argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\train\tower.py", line 224, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\train\trainers.py", line 189, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\graph_builder\training.py", line 226, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\graph_builder\training.py", line 122, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\graph_builder\training.py", line 117, in call_for_each_tower
    ret.append(func())
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\train\tower.py", line 280, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\train\tower.py", line 255, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\tfutils\tower.py", line 290, in __call__
    output = self._tower_fn(*args)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\contrib\keras.py", line 172, in get_cost
    outputs = model_caller(*input_tensors)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorpack\contrib\keras.py", line 92, in __call__
    model = self.cached_model = self.get_model(*input_tensors)
  File "mnist-keras-experiment-functional2.py", line 105, in get_keras_model
    M  = tf.keras.models.Model(visible, x, name='my_model')
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorflow\python\keras\engine\training.py", line 113, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorflow\python\keras\engine\network.py", line 79, in __init__
    self._init_graph_network(*args, **kwargs)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 364, in _method_wrapper
    method(self, *args, **kwargs)
  File "C:\Users\dps42\AppData\Local\Continuum\miniconda3\envs\dps42_dev\lib\site-packages\tensorflow\python\keras\engine\network.py", line 217, in _init_graph_network
    '(thus holding past layer metadata). Found: ' + str(x))
ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: Tensor("fc10/Softmax:0", shape=(?, 10), dtype=float32, device=/device:GPU:0)
"""

I think this is pretty much the same Keras problem as this:
https://github.com/tensorflow/tensorflow/issues/29371

But I think it hasn't been fixed yet. I guess it's more of a Keras problem for now..

**Comment by ppwwyyxx** [comment]
> Somehow, python imagenet-resnet-keras.py --fake doesn't seem to work on my machine..

You did not clone the code correctly. The code contains a soft link (imagenet_utils.py) to a file in a different directory. It seems that softlink is somehow broken when you clone the code.

**Comment by ppwwyyxx** [comment]
> I think this is pretty much the same Keras problem as this:
tensorflow/tensorflow#29371
But I think it hasn't been fixed yet. I guess it's more of a Keras problem for now..

It does look like this is just Keras limitation that makes it hard to use it with other libraries.
