### ISSUE TITLE
Attempted to use closed session when running distritbuted

### ISSUE THREAD

**Issue by aaron276h** [tensorpack/tensorpack#1278]
When training the MaskRCNN model in tensorpack, on a multi-machine setup (using DistributedTrainerReplicated), we consistently get `Attempted to use a closed session` error. 

1) We are running the MaskRCNN example. Here is the diff of the of what we changed to get it working with `DistributedTrainerReplicated`: 

```
git diff
diff --git a/examples/FasterRCNN/config.py b/examples/FasterRCNN/config.py
index ea417dea..43423865 100644
--- a/examples/FasterRCNN/config.py
+++ b/examples/FasterRCNN/config.py
@@ -78,9 +78,9 @@ config = AttrDict()
 _C = config     # short alias to avoid coding
 
 # mode flags ---------------------
-_C.TRAINER = 'replicated'  # options: 'horovod', 'replicated'
+_C.TRAINER = 'distributed_replicated'  # options: 'horovod', 'replicated'
 _C.MODE_MASK = True        # FasterRCNN or MaskRCNN
-_C.MODE_FPN = False
+_C.MODE_FPN = True
 
 # dataset -----------------------
 _C.DATA.BASEDIR = '/path/to/your/DATA/DIR'
diff --git a/examples/FasterRCNN/train.py b/examples/FasterRCNN/train.py
index 09f0d774..e01e280b 100755
--- a/examples/FasterRCNN/train.py
+++ b/examples/FasterRCNN/train.py
@@ -9,6 +9,7 @@ assert six.PY3, "This example requires Python 3!"
 from tensorpack import *
 from tensorpack.tfutils import collect_env_info
 from tensorpack.tfutils.common import get_tf_version_tuple
+import tensorflow as tf
 
 from dataset import register_coco
 from config import config as cfg
@@ -34,6 +35,8 @@ if __name__ == '__main__':
     parser.add_argument('--load', help='load a model to start training from. Can overwrite BACKBONE.WEIGHTS')
     parser.add_argument('--logdir', help='log directory', default='train_log/maskrcnn')
     parser.add_argument('--config', help="A list of KEY=VALUE to overwrite those defined in config.py", nargs='+')
+    parser.add_argument('--job', help="ps or worker")
+    parser.add_argument('--task', help="task index")
 
     if get_tf_version_tuple() < (1, 6):
         # https://github.com/tensorflow/tensorflow/issues/14657
@@ -122,5 +125,11 @@ if __name__ == '__main__':
         trainer = HorovodTrainer(average=False)
     else:
         # nccl mode appears faster than cpu mode
-        trainer = SyncMultiGPUTrainerReplicated(cfg.TRAIN.NUM_GPUS, average=False, mode='nccl')
+        ps_addresses = ["hostname0:port0", "hostname1:port0"]
+        worker_addresses = ["hostname0:port1", "hostname1:port1"]
+        cluster = tf.train.ClusterSpec({"ps": ps_addresses, "worker": worker_addresses})
+        server = tf.train.Server(cluster, job_name=args.job, task_index=args.task, config=cluster)
+        trainer = DistributedTrainerReplicated(cfg.TRAIN.NUM_GPUS, server)
+        # trainer = SyncMultiGPUTrainerReplicated(cfg.TRAIN.NUM_GPUS, average=False, mode='nccl')
+
     launch_train_with_config(traincfg, trainer)
```
Note: Hostnames & ports are hardcoded into the `train.py` and we ran this on two 8 GPU machines. 

2) An observation we made was that when running in AWS (p3dn instances) these errors occured infrequently. However when running on GCP, we observed these errors very frequently (e.g, every few minutes).
```96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:27.543611116Z 2019-07-24 04:55:27.543225: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.640360292Z Attempted to use a closed Session.
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.642700069Z [0724 04:55:29 @input_source.py:179] [EnqueueThread] Thread EnqueueThread QueueInput/input_queue Exited.
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644092074Z Traceback (most recent call last):
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644314685Z   File "/tensorpack/tensorpack/train/base.py", line 291, in main_loop
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644348810Z     self.run_step()  # implemented by subclass
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644351982Z   File "/tensorpack/tensorpack/train/base.py", line 182, in run_step
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644356945Z     self.hooked_sess.run([self.train_op, self.comm_op])
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644360170Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 676, in run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644363741Z     run_metadata=run_metadata)
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644366733Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644369901Z     run_metadata=run_metadata)
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644372950Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644376008Z     raise six.reraise(*original_exc_info)
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644378966Z   File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644381965Z     raise value
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644384685Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644387540Z     return self._sess.run(*args, **kwargs)
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644390281Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644393134Z     run_metadata=run_metadata)
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644395800Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644399759Z     return self._sess.run(*args, **kwargs)
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644402526Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644405361Z     run_metadata_ptr)
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644408027Z   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1075, in _run
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644410916Z     raise RuntimeError('Attempted to use a closed Session.')
96d0753b-b9d0-4202-a24b-e90386552d72 || 2019-07-24T04:55:29.644413657Z RuntimeError: Attempted to use a closed Session.
```

3) We encounter the `Attempted to use a closed Session` mentioned above.

4) Tensorpack commit: `d8e2929b4e9f2be3bf34604bc9232b2531517529`
Tensorflow version `1.13.1`, we have also tried `1.14.0` but this did not correct the issue.
Python: `3.6`
16 V100 GPUs on 2 machines, 8 GPUs per machine. 32 vCPUs, 488 GB memory per machine. Ubuntu 16.04.

**Comment by ppwwyyxx** [comment]
The readme of Mask R-CNN says you need to use HorovodTrainer.

`DistributedTrainerReplicated` does not exist in tensorpack documentation at all (https://tensorpack.readthedocs.io/modules/train.html). 
It exists in the codebase but that doesn't mean you can use it.
They don't work anymore because tensorflow has basically abandoned them due to the poor performance.

See also https://tensorpack.readthedocs.io/tutorial/trainer.html#distributed-trainers

**Comment by aaron276h** [comment]
@ppwwyyxx In our cluster configuration we are unable to use MPI which is why we are using `DistributedTrainerReplicated`. We have found that it works effectively outside of this error. Do you have any suggestions on what could be causing it?

**Comment by ppwwyyxx** [comment]
Alright. I can take a look at it if you can provide details about the problem. See https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE/unexpected-problems---bugs.md.

Also there is a [BytePSTrainer](https://tensorpack.readthedocs.io/modules/train.html#tensorpack.train.BytePSTrainer) -- does not require MPI and works similar to horovod, but the setup is a bit complicated.

**Comment by aaron276h** [comment]
@ppwwyyxx I updated the original comment with the required information. Really appreciate your help debugging this issue.

**Comment by ppwwyyxx** [comment]
The distributed training seems to be running fine on my side. Could you provide more logs, hopefully from each machine?

The partial error you provided does look like a side effect of a different error.

**Comment by aaron276h** [comment]
@ppwwyyxx We upgraded our machines on GCP (from 32 CPU -> 96) and haven't been able to re-produce the error either since. Will re-open if we encounter it again.
