### ISSUE TITLE
tensorpack.dataflow for tensorflow.estimator problem

### ISSUE THREAD

**Issue by KangGrandesty** [tensorpack/tensorpack#1300]
### dataflow for estimator

My code is based on tensorflow.estimator, so I want to take use of dataflow-tf.data pipeline as input for training. Thus, this simple example [dataflow4estimator](https://github.com/grandesty-ml/dataflow4estimator) demonstrate my use case.

### problem

the training program goes hang and then take all of the memory.

the entire logs here:

```
WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7fb0f9719598>) includes params argument, but params are not passed to Estimator.
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps 100 or save_checkpoints_secs None.
[0817 12:30:12 @format.py:99] WRN Traversing the database to find keys is slow. Your should specify the keys.
[0817 12:30:12 @timer.py:45] Start Loading LMDB keys ... ...
100%|###########################################################################################################################################################################|100/100[00:00<00:00,264959.19it/s]
[0817 12:30:13 @timer.py:50] Loading LMDB keys ... finished, time:1.2067 sec.
[0817 12:30:13 @format.py:92] Found 100 entries in ./data/0-of-3_lmdb
[0817 12:30:13 @format.py:99] WRN Traversing the database to find keys is slow. Your should specify the keys.
[0817 12:30:13 @timer.py:45] Start Loading LMDB keys ... ...
100%|###########################################################################################################################################################################|100/100[00:00<00:00,239264.35it/s]
[0817 12:30:13 @timer.py:50] Loading LMDB keys ... finished, time:0.0008 sec.
[0817 12:30:13 @format.py:92] Found 100 entries in ./data/2-of-3_lmdb
[0817 12:30:13 @format.py:99] WRN Traversing the database to find keys is slow. Your should specify the keys.
[0817 12:30:13 @timer.py:45] Start Loading LMDB keys ... ...
100%|###########################################################################################################################################################################|100/100[00:00<00:00,279247.94it/s]
[0817 12:30:13 @timer.py:50] Loading LMDB keys ... finished, time:0.0008 sec.
[0817 12:30:13 @format.py:92] Found 100 entries in ./data/1-of-3_lmdb
[0817 12:30:13 @argtools.py:146] WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra CPU memory. Use 'forkserver/spawn' method (available after Py3.4) instead if you run into any issues. See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
INFO:tensorflow:Calling model_fn.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2019-08-17 12:30:16.436836: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-17 12:30:16.460288: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-17 12:30:16.461426: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558efe395190 executing computations on platform CUDA. Devices:
2019-08-17 12:30:16.461466: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-08-17 12:30:16.461479: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-08-17 12:30:16.461490: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (2): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-08-17 12:30:16.484920: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2394240000 Hz
2019-08-17 12:30:16.487360: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x558efe404bd0 executing computations on platform Host. Devices:
2019-08-17 12:30:16.487407: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-17 12:30:16.487797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:02:00.0
totalMemory: 10.92GiB freeMemory: 1.15GiB
2019-08-17 12:30:16.487855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-08-17 12:30:16.491196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-17 12:30:16.491234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-08-17 12:30:16.491253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-08-17 12:30:16.491540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1117 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./model/model.ckpt-0
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./model/model.ckpt.
2019-08-17 12:30:18.422821: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
```

### environment

```
--------------------  -------------------------------------------------------------------
sys.platform          linux
Python                3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
Tensorpack            0.9.7.1-0-gc28a3fa
Numpy                 1.16.2
TensorFlow            1.13.1/b'v1.13.1-0-g6612da8951'
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.410.48
CUDA                  /usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
CUDNN                 /usr/local/cuda-10.0/lib64/libcudnn.so.7
NCCL
CUDA_VISIBLE_DEVICES  None
GPU 0,1,2             GeForce GTX 1080 Ti
Free RAM              13.58/62.81 GB
CPU Count             32
cv2                   4.1.0
msgpack               0.6.1
python-prctl          True
--------------------  -------------------------------------------------------------------
```

**Comment by ppwwyyxx** [comment]
https://github.com/grandesty-ml/dataflow4estimator/blob/master/gen_input.py#L43

 You cannot call `tuple()` on an iterator.

```
def f():
    while True:
        yield 1

x = tuple(f())
```

This code will hang and take all your memory as well.

**Comment by ppwwyyxx** [comment]
Btw, thanks for the clear issue description: makes it very easy to investigate.

**Comment by KangGrandesty** [comment]
You are right! And I change my code.

But a new error occurs, here is main information:

```
2019-08-17 16:23:19.056975: W tensorflow/core/framework/op_kernel.cc:1389] Invalid argument: TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.float32, tf.int64, tf.int64, tf.float32, tf.float32, tf.string, tf.string), but the yielded element was [array([[[130.,  50., 223.],
        [ 70.,  38., 111.],
        [177., 178., 170.],
        ...,
        [ 64.,  51., 156.],
        [ 42., 108.,  81.],
        [ 89., 225.,  89.]],

       [[145.,   0.,  97.],
        [237., 189., 239.],
        [ 48.,  73.,  80.],
        ...,
        [107., 150., 169.],
        [125., 182., 150.],
        [170., 215., 134.]],

       [[243.,  65.,  91.],
        [117.,  63.,  95.],
        [143., 187., 216.],
        ...,
        [ 92., 188., 125.],
        [ 70., 112.,  88.],
        [105.,  52.,  60.]],

       ...,

       [[116., 137.,  60.],
        [208., 203., 137.],
        [179., 160., 118.],
        ...,
        [ 80.,  51.,  73.],
        [137., 134., 117.],
        [200., 237., 196.]],

       [[103., 109., 109.],
        [115.,  97.,  85.],
        [140., 127.,  85.],
        ...,
        [ 70.,  76., 110.],
        [ 66.,  58.,  97.],
        [187., 158., 206.]],

       [[112.,  56., 167.],
        [172., 126., 173.],
        [220., 216., 155.],
        ...,
        [ 47., 110., 145.],
        [178., 183., 255.],
        [ 87.,   0., 126.]]], dtype=float32), array([[[188.,  55., 175., ...,  25.,  71.,  99.],
        [ 66., 241.,   4., ..., 164.,  39., 246.],
        [241., 117., 132., ...,  27.,   8., 115.],
        ...,
        [ 53., 215., 197., ...,  60.,  61., 204.],
        [ 58., 243.,  99., ..., 224., 166., 250.],
        [194.,  62., 238., ...,  58., 173.,  21.]],

       [[188.,  55., 175., ...,  25.,  71.,  99.],
        [ 66., 241.,   4., ..., 164.,  39., 246.],
        [241., 117., 132., ...,  27.,   8., 115.],
        ...,
        [ 53., 215., 197., ...,  60.,  61., 204.],
        [ 58., 243.,  99., ..., 224., 166., 250.],
        [194.,  62., 238., ...,  58., 173.,  21.]]], dtype=float32), 2, array([0, 0]), 0.0, array([0., 0.]), '0.0', ['0.0', '0.0']].
Traceback (most recent call last):

  File "/media/envs/anaconda3/envs/lk-tf36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 455, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/media/envs/anaconda3/envs/lk-tf36/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 399, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/media/envs/anaconda3/envs/lk-tf36/lib/python3.6/site-packages/tensorflow/python/data/util/nest.py", line 301, in assert_shallow_structure
    "Input has type: %s." % type(input_tree))

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: <class 'list'>.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/media/envs/anaconda3/envs/lk-tf36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "/media/envs/anaconda3/envs/lk-tf36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 460, in generator_py_func
    "element was %s." % (output_types, values))
```

I add a [`MapData` operation](https://github.com/grandesty-ml/dataflow4estimator/blob/8e1ba0846942ef73dd23d142181bb58a3873fc3e/gen_input.py#L41):

```python
lmdb_dataset = tp.MapData(lmdb_dataset, tuple)
```

before running `reset_state`, it works.

The returned element is tuple in `parse_fn`, and in `from_generator`, it is list. Maybe the type of element has been changed by some `DataFlow` class.

**Comment by ppwwyyxx** [comment]
The output from a dataflow is, by definition, either a list or a dict: https://tensorpack.readthedocs.io/tutorial/dataflow.html#what-is-dataflow.

Tuple is not supported, although it can work in certain dataflow (e.g., `MapData`).
