### ISSUE TITLE
Failed to export model of Faster-RCNN

### ISSUE THREAD

**Issue by kingaza** [tensorpack/tensorpack#1315]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:
Trained Faster-RCNN with my own dataset, but failed to export a pb file.
But I can do it for the original example in basics/export-model

(1) **If you're using examples, what's the command you run:**
Succeed in training by following the guideline:
`python ./train.py --config MODE_MASK=False MODE_FPN=True DATA.BASEDIR=./data/ BACKBONE.WEIGHTS=./pretrained_models/ImageNet-R50-AlignPadding.npz
`
I didn't change any other source code except for those related to training dataset

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
Failed in exporting a pb file
(a) copied export-model.py from basics to FasterRCNN
(b) modified function
```
def export_compact(model_path):
    """Export trained model to use it as a frozen and pruned inference graph in
       mobile applications. """
    pred_config = PredictConfig(
        session_init=get_model_loader(model_path),
        model = ResNetFPNModel(),
        input_names=['image', 'gt_boxes', 'gt_labels'],
        output_names=['output/boxes', 'output/scores', 'output/labels'],
        create_graph=False)
    exporter = ModelExporter(pred_config)
    exporter.export_compact('compact_graph.pb')
```
and it came out some error
```
(py36) hejiew@cnszn02x19:/data/hejiew/FasterRCNN$ python export.py --export=compact --load=./train_log/liver_cor/checkpoint
WARNING: Logging before flag parsing goes to stderr.
W0906 14:25:35.360084 140499398403840 __init__.py:308] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
[0906 14:25:35 @sesscreate.py:38] WRN User-provided custom session config may not work due to TF bugs. See https://github.com/tensorpack/tensorpack/issues/497 for workarounds.
Traceback (most recent call last):
  File "export.py", line 197, in <module>
    export_compact(args.load)
  File "export.py", line 128, in export_compact
    exporter.export_compact('compact_graph.pb')
  File "/home/hejiew/anaconda3/envs/py36/lib/python3.6/site-packages/tensorpack/tfutils/export.py", line 57, in export_compact
    self.config.tower_func(*input.get_input_tensors())
  File "/home/hejiew/anaconda3/envs/py36/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 291, in __call__
    output = self._tower_fn(*args)
  File "/data/hejiew/FasterRCNN/modeling/generalized_rcnn.py", line 71, in build_graph
    features = self.backbone(image)
  File "/data/hejiew/FasterRCNN/modeling/generalized_rcnn.py", line 229, in backbone
    c2345 = resnet_fpn_backbone(image, cfg.BACKBONE.RESNET_NUM_BLOCKS)
  File "/data/hejiew/FasterRCNN/modeling/backbone.py", line 196, in resnet_fpn_backbone
    mult = float(cfg.FPN.RESOLUTION_REQUIREMENT)
  File "/data/hejiew/FasterRCNN/config.py", line 22, in __getattr__
    raise AttributeError(name)
AttributeError: RESOLUTION_REQUIREMENT
```

(3) **If not using examples, help us reproduce your issue:**
n.a.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
shown in above

(2) **Other observations, if any:**
n.a.

### 3. What you expected, if not obvious.
n.a.

### 4. Your environment:
--------------------  ----------------------------------------------------------                                                                                                                                                             ---------
sys.platform          linux
Python                3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [G                                                                                                                                                             CC 7.3.0]
Tensorpack            v0.9.8-0-gb6318616
Numpy                 1.16.2
TensorFlow            1.14.0/v1.14.0-rc1-22-gaf24dc91b5
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/lib/nvidia-418/libnvidia-ml.so.418.87.00
CUDA                  libcudart.so.10.0
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
NCCL                  /usr/lib/x86_64-linux-gnu/libnccl.so.2.4.8
CUDA_VISIBLE_DEVICES  None
GPU 0,1               GeForce GTX 1080 Ti
Free RAM              61.72/62.85 GB
CPU Count             16
cv2                   4.1.0
msgpack               0.6.1
python-prctl          False
--------------------  ----------------------------------------------------------                                                                                                                                                             ---------

**Comment by kingaza** [comment]
hmm, I made a stupid mistake that I forgot to freeze config...
