### ISSUE TITLE
No OpKernel was registered to support Op 'NcclAllReduce' with these attrs

### ISSUE THREAD

**Issue by BrownZong** [tensorpack/tensorpack#1319]
### 1. What you did:

(1) **If you're using examples, what's the command you run:**
`python3 train.py `
 (data directory and backbone weights have been configured in config.py)
(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
```
-_C.DATA.BASEDIR = '/path/to/your/DATA/DIR'
+_C.DATA.BASEDIR = '/data/code/vision_ori/dataset'
 # All available dataset names are defined in `dataset/coco.py:register_coco`.
 # All TRAIN dataset will be concatenated for training.
-_C.DATA.TRAIN = ('coco_train2017',)   # i.e. trainval35k
+_C.DATA.TRAIN = ('coco_train2014', 'coco_valminusminival2014')   # i.e. trainval35k
 # Each VAL dataset will be evaluated separately (instead of concatenated)
-_C.DATA.VAL = ('coco_val2017',)  # AKA minival2014
+_C.DATA.VAL = ('coco_minival2014',)  # AKA minival2014
```
 

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```
2019-09-13 13:22:42.634749: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-09-13 13:22:42.650126: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-09-13 13:22:42.679266: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-09-13 13:22:42.721461: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-09-13 13:22:42.745770: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-09-13 13:22:42.767290: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-09-13 13:22:42.780580: I tensorflow/stream_executor/platform/default/dso_lo
ader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: ca
nnot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/l
ocal/nvidia/lib64:/data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cuda/lib6
4:/data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cud
a-10.0/cuda/lib64:/data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cuda/lib6
4:/data/cuda/cuda-10.0/cuda/lib64:/data/cuda/cuda-10.0/cuda/lib64
2019-09-13 13:22:42.780640: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1
663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-09-13 13:22:42.781157: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-13 13:22:42.781180: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
187]      0 1 2 3 
2019-09-13 13:22:42.781195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
200] 0:   N N N N 
2019-09-13 13:22:42.781212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
200] 1:   N N N N 
2019-09-13 13:22:42.781226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
200] 2:   N N N N 
2019-09-13 13:22:42.781240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
200] 3:   N N N N 
Traceback (most recent call last):                                     [86/1988]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.
py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.
py", line 1339, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.
py", line 1374, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was re
gistered to support Op 'NcclAllReduce' used by {{node AllReduceGrads/NcclAllRedu
ce}}with these attrs: [T=DT_FLOAT, num_devices=4, reduction="sum", shared_name="
c0"]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'

         [[AllReduceGrads/NcclAllReduce]]

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 127, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/interface.py", l
ine 101, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 3
44, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 3
15, in train
    self.initialize(session_creator, session_init)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/utils/argtools.py", li
ne 176, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/tower.py", line 
151, in initialize
    super(TowerTrainer, self).initialize(session_creator, session_init)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/utils/argtools.py", li
ne 176, in wrapper
    return func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 2
32, in initialize
    self.sess = session_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/sesscreate.py"
, line 85, in create_session
    run(tf.global_variables_initializer())
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/sesscreate.py"
, line 83, in run
    sess.run(op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.
py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.
py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.
py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.
py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was re
gistered to support Op 'NcclAllReduce' used by node AllReduceGrads/NcclAllReduce
 (defined at /usr/local/lib/python3.5/dist-packages/tensorpack/graph_builder/uti
ls.py:154) with these attrs: [T=DT_FLOAT, num_devices=4, reduction="sum", shared
_name="c0"]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'

         [[AllReduceGrads/NcclAllReduce]]

Errors may have originated from an input operation.
Input Source operations connected to node AllReduceGrads/NcclAllReduce:
 tower0/gradients/AddN_204 (defined at /usr/local/lib/python3.5/dist-packages/te
nsorpack/tfutils/optimizer.py:29)
MultiProcessMapDataZMQ successfully cleaned-up.
```

### 3. What you expected, if not obvious.
Start training.

### 4. Your environment:
```
sys.platform          linux
Python                3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
Tensorpack            v0.9.8-10-g0ffd533-dirty
Numpy                 1.17.2
TensorFlow            1.14.0/v1.14.0-rc1-22-gaf24dc91b5
TF Compiler Version   4.8.5
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/local/nvidia/lib64/libnvidia-ml.so.418.67
CUDA                  /data/cuda/cuda-10.0/cuda/lib64/libcudart.so.10.0.130
CUDNN
NCCL
CUDA_VISIBLE_DEVICES  None
GPU                   Not found with NVML
Free RAM              6.44/7.84 GB
CPU Count             4
cv2                   4.0.0
msgpack               0.5.6
python-prctl          False

```

**Comment by ppwwyyxx** [comment]
Feel free to reopen if this does not solve your issue.
