### ISSUE TITLE
Crash when using two InferenceRunner callbacks (with different datasets)

### ISSUE THREAD

**Issue by philippwerner** [tensorpack/tensorpack#1329]
Thank you for developing tensorpack. It is very useful!

I have modified the example examples/basics/mnist-convnet.py for running two InferenceRunner callbacks on different datasets.

```diff
diff --git a/examples/basics/mnist-convnet.py b/examples/basics/mnist-convnet.py
index 4e887e62..e8ab995f 100755
--- a/examples/basics/mnist-convnet.py
+++ b/examples/basics/mnist-convnet.py
@@ -109,6 +109,7 @@ if __name__ == '__main__':
     logger.auto_set_dir()
 
     dataset_train, dataset_test = get_data()
+    dataset_train_for_inference_runner = BatchData(dataset.Mnist('train'), 128, remainder=True)
 
     # How many iterations you want in each epoch.
     # This len(data) is the default value.
@@ -129,6 +130,10 @@ if __name__ == '__main__':
                 dataset_test,   # the DataFlow instance used for validation
                 ScalarStats(    # produce `val_accuracy` and `val_cross_entropy_loss`
                     ['cross_entropy_loss', 'accuracy'], prefix='val')),
+            InferenceRunner(    # run inference(for training data) after every epoch
+                dataset_train_for_inference_runner,
+                ScalarStats(    # produce `train_accuracy` and `train_cross_entropy_loss`
+                    ['cross_entropy_loss', 'accuracy'], prefix='train')),
             # MaxSaver needs to come after InferenceRunner to obtain its score
             MaxSaver('val_accuracy'),  # save the model with highest accuracy
         ],
```

This reproduces an issue that I also have with another training script. My main idea is to apply the same custom InferenceRunners on both training and validation data. I have successfully used multiple InferenceRunner callbacks in a prior version of tensorpack.

Tensorpack crashes when it is supposed to run the second InferenceRunner callback the first time.

Output:
```
$ python mnist-convnet.py
[0920 14:17:39 @logger.py:90] Argv: mnist-convnet.py
[0920 14:17:39 @fs.py:101] WRN Env var $TENSORPACK_DATASET not set, using C:\tensorpack_data for datasets.
[0920 14:17:40 @trainers.py:47] Building graph for a single training tower ...
[0920 14:17:40 @registry.py:90] 'conv0': [?, 28, 28, 1] --> [?, 28, 28, 32]
[0920 14:17:40 @registry.py:90] 'pool0': [?, 28, 28, 32] --> [?, 14, 14, 32]
[0920 14:17:40 @registry.py:90] 'conv1': [?, 14, 14, 32] --> [?, 14, 14, 32]
[0920 14:17:40 @registry.py:90] 'conv2': [?, 14, 14, 32] --> [?, 14, 14, 32]
[0920 14:17:40 @registry.py:90] 'pool1': [?, 14, 14, 32] --> [?, 7, 7, 32]
[0920 14:17:40 @registry.py:90] 'conv3': [?, 7, 7, 32] --> [?, 7, 7, 32]
[0920 14:17:40 @registry.py:90] 'fc0': [?, 7, 7, 32] --> [?, 512]
[0920 14:17:40 @registry.py:90] 'fc1': [?, 512] --> [?, 10]
[0920 14:17:40 @regularize.py:97] regularize_cost() found 2 variables to regularize.
[0920 14:17:40 @regularize.py:21] The following tensors will be regularized: fc0/W:0, fc1/W:0
[0920 14:17:40 @model_utils.py:67] List of Trainable Variables:
name     shape             #elements
-------  --------------  -----------
conv0/W  [3, 3, 1, 32]           288
conv0/b  [32]                     32
conv1/W  [3, 3, 32, 32]         9216
conv1/b  [32]                     32
conv2/W  [3, 3, 32, 32]         9216
conv2/b  [32]                     32
conv3/W  [3, 3, 32, 32]         9216
conv3/b  [32]                     32
fc0/W    [1568, 512]          802816
fc0/b    [512]                   512
fc1/W    [512, 10]              5120
fc1/b    [10]                     10
Number of trainable variables: 12
Number of parameters (elements): 836522
Storage space needed for all trainable variables: 3.19MB
[0920 14:17:40 @base.py:209] Setup callbacks graph ...
[0920 14:17:40 @inference_runner.py:149] [InferenceRunner] Building tower 'InferenceTower' on device /gpu:0 ...
[0920 14:17:40 @inference_runner.py:149] [InferenceRunner] Building tower 'InferenceTower' on device /gpu:0 ...
[0920 14:17:40 @summary.py:47] [MovingAverageSummary] 5 operations in collection 'MOVING_SUMMARY_OPS' will be run with session hooks.
[0920 14:17:40 @summary.py:94] Summarizing collection 'summaries' of size 18.
[0920 14:17:40 @base.py:230] Creating the session ...
2019-09-20 14:17:40.822977: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-09-20 14:17:41.088505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
pciBusID: 0000:17:00.0
totalMemory: 11.00GiB freeMemory: 9.11GiB
2019-09-20 14:17:41.203769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 1 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.6325
pciBusID: 0000:65:00.0
totalMemory: 11.00GiB freeMemory: 9.11GiB
2019-09-20 14:17:41.204408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0, 1
2019-09-20 14:17:43.174425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-20 14:17:43.174848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 1
2019-09-20 14:17:43.175127: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N N
2019-09-20 14:17:43.175398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 1:   N N
2019-09-20 14:17:43.175972: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11151 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:17:00.0, compute capability: 6.1)
2019-09-20 14:17:43.178887: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 11151 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
[0920 14:17:43 @base.py:236] Initializing the session ...
[0920 14:17:43 @base.py:243] Graph Finalized.
[0920 14:17:43 @inference_runner.py:96] [InferenceRunner] Will eval 40 iterations
[0920 14:17:43 @inference_runner.py:96] [InferenceRunner] Will eval 469 iterations
[0920 14:17:43 @base.py:275] Start Epoch 1 ...
  0%|          |0/468[00:00<?,?it/s][0920 14:17:43 @common.py:844] Contents of DataFlow:
datapoint 0/1 with 2 components consists of
  0: ndarray:float32 of shape (128, 28, 28) in range [0.0, 1.0]
  1: ndarray:uint8 of shape (128,) in range [0, 9]
100%|##########|468/468[00:03<00:00,121.26it/s]
[0920 14:17:47 @base.py:285] Epoch 1 (global_step 468) finished, time:3.86 seconds.
[0920 14:17:47 @saver.py:82] Model saved to train_log\mnist-convnet\model-468.
100%|##########|40/40[00:00<00:00,127.83it/s]
  0%|          |0/469[00:00<?,?it/s]
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[{{node input_1}} = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[{{node InferenceTower/cross_entropy_loss/_191}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_93_InferenceTower/cross_entropy_loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist-convnet.py", line 146, in <module>
    launch_train_with_config(config, SimpleTrainer())
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\interface.py", line 101, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\base.py", line 344, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\base.py", line 316, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\utils\argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\base.py", line 288, in main_loop
    self._callbacks.trigger_epoch()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\base.py", line 156, in trigger_epoch
    self._trigger_epoch()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\group.py", line 99, in _trigger_epoch
    cb.trigger_epoch()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\base.py", line 156, in trigger_epoch
    self._trigger_epoch()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\base.py", line 162, in _trigger_epoch
    self.trigger()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\base.py", line 165, in trigger
    self._trigger()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\inference_runner.py", line 178, in _trigger
    self._hooked_sess.run(fetches=[])
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[node input_1 (defined at C:\Program Files\Python36\lib\site-packages\tensorpack\input_source\input_source_base.py:45)  = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[{{node InferenceTower/cross_entropy_loss/_191}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_93_InferenceTower/cross_entropy_loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'input_1', defined at:
  File "mnist-convnet.py", line 146, in <module>
    launch_train_with_config(config, SimpleTrainer())
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\interface.py", line 101, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\base.py", line 344, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\base.py", line 314, in train
    self.setup_callbacks(callbacks, monitors)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\utils\argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\train\base.py", line 211, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\base.py", line 59, in setup_graph
    self._setup_graph()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\group.py", line 72, in _setup_graph
    cb.setup_graph(self.trainer)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\base.py", line 59, in setup_graph
    self._setup_graph()
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\callbacks\inference_runner.py", line 144, in _setup_graph
    input_callbacks = self._input_source.setup(self._tower_func.input_signature)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\utils\argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\input_source\input_source_base.py", line 128, in setup
    self._setup(input_signature)
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\input_source\input_source.py", line 113, in _setup
    self._all_placehdrs = [build_or_reuse_placeholder(v) for v in inputs]
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\input_source\input_source.py", line 113, in <listcomp>
    self._all_placehdrs = [build_or_reuse_placeholder(v) for v in inputs]
  File "C:\Program Files\Python36\lib\site-packages\tensorpack\input_source\input_source_base.py", line 45, in build_or_reuse_placeholder
    tensor_spec.dtype, shape=tensor_spec.shape, name=tensor_spec.name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1747, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6252, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,28,28]
         [[node input_1 (defined at C:\Program Files\Python36\lib\site-packages\tensorpack\input_source\input_source_base.py:45)  = Placeholder[dtype=DT_FLOAT, shape=[?,28,28], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[{{node InferenceTower/cross_entropy_loss/_191}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_93_InferenceTower/cross_entropy_loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

My environment:
```
$ python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'
--------------------  ---------------------------------------------------------------------------------
sys.platform          win32
Python                3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
Tensorpack            v0.9.8-16-geb25cd7f-dirty
Numpy                 1.16.3
TensorFlow            1.12.0/b'v1.12.0-rc2-3-ga6d8ffae09'
TF Compiler Version   MSVC 190024215
TF CUDA support       True
TF MKL support        False
Nvidia Driver
CUDA
CUDNN
NCCL
CUDA_VISIBLE_DEVICES  None
GPU                   Not found with NVML
Free RAM              22.54/31.68 GB
CPU Count             12
cv2                   4.0.0
msgpack               0.6.0
python-prctl          False
--------------------  ---------------------------------------------------------------------------------
```

**Comment by ppwwyyxx** [comment]
Please check https://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.InferenceRunner:

> tower_name (str) – the name scope of the tower to build. Need to set a different one if multiple InferenceRunner are used.

**Comment by ppwwyyxx** [comment]
Maybe this can be made automatic, though, i.e., detect that the name scope has been used and create the graph in a new name scope. But for now you need to specify the name for new `InferenceRunner`.

**Comment by ppwwyyxx** [comment]
This specific issue can be fixed in the above commit, but in general it's still best to use different names because other types of name conflicts may also exist.

**Comment by philippwerner** [comment]
Using different tower_names is fine, I just missed this part of the docs. Thank you!
