### ISSUE TITLE
Please some one help me regarding this problem zmq.error.ZMQError: Protocol not supported

### ISSUE THREAD

**Issue by niazahamd89** [tensorpack/tensorpack#1341]
loading annotations into memory...
Done (t=7.73s)
creating index...
index created!
loading annotations into memory...
Done (t=7.87s)
creating index...
index created!
ZMQError in socket.bind(). Perhaps you're                 using pipes on a non-local file system. See documentation of PrefetchDataZMQ for more information.
Traceback (most recent call last):
  File "network.py", line 163, in <module>
    trainer = Trainer(Network(), cfg)
  File "C:\Users\niaza\tf-cpn-master\models\COCO.res50.256x192.CPN\..\..\lib\tfflat\base.py", line 192, in __init__
    self._data_iter = self.net.make_data()
  File "network.py", line 90, in make_data
    dp.reset_state()
  File "C:\Users\niaza\tf-cpn-master\models\COCO.res50.256x192.CPN\..\..\lib\tfflat\data_provider.py", line 371, in reset_state
    self.ds.reset_state()
  File "C:\Users\niaza\tf-cpn-master\models\COCO.res50.256x192.CPN\..\..\lib\tfflat\data_provider.py", line 266, in reset_state
    self._reset_once()  # build processes
  File "C:\Users\niaza\tf-cpn-master\models\COCO.res50.256x192.CPN\..\..\lib\tfflat\data_provider.py", line 236, in _reset_once
    self.socket.bind(pipename)
  File "zmq\backend\cython\socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Protocol not supported
MultiProcessMapDataZMQ successfully cleaned-up.
MultiProcessMapDataZMQ successfully cleaned-up.

**Comment by ppwwyyxx** [comment]
The ZMQ protocol we use does not support windows. Please replace the ZMQ dataflow in your code by the non-zmq version.
