### ISSUE TITLE
Running keras example yields :TypeError: Input 'predictions' of 'InTopKV2' Op has type int32 that does not match expected type of float32.

### ISSUE THREAD

**Issue by piperod** [tensorpack/tensorpack#1359]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

Run the script for keras-mnist.py
(1) **If you're using examples, what's the command you run:**
python keras-mnist.py
(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

(3) **If not using examples, help us reproduce your issue:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It's always better to copy-paste what you observed instead of describing them.

ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: <tf.Tensor 'tower0/StagingInput/StagingArea_get:1' shape=(None,) dtype=int32>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testingmnist.py", line 125, in <module>
    launch_train_with_config(cfg, SyncMultiGPUTrainerParameterServer(2))
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/train/interface.py", line 91, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/train/tower.py", line 224, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/train/trainers.py", line 102, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 159, in call_for_each_tower
    return DataParallelBuilder.build_on_towers(self.towers, tower_fn, devices)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 122, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 117, in call_for_each_tower
    ret.append(func())
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/train/tower.py", line 281, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/train/tower.py", line 255, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorpack/tfutils/tower.py", line 291, in __call__
    output = self._tower_fn(*args)
  File "testingmnist.py", line 78, in build_graph
    acc = tf.cast(tf.nn.in_top_k(logits, label, 1), tf.float32)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 4897, in in_top_k_v2
    return in_top_k(predictions, targets, k, name)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 4892, in in_top_k
    return gen_nn_ops.in_top_kv2(predictions, targets, k, name=name)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 4633, in in_top_kv2
    "InTopKV2", predictions=predictions, targets=targets, k=k, name=name)
  File "/home/irodri15/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 491, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'predictions' of 'InTopKV2' Op has type int32 that does not match expected type of float32.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

**Comment by ppwwyyxx** [comment]
The builtin example https://github.com/tensorpack/tensorpack/blob/master/examples/keras/mnist-keras.py runs well in my environment of TF 1.13.
If you've made changes, please undo them. If the issue persists, please include environment information as requested in the issue template.

**Comment by piperod** [comment]
I am using TF 2.0 it seems then that is not compatible with the new version?

**Comment by ppwwyyxx** [comment]
As [README](https://github.com/tensorpack/tensorpack/#install) says we do not support TF 2.0.

**Comment by piperod** [comment]
I see. Are there plans for tensorflow 2.0.? Is it possible to create a data generator using dataflow so keras can use it for training? Any light very welcome.

**Comment by ppwwyyxx** [comment]
TF 2.0 is discussed in #1167

Dataflow question is answerd in https://tensorpack.readthedocs.io/tutorial/dataflow.html

**Comment by piperod** [comment]
Unfortunally  https://tensorpack.readthedocs.io/tutorial/dataflow.html this won't work as a data generator for keras. It yields shape is not defined.
AttributeError: 'BatchData' object has no attribute 'shape'

**Comment by ppwwyyxx** [comment]
I don't know how you're using keras, but dataflow is an iterator and keras supports iterator.

**Comment by piperod** [comment]
That is why I asked  if there is a concrete example for keras using dataflow as datagenerator. I am using it as: 
''' 
model.fit_generator(train_generator, etc etc )
'''

**Comment by ppwwyyxx** [comment]
How to use dataflow as a pure python generator is documented at https://tensorpack.readthedocs.io/tutorial/dataflow.html#run-the-dataflow. If anything else is unclear it should be Keras.
