### ISSUE TITLE
an error of running tensorpack/examples/FasterRCNN/predict.py 

### ISSUE THREAD

**Issue by jhx9327** [tensorpack/tensorpack#1370]
python predict.py --predict input1.jpg input3.jpg --load ./train_log/maskrcnn/model-500.data-00000-of-00001 --config BACKBONE.WEIGHTS=./ImageNet-R50-AlignPadding.npz DATA.BASEDIR=./coco2017

Traceback (most recent call last):
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([1,3,805,1093]) filter shape([7,7,3,64])
         [[{{node conv0/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Pad, conv0/W/read)]]
         [[{{node generate_fpn_proposals/Lvl3/generate_rpn_proposals/clip_boxes/Minimum/_697}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1464_generate_fpn_proposals/Lvl3/generate_rpn_proposals/clip_boxes/Minimum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict.py", line 170, in <module>
    do_predict(predictor, image_file)
  File "predict.py", line 98, in do_predict
    results = predict_image(img, pred_func)
  File "/home/hxjiang/code/tensorpack-master/FasterRCNN_jhx/eval.py", line 126, in predict_image
    boxes, probs, labels, *masks = model_func(resized_img)
  File "/home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/predict/base.py", line 39, in __call__
    output = self._do_call(dp)
  File "/home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/predict/base.py", line 130, in _do_call
    return self._callable(*dp)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1204, in _generic_run
    return self.run(fetches, feed_dict=feed_dict, **kwargs)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([1,3,805,1093]) filter shape([7,7,3,64])
         [[node conv0/Conv2D (defined at /home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/models/conv2d.py:76)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Pad, conv0/W/read)]]
         [[{{node generate_fpn_proposals/Lvl3/generate_rpn_proposals/clip_boxes/Minimum/_697}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1464_generate_fpn_proposals/Lvl3/generate_rpn_proposals/clip_boxes/Minimum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'conv0/Conv2D', defined at:
  File "predict.py", line 168, in <module>
    predictor = OfflinePredictor(predcfg)
  File "/home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/predict/base.py", line 159, in __init__
    config.tower_func(*input.get_input_tensors())
  File "/home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 291, in __call__
    output = self._tower_fn(*args)
  File "/home/hxjiang/code/tensorpack-master/FasterRCNN_jhx/modeling/generalized_rcnn.py", line 67, in build_graph
    features = self.backbone(image)
  File "/home/hxjiang/code/tensorpack-master/FasterRCNN_jhx/modeling/generalized_rcnn.py", line 227, in backbone
    c2345 = resnet_fpn_backbone(image, cfg.BACKBONE.RESNET_NUM_BLOCKS)
  File "/home/hxjiang/code/tensorpack-master/FasterRCNN_jhx/modeling/backbone.py", line 208, in resnet_fpn_backbone
    l = Conv2D('conv0', l, 64, 7, strides=2, padding='VALID')
  File "/home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/models/registry.py", line 173, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/models/tflayer.py", line 66, in decorated_func
    return func(inputs, **ret)
  File "/home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/models/conv2d.py", line 76, in Conv2D
    ret = layer.apply(inputs, scope=tf.get_variable_scope())
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 817, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 957, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): cuDNN launch failure : input shape([1,3,805,1093]) filter shape([7,7,3,64])
         [[node conv0/Conv2D (defined at /home/hxjiang/.local/lib/python3.6/site-packages/tensorpack/models/conv2d.py:76)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Pad, conv0/W/read)]]
         [[{{node generate_fpn_proposals/Lvl3/generate_rpn_proposals/clip_boxes/Minimum/_697}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1464_generate_fpn_proposals/Lvl3/generate_rpn_proposals/clip_boxes/Minimum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Any help is appreciated.

**Comment by ppwwyyxx** [comment]
Most likely you're using a wrong build of cudnn

**Comment by jhx9327** [comment]
> Most likely you're using a wrong build of cudnn

Thanks for your reply. But if I ran train.py successfully, is there still the problem with cudnn?

**Comment by ppwwyyxx** [comment]
Then there might be a bug in either the cudnn or the tensorflow you're using.
You can try to upgrade them or try on a different machine.
Closing as I don't think it's related to tensorpack.
