### ISSUE TITLE
How to deal with the erro 'AssertionError: ZMQ IPC doesn't support windows!'? 

### ISSUE THREAD

**Issue by ming-nju** [tensorpack/tensorpack#1387]
+ running the code tensorpack\examples\GAN\DCGAN.py on Windows, an error occured 'AssertionError: ZMQ IPC doesn't support windows!'?
+ Traceback (most recent call last):
  File "./DCGAN-CelebA.py", line 165, in <module>
    input=QueueInput(get_data()),
  File "./DCGAN-CelebA.py", line 118, in get_data
    ds = MultiProcessRunnerZMQ(ds, 5)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\dataflow\parallel.py", line 348, in __init__
    super(MultiProcessRunnerZMQ, self).__init__()
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\dataflow\parallel.py", line 111, in __init__
    assert os.name != 'nt', "ZMQ IPC doesn't support windows!"
AssertionError: ZMQ IPC doesn't support windows!
How to solve it? Am i need to  to use TCP on a Loopback Interface, and how to use the TCP
Thank you very `much!`

**Comment by ppwwyyxx** [comment]
See https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.MultiProcessRunnerZMQ.
