### ISSUE TITLE
How to deal with ERR [EnqueueThread] Exception in thread EnqueueThread QueueInput/input_queue?

### ISSUE THREAD

**Issue by ming-nju** [tensorpack/tensorpack#1388]
When run the codes tensorpack\examples\GAN\DCGAN.py, an error occured, 'ERR **[EnqueueThread]** Exception in thread EnqueueThread QueueInput/input_queue:'

The Command:
`python ./DCGAN-CelebA.py --data E:/projects/下载程序/tensorpack/examples/GAN/mytry1/img_align_celeba/ --crop-size 140`

And the error is:
`Traceback (most recent call last):
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\input_source\input_source.py", line 161, in run
    dp = next(self._itr)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\dataflow\common.py", line 386, in __iter__
    for dp in self.ds:
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\dataflow\common.py", line 118, in __iter__
    for data in self.ds:
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\dataflow\common.py", line 312, in __iter__
    for dp in self.ds:
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\dataflow\image.py", line 75, in __iter__
    assert im is not None, 
AssertionError: E:/projects/下载程序/tensorpack/examples/GAN/mytry1/img_align_celeba\060315.jpg`
`[0121 10:03:55 @input_source.py:179] [EnqueueThread] Thread EnqueueThread QueueInput/input_queue Exited.
[0121 10:03:56 @base.py:275] Start Epoch 1 ...
  0%|                                                                                                     |0/300[00:00<?,?it/s]2020-01-21 10:03:56.580060: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-01-21 10:03:56.823400: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-01-21 10:03:57.849404: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.
[0121 10:03:58 @base.py:291] Training was stopped by exception FIFOQueue '_0_QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[node QueueInput/input_deque (defined at C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]'

'Original stack trace for 'QueueInput/input_deque':
  File "./DCGAN-CelebA.py", line 166, in <module>
    model=M).train_with_defaults(
  File "E:\projects\下载程序\tensorpack\examples\GAN\GAN.py", line 95, in __init__
    self._build_gan_trainer(input, model)
  File "E:\projects\下载程序\tensorpack\examples\GAN\GAN.py", line 110, in _build_gan_trainer
    self.tower_func(*input.get_input_tensors())
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\input_source\input_source_base.py", line 83, in get_input_tensors
    return self._get_input_tensors()
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorpack\input_source\input_source.py", line 272, in _get_input_tensors
    ret = self.queue.dequeue(name='input_deque')
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\ops\data_flow_ops.py", line 446, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_data_flow_ops.py", line 4140, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\a\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
.
  0%|                                                                                                     |0/300[00:01<?,?it/s]
`
How to solve this problems, thank very much!

**Comment by ppwwyyxx** [comment]
As the error says, the image `E:/projects/下载程序/tensorpack/examples/GAN/mytry1/img_align_celeba\060315.jpg` cannot be read. Please make sure it's a valid image.

**Comment by ming-nju** [comment]
> As the error says, the image `E:/projects/下载程序/tensorpack/examples/GAN/mytry1/img_align_celeba\060315.jpg` cannot be read. Please make sure it's a valid image.

The image is exist in this filepath. I tried run the code three times, each time showing a different image. These image are exist in this filepath. 
`AssertionError: E:/projects/下载程序/tensorpack/examples/GAN/mytry1/img_align_celeba\034658.jpg`
