### ISSUE TITLE
ValueError: Variable conv0/W/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?Please read & provide the following information

### ISSUE THREAD

**Issue by aywkwok** [tensorpack/tensorpack#1400]
I too try to replicate the experiment in:

https://github.com/czhu95/ternarynet/blob/master/README.md

Using a very old release of TF/tensorpack:
+Ubuntu 16.04
+Python 2.7
+TF release 1.1.0
+ Old Tensorpack as included in the Ternarynet repo

And got this error:

ValueError: Variable conv0/W/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

Being a newbie in TF, I have no idea how to fix it. Any idea?

Full Trace:

[0222 14:48:36 @regularize.py:17] Apply regularizer for linear/Wp:0
[0222 14:48:36 @regularize.py:17] Apply regularizer for linear/Wn:0
Traceback (most recent call last):
  File "./tw-cifar10-resnet.py", line 227, in <module>
    SyncMultiGPUTrainer(config).train()
  File "/home/akwok/ML/ternarynet-master/tensorpack/train/multigpu.py", line 80, in train
    self.config.optimizer.apply_gradients(grads, get_global_step_var()),
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/training/momentum.py", line 63, in _create_slots
    self._zeros_slot(v, "momentum", self._name)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/home/akwok/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 671, in _get_single_variable
    "VarScope?" % name)

ValueError: Variable conv0/W/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by ppwwyyxx** [comment]
We do not provide support for ancient versions of the software.
There is a working TTQ implementation in https://github.com/tensorpack/tensorpack/tree/master/examples/DoReFa-Net with similar results using latest software.

**Comment by songqi-github** [comment]
Hi, have you solved this problem? I met the same problem, could you please tell me the reason and how to solve it? Thank you very much!
