### ISSUE TITLE
Train with Negative Dataset for Cascade R-CNN

### ISSUE THREAD

**Issue by mdv3101** [tensorpack/tensorpack#1411]
I am using tensorpack/examples/FasterRCNN for cascade RCNN training. I am training it for single class (say object). My dataset has few unlabelled images (negative dataset). I want to include them during training. Since they do not have any 'object' present in them, the bounding box has value [0,0,0,0]. Is setting label to 'BG' and label_id to 0 is enough?
Can you please tell the procedure?

**Comment by ppwwyyxx** [comment]
If there are no objects you should leave "boxes/labels" empty rather than an array full of zeros.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/blob/d89b6f074d3a37a88aa35df49da58f934bd694f8/examples/FasterRCNN/dataset/dataset.py#L20-L26

**Comment by mdv3101** [comment]
Setting "boxes" to empty generates the following error (during loading of annotations)
`File "/home/madhav3101/cascade/tensorpack/examples/FasterRCNN/dataset/coco.py", line 149, in _add_detection_gt
    x1, y1, w, h = list(map(float, obj['bbox']))
ValueError: not enough values to unpack (expected 4, got 0)`

**Comment by ppwwyyxx** [comment]
The above comment is for custom format.
If you're using COCO format, what you do is to simply not create an annotation for the image in the json file.

**Comment by mdv3101** [comment]
If i am not getting wrong, For the coco format all i have to do is:
* In the 'images' of json, create an entry for every image in dataset (both positive and negative images). 
* In the 'annoatations' of json, create entry for every positive image (i.e. image which contains the bounding box)

If i follow these steps, will it going to include negative images (i.e. images which doesn't contain the object, only background) during the training. Or is it just going to ignore them and keeps on training using the positive images only?

**Comment by ppwwyyxx** [comment]
The steps are correct and you'll also need to remove https://github.com/tensorpack/tensorpack/blob/d89b6f074d3a37a88aa35df49da58f934bd694f8/examples/FasterRCNN/data.py#L346-L348 otherwise those images will be filtered

**Comment by mdv3101** [comment]
As you suggested, I have modified roidbs to include all the images. But now i am getting the following error.

  0%|          |0/1000[00:00<?,?it/s]2020-03-16 13:10:52.352836: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
  0%|          |1/1000[00:20<5:45:08, 0.05it/s]2020-03-16 13:10:55.243286: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed

MultiProcessMapDataZMQ successfully cleaned-up.
Traceback (most recent call last):
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 1 is empty in shape [512,0]
	 [[{{node tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/ArgMax}}]]
	 [[{{node tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/mul}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 132, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/interface.py", line 101, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/base.py", line 342, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/base.py", line 314, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/utils/argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/base.py", line 279, in main_loop
    self.run_step()  # implemented by subclass
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/base.py", line 179, in run_step
    self.hooked_sess.run(self.train_op)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 676, in run
    run_metadata=run_metadata)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1171, in run
    run_metadata=run_metadata)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1270, in run
    raise six.reraise(*original_exc_info)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    return self._sess.run(*args, **kwargs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1327, in run
    run_metadata=run_metadata)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/training/monitored_session.py", line 1091, in run
    return self._sess.run(*args, **kwargs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reduction axis 1 is empty in shape [512,0]
	 [[node tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/ArgMax (defined at /home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/model_cascade.py:90) ]]
	 [[node tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/mul (defined at /home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/model_cascade.py:94) ]]

Caused by op 'tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/ArgMax', defined at:
  File "train.py", line 132, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/interface.py", line 91, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/utils/argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/tower.py", line 224, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/trainers.py", line 190, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/graph_builder/training.py", line 225, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/graph_builder/training.py", line 121, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/graph_builder/training.py", line 115, in call_for_each_tower
    ret.append(func())
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/tower.py", line 281, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/train/tower.py", line 255, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorpack-0.9.8-py3.7.egg/tensorpack/tfutils/tower.py", line 291, in __call__
    output = self._tower_fn(*args)
  File "/home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py", line 74, in build_graph
    head_losses = self.roi_heads(image, features, proposals, targets)
  File "/home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py", line 288, in roi_heads
    (gt_boxes, gt_labels), image_shape2d, cfg.DATA.NUM_CATEGORY)
  File "/home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 46, in __init__
    B1_proposal = self.match_box_with_gt(B1, ious[1])
  File "/home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 90, in match_box_with_gt
    best_iou_ind = tf.argmax(iou, axis=1)  # N
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 86, in argmax
    return argmax_v2(input, axis, output_type, name)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 115, in argmax_v2
    return gen_math_ops.arg_max(input, axis, name=name, output_type=output_type)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 879, in arg_max
    name=name)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/madhav3101/env1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Reduction axis 1 is empty in shape [512,0]
	 [[node tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/ArgMax (defined at /home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/model_cascade.py:90) ]]
	 [[node tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/mul (defined at /home/madhav3101/cascade/tensorpack/examples/FasterRCNN/modeling/model_cascade.py:94) ]]

**Comment by ppwwyyxx** [comment]
Cascade R-CNN may not support such training - could you try a regular R-CNN?

**Comment by ppwwyyxx** [comment]
Cascade R-CNN can probably support it after using 
https://github.com/tensorpack/tensorpack/blob/d89b6f074d3a37a88aa35df49da58f934bd694f8/examples/FasterRCNN/modeling/model_frcnn.py#L91-L93 
to replace 
https://github.com/tensorpack/tensorpack/blob/d89b6f074d3a37a88aa35df49da58f934bd694f8/examples/FasterRCNN/modeling/model_cascade.py#L88

**Comment by mdv3101** [comment]
@ppwwyyxx thanks for the support. It worked for me. Closing this issue.

**Comment by ppwwyyxx** [comment]
That's good to hear. Could you explain "what" worked for you? Regular R-CNN, or the code change above?

**Comment by mdv3101** [comment]
@ppwwyyxx I made changes, as suggested, in Cascade RCNN. It works fine for me.
