### ISSUE TITLE
image2image.py on win10: AttributeError: Can't pickle local object 'get_data.<locals>.<lambda>'

### ISSUE THREAD

**Issue by Lucretious** [tensorpack/tensorpack#1412]
Hello, 
I am rather new to tensorflow and to python, but I am trying to learn, because I could use the image2image translation network. Well I played around with other pix2pix variants before, and I got some of them working, though rather slow. Then I read, that your tensorpack code is trimmed for speed, so I am trying this now, especially your image2image.py.

So I cloned your tensorpack.git and all the dependencies. Then I tried to train a small selfmade sample training set made out of 512x256 pixel Images, that I put together in the form B to A, in the folder ´train´in the main directory. The code starts, and asks if I want to keep the model. Then the error happens, and it tells me somewhere:

AttributeError: Can't pickle local object 'get_data.<locals>.<lambda>'

(1) The command line I used:         image2image.py --data train --mode BtoA

Log:

2020-03-26 23:19:47.581961: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
[0326 23:19:49 @logger.py:128] WRN Log directory train_log\Image2Image exists! Use 'd' to delete it.
[0326 23:19:49 @logger.py:131] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):d
[0326 23:19:51 @logger.py:92] Argv: I:\pix2pix basic\Image2Image.py --data train --mode BtoA
[0326 23:19:51 @parallel.py:207] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
Traceback (most recent call last):
  File "I:\pix2pix basic\Image2Image.py", line 215, in <module>
    data = QueueInput(get_data())
  File "I:\pix2pix basic\Image2Image.py", line 172, in get_data
    ds = MultiProcessRunner(ds, 100, 1)
  File "I:\pix2pix basic\tensorpack\dataflow\parallel.py", line 226, in __init__
    start_proc_mask_signal(self.procs)
  File "I:\pix2pix basic\tensorpack\utils\concurrency.py", line 239, in start_proc_mask_signal
    p.start()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_data.<locals>.<lambda>'

I:\pix2pix basic>2020-03-26 23:19:51.635938: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Here´s the log.txt:

[32m[0326 23:42:54 @logger.py:92][0m Argv: I:\pix2pix basic\Image2Image.py --data train --mode BtoA
[32m[0326 23:42:54 @parallel.py:207][0m [5m[31mWRN[0m MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.

2020-03-26 23:40:51.195079: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
--------------------  ---------------------------------------------------------------------------------
sys.platform          win32
Python                3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
Tensorpack            0.10
Numpy                 1.18.1
TensorFlow            1.15.0/v1.15.0-rc3-22-g590d6eef7e
TF Compiler Version   MSVC 191627032
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver
CUDA
CUDNN
NCCL
CUDA_VISIBLE_DEVICES  None
GPU                   AMD Ryzen 2600X
Free RAM              22.20/31.95 GB
CPU Count             12
cv2                   4.1.2
msgpack               1.0.0
python-prctl          False
--------------------  ---------------------------------------------------------------------------------

Don´t know why it says "CUDA_VISIBLE_DEVICES  None", I have a Geforce 1080 installed, which is (normally) recognized, and which I successfully used in other small neural network experiments.

  + You can install tensorpack master by `pip install -U git+https://github.com/tensorpack/tensorpack.git`
    and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell.

Tried the above, sadly, didin´t change my error. Oh, and may I ask a question? Is your image2image implementation somehow limited in image-dimensions? As I understand it, the original pix2pix code only accepts 256x256 pixel images, so I chose those for my training set.

Thank you very much for your time.

**Comment by ppwwyyxx** [comment]
fixed now. To use other image sizes you'll need to modify the model architecture

**Comment by Lucretious** [comment]
Wow, that was fast. Thank you very much.
