### ISSUE TITLE
image2image.py win10 error: Can't pickle local object 'AugmentImageComponents.__init__.<locals>.func'

### ISSUE THREAD

**Issue by Lucretious** [tensorpack/tensorpack#1413]
Sorry to bother you again,

I downloaded the whole repository new, to a new location, and checked, if maybe some requirements were different or new. Then I tried again with my command line:

image2image.py --data train --mode BtoA

sadly, I get a new ´pickle´error:

AttributeError: Can't pickle local object 'AugmentImageComponents.__init__.<locals>.func'

2020-03-27 10:17:35.841774: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
[0327 10:17:37 @logger.py:128] WRN Log directory train_log\Image2Image exists! Use 'd' to delete it.
[0327 10:17:37 @logger.py:131] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit.
Select Action: k (keep) / d (delete) / q (quit):d
[0327 10:17:39 @logger.py:92] Argv: I:\tensorpack\examples\GAN\Image2Image.py --data train --mode BtoA
[0327 10:17:39 @parallel.py:207] WRN MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.
Traceback (most recent call last):
  File "I:\tensorpack\examples\GAN\Image2Image.py", line 220, in <module>
    data = QueueInput(get_data())
  File "I:\tensorpack\examples\GAN\Image2Image.py", line 177, in get_data
    ds = MultiProcessRunner(ds, 100, 1)
  File "C:\Program Files\Python37\lib\site-packages\tensorpack\dataflow\parallel.py", line 226, in __init__
    start_proc_mask_signal(self.procs)
  File "C:\Program Files\Python37\lib\site-packages\tensorpack\utils\concurrency.py", line 239, in start_proc_mask_signal
    p.start()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'AugmentImageComponents.__init__.<locals>.func'

I:\tensorpack\examples\GAN>2020-03-27 10:17:39.824861: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

And here the logfile :

[32m[0327 10:17:39 @logger.py:92][0m Argv: I:\tensorpack\examples\GAN\Image2Image.py --data train --mode BtoA
[32m[0327 10:17:39 @parallel.py:207][0m [5m[31mWRN[0m MultiProcessRunner does support Windows. However, Windows requires more strict picklability on processes, which may lead of failure on some of the code.

>>> import tensorpack.tfutils as u; print(u.collect_env_info())
--------------------  ---------------------------------------------------------------------------------
sys.platform          win32
Python                3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
Tensorpack            v0.10-0-g7958d608-dirty
Numpy                 1.18.1
TensorFlow            1.15.0/v1.15.0-rc3-22-g590d6eef7e
TF Compiler Version   MSVC 191627032
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver
CUDA
CUDNN
NCCL
CUDA_VISIBLE_DEVICES  None
GPU                   Not found with NVML
Free RAM              23.92/31.95 GB
CPU Count             12
cv2                   4.1.2
msgpack               1.0.0
python-prctl          False
--------------------  ---------------------------------------------------------------------------------

Thank you again in advance for your time.

**Comment by ppwwyyxx** [comment]
Alright..
Most of the code is not tested on windows so things like this could happen. I'll fix it shortly.

**Comment by Lucretious** [comment]
Really sorry to take up your time. I absolutely know nothing about linux, otherwise I would try installing and working with it. Thank you again for helping.
