### ISSUE TITLE
AssertionError: "Cannot create tower {} under reuse=True!".format(ns_name)

### ISSUE THREAD

**Issue by sara782** [tensorpack/tensorpack#1431]
### 1. What I did:

I'm using this code : https://github.com/twangnh/Distilling-Object-Detectors-Shuffledet
which calls upon TowerContext from your tensorpack/tfutils/tower.py 

`with TowerContext(tf.get_default_graph().get_name_scope(), is_training=mc.IS_TRAINING):`

the "is_training" here is true, so it goes to TrainTowerContext and that's where an assertion error occurs

```
Traceback (most recent call last):
  File "train_multi_gpu.py", line 161, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_multi_gpu.py", line 157, in main
    train()
  File "train_multi_gpu.py", line 86, in train
    optimizer=optimizer, freeze_variable_func=freeze_variable_func)
  File "/content/Distilling-Object-Detectors-Shuffledet-master/lib/utils/model_deploy.py", line 350, in deploy
    clones = create_clones(config, model_fn, args)
  File "/content/Distilling-Object-Detectors-Shuffledet-master/lib/utils/model_deploy.py", line 191, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "/content/Distilling-Object-Detectors-Shuffledet-master/lib/models/shuffleDet_sup.py", line 74, in model_fn
    self._add_forward_graph(student)
  File "/content/Distilling-Object-Detectors-Shuffledet-master/lib/models/shuffleDet_sup.py", line 246, in _add_forward_graph
    with TowerContext(tf.get_default_graph().get_name_scope(), is_training=mc.IS_TRAINING):#with TowerContext(tf.get_default_graph().get_name_scope(), is_training=mc.IS_TRAINING, index=int(tf.get_default_graph().get_name_scope()[-1])):
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/tower.py", line 243, in TowerContext
    return TrainTowerContext(tower_name, vs_name=vs_name)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/tower.py", line 183, in __init__
    "Cannot create tower {} under reuse=True!".format(ns_name)
AssertionError: Cannot create tower clone_1 under reuse=True!
```
### 2. My environment:
The output of this command: `python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'`:
sys.platform         linux
Python               3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Tensorpack           v0.10.1-0-g8f831349-dirty
Numpy                1.18.3
TensorFlow           1.7.0/v1.7.0-3-g024aecf414
TF Compiler Version  4.8.4
TF CUDA support      False
TF MKL support       False
Free RAM             11.47/12.72 GB
CPU Count            2
cv2                  4.1.2
msgpack              1.0.0
python-prctl         False

Please help!

**Comment by ppwwyyxx** [comment]
The code was not correct w.r.t. latest version of tensorpack: If TrainTowerContext is used for multi-gpu training, index of the GPU and total number of GPUs should be provided.
