### ISSUE TITLE
ValueError: Trying to load an array of shape (80,) into variable 'maskrcnn/conv/b' whose shape is (34,)

### ISSUE THREAD

**Issue by JYueee** [tensorpack/tensorpack#1436]
I try to train  the maskrcnn example with my own coco style dataset, and I download a pre-trained model COCO-MaskRCNN-R101FPN9xGNCasAugScratch. But I got this ValueError , How can I figure it out ?
  
 Your environment:
python 3.6 tensorflow1.13

--------------------  ------------------------------------------------------------------------------------
sys.platform          win32
Python                3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)]
Tensorpack            v0.10.1-1-g17c5984f-dirty
Numpy                 1.17.0
TensorFlow            1.13.1/b'unknown'
TF Compiler Version   MSVC 190024215
TF CUDA support       True
TF MKL support        False
Nvidia Driver
CUDA
CUDNN
NCCL
CUDA_VISIBLE_DEVICES  Unspecified
GPU                   Not found with NVML
Free RAM              7.71/11.81 GB
CPU Count             12
cv2                   4.2.0
msgpack               1.0.0
python-prctl          False
--------------------  ------------------------------------------------------------------------------------
[0509 16:15:18 @config.py:320] Config: ------------------------------------------
{'BACKBONE': {'FREEZE_AFFINE': False,
              'FREEZE_AT': 2,
              'NORM': 'GN',
              'RESNET_NUM_BLOCKS': [3, 4, 23, 3],
              'STRIDE_1X1': False,
              'TF_PAD_MODE': False,
              'WEIGHTS': 'COCO-MaskRCNN-R101FPN9xGNCasAugScratch.npz'},
 'CASCADE': {'BBOX_REG_WEIGHTS': [[10.0, 10.0, 5.0, 5.0], [20.0, 20.0, 10.0, 10.0],
                                  [30.0, 30.0, 15.0, 15.0]],
             'IOUS': [0.5, 0.6, 0.7]},
 'DATA': {'ABSOLUTE_COORD': True,
          'BASEDIR': 'E:\\ALi3DAI\\dataset',
          'CLASS_NAMES': ['BG', 'Children Cabinet', 'Nightstand', 'Bookcase / jewelry Armoire',
                          'Wardrobe', 'Tea Table', 'Corner/Side Table',
                          'Sideboard / Side Cabinet / Console', 'Wine Cooler', 'TV Stand',
                          'Drawer Chest / Corner cabinet', 'Shelf', 'Round End Table', 'Double Bed',
                          'Bunk Bed', 'Bed Frame', 'Single bed', 'Kids Bed', 'Dining Chair',
                          'Lounge Chair / Book-chair / Computer Chair', 'Dressing Chair',
                          'Classic Chinese Chair', 'Barstool', 'Dressing Table', 'Dining Table',
                          'Table', 'Three-Seat / Multi-person sofa', 'achairmr', 'Two-seat Sofa',
                          'L-shaped Sofa', 'Lazy Sofa', 'Chaise Longue Sofa',
                          'Footstool / Sofastool / Bed End Stool / Stool', 'Pendant Lamp',
                          'Ceiling Lamp'],
          'FILTER_EMPTY_ANNOTATIONS': True,
          'NUM_CATEGORY': 34,
          'NUM_WORKERS': 0,
          'TRAIN': ('coco_train2017',),
          'VAL': ('coco_val2017',)},
 'FPN': {'ANCHOR_STRIDES': (4, 8, 16, 32, 64),
         'CASCADE': True,
         'FRCNN_CONV_HEAD_DIM': 256,
         'FRCNN_FC_HEAD_DIM': 1024,
         'FRCNN_HEAD_FUNC': 'fastrcnn_4conv1fc_gn_head',
         'MRCNN_HEAD_FUNC': 'maskrcnn_up4conv_gn_head',
         'NORM': 'GN',
         'NUM_CHANNEL': 256,
         'PROPOSAL_MODE': 'Level',
         'RESOLUTION_REQUIREMENT': 32},
 'FRCNN': {'BATCH_PER_IM': 512,
           'BBOX_REG_WEIGHTS': [10.0, 10.0, 5.0, 5.0],
           'FG_RATIO': 0.25,
           'FG_THRESH': 0.5},
 'MODE_FPN': True,
 'MODE_MASK': True,
 'MRCNN': {'ACCURATE_PASTE': True, 'HEAD_DIM': 256},
 'PREPROC': {'MAX_SIZE': 1344.0,
             'PIXEL_MEAN': [123.675, 116.28, 103.53],
             'PIXEL_STD': [58.395, 57.12, 57.375],
             'TEST_SHORT_EDGE_SIZE': 800,
             'TRAIN_SHORT_EDGE_SIZE': [640, 800]},
 'RPN': {'ANCHOR_RATIOS': (0.5, 1.0, 2.0),
         'ANCHOR_SIZES': (32, 64, 128, 256, 512),
         'ANCHOR_STRIDE': 16,
         'BATCH_PER_IM': 256,
         'CROWD_OVERLAP_THRESH': 9.99,
         'FG_RATIO': 0.5,
         'HEAD_DIM': 1024,
         'MIN_SIZE': 0,
         'NEGATIVE_ANCHOR_THRESH': 0.3,
         'NUM_ANCHOR': 15,
         'POSITIVE_ANCHOR_THRESH': 0.7,
         'PROPOSAL_NMS_THRESH': 0.7,
         'TEST_PER_LEVEL_NMS_TOPK': 1000,
         'TEST_POST_NMS_TOPK': 1000,
         'TEST_PRE_NMS_TOPK': 6000,
         'TRAIN_PER_LEVEL_NMS_TOPK': 2000,
         'TRAIN_POST_NMS_TOPK': 2000,
         'TRAIN_PRE_NMS_TOPK': 12000},
 'TEST': {'FRCNN_NMS_THRESH': 0.5,
          'RESULTS_PER_IM': 100,
          'RESULT_SCORE_THRESH': 0.05,
          'RESULT_SCORE_THRESH_VIS': 0.5},
 'TRAIN': {'BASE_LR': 0.01,
           'CHECKPOINT_PERIOD': 20,
           'EVAL_PERIOD': 50,
           'LR_SCHEDULE': [1500000, 1580000, 1620000],
           'NUM_GPUS': 1,
           'STARTING_EPOCH': 1,
           'STEPS_PER_EPOCH': 500,
           'WARMUP': 1000,
           'WARMUP_INIT_LR': 0.0,
           'WEIGHT_DECAY': 0.0001},
 'TRAINER': 'replicated'}
[0509 16:15:18 @train.py:73] Warm Up Schedule (steps, value): [(0, 0.0), (1000, 0.01)]
[0509 16:15:18 @train.py:74] LR Schedule (epochs, value): [(2, 0.01), (24000.0, 0.001), (25280.0, 0.00010000000000000002)]
loading annotations into memory...
Done (t=26.75s)
creating index...
index created!

[0509 16:18:49 @sessinit.py:87] WRN The following variables are in the graph, but not found in the dict: global_step, learning_rate
[0509 16:18:49 @sessinit.py:236] Restoring 436 variables from dict ...
Traceback (most recent call last):
  File "e:\ALi3DAI\MastRCNN_tensorpack\train.py", line 125, in <module>
    launch_train_with_config(traincfg, trainer)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\train\interface.py", line 99, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\train\base.py", line 342, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\train\base.py", line 313, in train
    self.initialize(session_creator, session_init)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\utils\argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\train\tower.py", line 147, in initialize
    super(TowerTrainer, self).initialize(session_creator, session_init)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\utils\argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\train\base.py", line 235, in initialize
    session_init._run_init(self.sess)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\tfutils\sessinit.py", line 237, in _run_init
    upd.update({name: value for name, value in six.iteritems(self._prms) if name in intersect})
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\tfutils\varmanip.py", line 132, in update
    value, var, ignore_mismatch=self.ignore_mismatch)
  File "D:\software\Anaconda3\envs\tensorflow-gpu1.13\lib\site-packages\tensorpack\tfutils\varmanip.py", line 85, in relaxed_value_for_var
    value.shape, name, varshape))
ValueError: Trying to load an array of shape (80,) into variable 'maskrcnn/conv/b' whose shape is (34,).

**Comment by ppwwyyxx** [comment]
`--load` the model.
