### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Adblu** [tensorpack/tensorpack#1438]
Hi. I want to run:

```
 ./predict.py --evaluate /home/n/Documents/cars_mask_rcnn/tests/models_ex1/stats.json --load /home/n/Documents/cars_mask_rcnn/tests/models_ex1/model-5000.data-00000-of-00001 --config SAME-AS_TRAINING
```

However Im getting:

```
/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "./predict.py", line 125, in <module>
    cfg.update_args(args.config)
  File "/home/n/Documents/cars_mask_rcnn/tests/config.py", line 58, in update_args
    keys, v = cfg.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)

```

What might be wrong ?

**Comment by ppwwyyxx** [comment]
`SAME-AS_TRAINING` means use the same config arguments as training.
