### ISSUE TITLE
Missing "image_tensor:0"

### ISSUE THREAD

**Issue by Adblu** [tensorpack/tensorpack#1444]
I am using 'predict.py' with option '--output-pb' on my own custom inference script, and I'm getting weir error:

```
Traceback (most recent call last):
  File "/home/n/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8914418476c7>", line 1, in <module>
    runfile('/home/n/Documents/cars_mask_rcnn/tests/adrian_predictor/predictor2.py', wdir='/home/n/Documents/cars_mask_rcnn/tests/adrian_predictor')
  File "/snap/pycharm-community/194/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-community/194/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/n/Documents/cars_mask_rcnn/tests/adrian_predictor/predictor2.py", line 13, in <module>
    d_img, d_prediction, joint_mask = damage_objects.run_on_image(img_path=im_path, get_joint_mask=True)
  File "/home/n/Documents/cars_mask_rcnn/tests/adrian_predictor/utils.py", line 110, in run_on_image
    _inputs = [self.graph.get_tensor_by_name (input_name + ":0") for input_name in input_tensors]
  File "/home/n/Documents/cars_mask_rcnn/tests/adrian_predictor/utils.py", line 110, in <listcomp>
    _inputs = [self.graph.get_tensor_by_name (input_name + ":0") for input_name in input_tensors]
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3972, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3796, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3838, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'image_tensor:0' refers to a Tensor which does not exist. The operation, 'image_tensor', does not exist in the graph."

```

Could you elaborate on what is going on ? why this tensor is missing ? Or what are tensors responsible for image segmentation ?

**Comment by ppwwyyxx** [comment]
The tensor is missing because it is not defined. The tensors that should be used as inputs are defined by user when implementing the model.
