### ISSUE TITLE
Please read & provide the following information

### ISSUE THREAD

**Issue by Eunhui-Kim** [tensorpack/tensorpack#1463]
When I run on my server with multiple-gpus, I met the following error messages from tensorpack.
What is the error message mean?
How can I solve the following restrictions?
When I run resnet50 images with 4-gpus of 32GB, it reports it will take about 21 days.
I think it's too long even with 4 gpus.
This error message is related with the long training time?
Thank you~

----------------------------- error messages -----------------------------------------------------
tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
Traceback (most recent call last):
  File "/apps/applications/PYTHON/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/apps/applications/PYTHON/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home01/hpc15a01/.local/lib/python3.7/site-packages/tensorpack/callbacks/prof.py", line 128, in worker
    devices = [ctx.device(i) for i in devices]
  File "/home01/hpc15a01/.local/lib/python3.7/site-packages/tensorpack/callbacks/prof.py", line 128, in <listcomp>
    devices = [ctx.device(i) for i in devices]
  File "/home01/hpc15a01/.local/lib/python3.7/site-packages/tensorpack/utils/nvml.py", line 203, in device
    "nvmlDeviceGetHandleByIndex_v2")(c_index, byref(device)))
  File "/home01/hpc15a01/.local/lib/python3.7/site-packages/tensorpack/utils/nvml.py", line 48, in _check_return
    raise NvmlException(ret)
tensorpack.utils.nvml.NvmlException: NVML_ERROR_INVALID_ARGUMENT

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by Eunhui-Kim** [comment]
OK, I'll upload as you suggest
Thus, close this
