### ISSUE TITLE
NotImplementedError when doing evaluate

### ISSUE THREAD

**Issue by Nina-Gn** [tensorpack/tensorpack#1466]
### 1. What I did:

# Evaluation
!python ./predict.py --config DATA.BASEDIR=./plastic/ MODE_FPN=True \
	"DATA.VAL=('plastic_val',)"  "DATA.TRAIN=('plastic_train',)" \
	--load train_log/bags/checkpoint --evaluate output.json

I think the issue lies within "output.json". What exactly is requested there? 

### 2. What I observed:

[0715 14:02:32 @sessinit.py:114] Restoring checkpoint from train_log/bags/model-4000 ...
[0715 14:02:33 @predict.py:87] Evaluating plastic_val ...
Traceback (most recent call last):
  File "./predict.py", line 164, in <module>
    do_evaluate(predcfg, args.evaluate)
  File "./predict.py", line 90, in do_evaluate
    for k in range(num_tower)]
  File "./predict.py", line 90, in <listcomp>
    for k in range(num_tower)]
  File "/nfs/data/sozi5148/MRCNN_bag/data.py", line 379, in get_eval_dataflow
    roidbs = DatasetRegistry.get(name).inference_roidbs()
  File "/nfs/data/sozi5148/MRCNN_bag/dataset/dataset.py", line 54, in inference_roidbs
    raise NotImplementedError()
NotImplementedError

### 3. What I expected:

Evaluation Output

### 4. My environment:

Python: 3.73
Tensorflow: 1.15
Tensorpack: latest

**Comment by ppwwyyxx** [comment]
As https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/dataset/dataset.py says, the relevant methods of a custom dataset need to be implemented
