### ISSUE TITLE
How to get the results of each image in the resnet classification?

### ISSUE THREAD

**Issue by CruiseShao** [tensorpack/tensorpack#1469]
+ If you did something with tensorpack and it failed, PLEASE STOP HERE and use the "Unexpected Problems /
  Bugs" category.

+ Your question is probably answered in [tutorials](http://tensorpack.readthedocs.io/tutorial/index.html#user-tutorials). Read it first.

+ We answer "HOW to do X with Tensorpack" for a well-defined specific X.
  X must be something that you conceptually know how to do, but are unable to do due to lack of knowledge about Tensorpack.
  We don't answer vague questions like "How to do semantic segmentation in Tensorpack".

+ We also answer "HOW/WHY Tensorpack does X" for some X that Tensorpack or its examples are doing.

Some typical questions that we DO NOT answer:

+ "Could you improve/implement an example/paper?":

  We have no plans to do so. We don't consider feature
  requests for examples or implement a paper for you.
  If you don't know how to do something yourself, you may ask a usage question.

+ "The examples do not perform as expected after I change the models/dataset/parameters/etc.":

  Tensorpack maintainers make sure the examples perform well without modifications.
  But it's your job to pick the model and parameters that are suitable for your own situation.
  We cannot help with such questions unless they appear to be a bug in tensorpack.

+ "Why my own model doesn't perform well?", "I don't understand this paper you implement.",
  "How should I change the parameters for my own dataset?":

  We do not answer machine learning questions.

You can also use gitter (https://gitter.im/tensorpack/users) for more casual discussions.

Hello, thank you very much for your contribution.
When I make model inferences using my own resnet-SE network data set (modeled after the Imagenet format), I can only get the overall erro-top1 and erro-top5 of the val dataset.
How should I modify the code to get the **predicted result**(which category) or **the predicted probability** of each categories for **each image**.

**Comment by ppwwyyxx** [comment]
see https://tensorpack.readthedocs.io/tutorial/inference.html

**Comment by CruiseShao** [comment]
> see https://tensorpack.readthedocs.io/tutorial/inference.html


Are there any specific examples or previous answers, just a simple explanation is just too difficult for me to finish this work.

**Comment by ppwwyyxx** [comment]
The link https://tensorpack.readthedocs.io/tutorial/inference.html#offlinepredictor contains examples

**Comment by CruiseShao** [comment]
Hello, I solved the problem by getting the classification probability of each image by obtaining the 'prob' in the resnet network.

But I run into another problem: Since I'm getting the image from the URL, And I can't guarantee that every image will be successful, I want to know in which function the ”mapf (dp)“ function in the ”get_imagenet_dataflow“ function is called correctly so that I can do exception handling on that function.

**Comment by CruiseShao** [comment]
**map_func (callable): datapoint -> datapoint | None. Return None to
                discard/skip the datapoint.**
Hello, I have found the sentence you wrote in the comment. Does this sentence mean that if the image is not obtained successfully, I just need to return None, and it will  automatically  give up this image acquisition andproceed to the next image acquisition

**Comment by ppwwyyxx** [comment]
> Does this sentence mean that if the image is not obtained successfully, I just need to return None, and it will automatically give up this image acquisition andproceed to the next image acquisition

yes

**Comment by CruiseShao** [comment]
4%|▎         | 98/2721 [02:08<1:39:40,  2.28s/it]Exception in thread Thread-20:
Traceback (most recent call last):
  File "/opt/app/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 135, in run
    obj = self.func(dp)
  File "/home/powerop/work/label_classify/tensorpack/examples/ResNet/imagenet_utils.py", line 123, in mapf
    im = aug.augment(im)
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/imgaug/base.py", line 198, in augment
    check_dtype(img)
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/image.py", line 18, in check_dtype
    assert isinstance(img, np.ndarray), "[Augmentor] Needs an numpy array, but got a {}!".format(type(img))
AssertionError: [Augmentor] Needs an numpy array, but got a <class 'NoneType'>!

  6%|▌         | 168/2721 [06:00<3:02:39,  4.29s/it]

It does not continue to work and I found the following comment in your code:
 **# cannot ignore None here. will lead to unsynced send/recv**
(in parallel_map.py ,line 134)

**Comment by ppwwyyxx** [comment]
From the error, it looks like you did not return None, but threw an exception.

If you need help diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)). Without knowing what you did we cannot help.

**Comment by CruiseShao** [comment]
I just realize what stupid thing I have did，hhhhh~~

As you say, I didn't really return None, which is the format that returns [None, label]

**Comment by CruiseShao** [comment]
0%|          | 0/2721 [00:00<?, ?it/s]
[0722 09:13:18 @input_source.py:599] Pre-filling StagingArea ...
[0722 09:13:19 @input_source.py:603] 1 element was put into StagingArea on each tower.
  3%|▎         | 93/2721 [01:55<1:32:40,  2.12s/it]Process _Worker-1:
Traceback (most recent call last):
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 50, in _repeat_iter
    yield from get_itr()
  File "/opt/app/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 313, in run
    dp = next(itr)
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 120, in __iter__
    for data in self.ds:
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 202, in __iter__
    yield from super(MultiThreadMapData, self).__iter__()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 87, in __iter__
    yield from self.get_data_strict()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 74, in get_data_strict
    yield self._recv_filter_none()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 47, in _recv_filter_none
    "[{}] Map function cannot return None when strict mode is used.".format(type(self).__name__)
AssertionError: [MultiThreadMapData] Map function cannot return None when strict mode is used.
  4%|▍         | 117/2721 [02:54<1:54:50,  2.65s/it]
[0722 09:16:13 @parallel.py:351] ERR Exception '<class 'AssertionError'>' in worker:
[0722 09:16:13 @input_source.py:171] ERR [EnqueueThread] Exception in thread EnqueueThread: enqueue dataflow to TF queue "QueueInput/input_queue":
Traceback (most recent call last):
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 159, in run
    dp = next(self._itr)
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 389, in __iter__
    yield from self.ds
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 363, in __iter__
    yield self._recv()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 352, in _recv
    raise exc.exc_type(exc.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 313, in run
    dp = next(itr)
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 50, in _repeat_iter
    yield from get_itr()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/common.py", line 120, in __iter__
    for data in self.ds:
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 202, in __iter__
    yield from super(MultiThreadMapData, self).__iter__()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 87, in __iter__
    yield from self.get_data_strict()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 74, in get_data_strict
    yield self._recv_filter_none()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 47, in _recv_filter_none
    "[{}] Map function cannot return None when strict mode is used.".format(type(self).__name__)
AssertionError: [MultiThreadMapData] Map function cannot return None when strict mode is used.

[0722 09:16:13 @input_source.py:177] [EnqueueThread] Thread EnqueueThread: enqueue dataflow to TF queue "QueueInput/input_queue" Exited.
  6%|▌         | 168/2721 [05:41<1:26:27,  2.03s/it]
---------------------------------------------------------------------------
OutOfRangeError                           Traceback (most recent call last)
/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1350                                       target_list, run_metadata)
   1351 

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1442                                             fetch_list, target_list,
-> 1443                                             run_metadata)
   1444 

OutOfRangeError: FIFOQueue '_0_QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[{{node QueueInput/input_deque}}]]

During handling of the above exception, another exception occurred:

OutOfRangeError                           Traceback (most recent call last)
<ipython-input-2-66c440eb6ad2> in <module>
     41         ds = get_imagenet_dataflow(args.data, 'val', batch)#,parallel=1
     42         Init=SmartInit(args.load)
---> 43         eval_classification(model,Init , ds)
     44     else:
     45         if args.fake:

~/work/label_classify/tensorpack/examples/ResNet/imagenet_utils.py in eval_classification(model, sessinit, dataflow)
    348     csv_write_path = all_path + csv_file_name_write
    349     for _ in tqdm.trange(dataflow.size()):
--> 350         top1, top5, prob,imgname,csvline=pred()
    351         #print(res.shape)
    352         #print([np.argmax(res[i,:]) for i in range(res.shape[0])])

~/.local/lib/python3.6/site-packages/tensorpack/predict/feedfree.py in __call__(self)
     66 
     67     def __call__(self):
---> 68         return self._hooked_sess.run(self._output_tensors)
     69 
     70     def _do_call(self):

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py in run(self, fetches, feed_dict, options, run_metadata)
   1416         feed_dict=feed_dict,
   1417         options=options,
-> 1418         run_metadata=run_metadata)
   1419 
   1420     for hook in self._hooks:

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py in run(self, *args, **kwargs)
   1174 
   1175   def run(self, *args, **kwargs):
-> 1176     return self._sess.run(*args, **kwargs)
   1177 
   1178   def run_step_fn(self, step_fn, raw_session, run_with_hooks):

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1178     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:
   1182       results = []

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

OutOfRangeError: FIFOQueue '_0_QueueInput/input_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node QueueInput/input_deque (defined at /opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'QueueInput/input_deque':
  File "/opt/app/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/app/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/app/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 597, in start
    self.io_loop.start()
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/opt/app/conda/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/opt/app/conda/lib/python3.6/asyncio/base_events.py", line 1434, in _run_once
    handle._run()
  File "/opt/app/conda/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 381, in dispatch_queue
    yield self.process_one()
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 225, in wrapper
    runner = Runner(result, future, yielded)
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 714, in __init__
    self.run()
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 545, in execute_request
    user_expressions, allow_stdin,
  File "/opt/app/conda/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/app/conda/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/app/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/opt/app/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "/opt/app/conda/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/app/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/app/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/opt/app/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-66c440eb6ad2>", line 43, in <module>
    eval_classification(model,Init , ds)
  File "/home/powerop/work/label_classify/tensorpack/examples/ResNet/imagenet_utils.py", line 344, in eval_classification
    pred = FeedfreePredictor(pred_config, StagingInput(QueueInput(dataflow), device='/gpu:0'))
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/predict/feedfree.py", line 38, in __init__
    self._input_tensors = self._input_source.get_input_tensors()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/input_source/input_source_base.py", line 114, in get_input_tensors
    return self._get_input_tensors()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 665, in _get_input_tensors
    inputs = self._input.get_input_tensors()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/input_source/input_source_base.py", line 114, in get_input_tensors
    return self._get_input_tensors()
  File "/home/powerop/.local/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 270, in _get_input_tensors
    ret = self.queue.dequeue(name='input_deque')
  File "/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/ops/data_flow_ops.py", line 446, in dequeue
    self._queue_ref, self._dtypes, name=name)
  File "/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_data_flow_ops.py", line 4140, in queue_dequeue_v2
    timeout_ms=timeout_ms, name=name)
  File "/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/opt/app/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Another exception occur when return None**

**Comment by CruiseShao** [comment]
Will strict mode affect the prediction, I'm using strict mode in the MultiThreadMapData function, and no errors have been reported yet.

**Comment by CruiseShao** [comment]
Hi, I was using resnet for category prediction and found that the initial prediction speed was 6 s/it, after running 500 epochs, the prediction speed is now 14 s/it.
After checking the GPU and CPU, I found that although the GPU memory is occupied, the GPU usage is 0, and the CPU is always running at high speed.
Is it because the strict mode is changed to false?

**Comment by CruiseShao** [comment]
I've fixed an exception error in strict mode when the input was None: 
add  a judge after parallel_map.py, line 135 of OBJ. The code is as follows:
`def run(self):
            try:
                while True:
                    dp = self.queue_get_stoppable(self.inq)
                    if self.stopped():
                        return
                    # cannot ignore None here. will lead to unsynced send/recv
                    obj = self.func(dp)
                    **if obj is None:
                        continue**
                    self.queue_put_stoppable(self.outq, obj)
            except Exception:
                if self.stopped():
                    pass        # skip duplicated error messages
                else:
                    raise
            finally:
                self.stop()`

**Comment by ppwwyyxx** [comment]
> AssertionError: [MultiThreadMapData] Map function cannot return None when strict mode is used.

As the error suggests, strict mode cannot be used if the function returns None. It was not well implemented
