### ISSUE TITLE
FasterRCNN - Trying with TF 2.4.1 - getting error - Attempting to capture an EagerTensor without building a function

### ISSUE THREAD

**Issue by vijaygill** [tensorpack/tensorpack#1520]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) Setup environment in docker container. Tensorflow base image "tensorflow/tensorflow:2.4.1-gpu". Tensorpack installed using command "pip install --user  git+https://github.com/tensorpack/tensorpack.git". Then followed instructions for ballons example.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```

[0402 21:41:21 @logger.py:92] Argv: ./train.py --config DATA.BASEDIR=/code/temp_code/balloon/balloon MODE_FPN=True DATA.VAL=('balloon_val',) DATA.TRAIN=('balloon_train',) TRAIN.BASE_LR=1e-3 TRAIN.EVAL_PERIOD=0 TRAIN.LR_SCHEDULE=[1000] PREPROC.TRAIN_SHORT_EDGE_SIZE=[600,1200] TRAIN.CHECKPOINT_PERIOD=1 DATA.NUM_WORKERS=1 --load /code/temp_code/balloon/COCO-MaskRCNN-R50FPN2x.npz --logdir /code/temp_code/balloon/train_log/balloon
[0402 21:41:22 @train.py:47] Environment Information:
-----------------------  -------------------------------------------------------------------------------
sys.platform             linux
Python                   3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
Tensorpack               v0.11-2-g88530083-dirty @/.local/lib/python3.6/site-packages/tensorpack
Numpy                    1.19.5
TensorFlow               2.4.1/v2.4.0-49-g85c8b2a817f @/usr/local/lib/python3.6/dist-packages/tensorflow
TF Compiler Version      7.3.1 20180303
TF CUDA support          True
TF MKL support           False
TF XLA support           False
Nvidia Driver            /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.460.67
CUDA libs                /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so.11.0.221
CUDNN libs               /usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
TF compute capabilities  sm_35,sm_50,sm_60,sm_70,sm_75,80
TF built with CUDA       11.0
TF built with CUDNN      8
NCCL libs
CUDA_VISIBLE_DEVICES     Unspecified
GPU 0                    GeForce RTX 2080 SUPER
Free RAM                 61.23/62.57 GB
CPU Count                8
cv2                      4.5.1
msgpack                  1.0.2
python-prctl             True
-----------------------  -------------------------------------------------------------------------------
[0402 21:41:22 @config.py:322] Config: ------------------------------------------
{'BACKBONE': {'FREEZE_AFFINE': False,
              'FREEZE_AT': 2,
              'NORM': 'FreezeBN',
              'RESNET_NUM_BLOCKS': [3, 4, 6, 3],
              'STRIDE_1X1': False,
              'TF_PAD_MODE': False,
              'WEIGHTS': ''},
 'CASCADE': {'BBOX_REG_WEIGHTS': [[10.0, 10.0, 5.0, 5.0], [20.0, 20.0, 10.0, 10.0],
                                  [30.0, 30.0, 15.0, 15.0]],
             'IOUS': [0.5, 0.6, 0.7]},
 'DATA': {'ABSOLUTE_COORD': True,
          'BASEDIR': '/code/temp_code/balloon/balloon',
          'CLASS_NAMES': ['BG', 'balloon'],
          'FILTER_EMPTY_ANNOTATIONS': True,
          'NUM_CATEGORY': 1,
          'NUM_WORKERS': 1,
          'TRAIN': ('balloon_train',),
          'VAL': ('balloon_val',)},
 'FPN': {'ANCHOR_STRIDES': (4, 8, 16, 32, 64),
         'CASCADE': False,
         'FRCNN_CONV_HEAD_DIM': 256,
         'FRCNN_FC_HEAD_DIM': 1024,
         'FRCNN_HEAD_FUNC': 'fastrcnn_2fc_head',
         'MRCNN_HEAD_FUNC': 'maskrcnn_up4conv_head',
         'NORM': 'None',
         'NUM_CHANNEL': 256,
         'PROPOSAL_MODE': 'Level',
         'RESOLUTION_REQUIREMENT': 32},
 'FRCNN': {'BATCH_PER_IM': 512,
           'BBOX_REG_WEIGHTS': [10.0, 10.0, 5.0, 5.0],
           'FG_RATIO': 0.25,
           'FG_THRESH': 0.5},
 'MODE_FPN': True,
 'MODE_MASK': True,
 'MRCNN': {'ACCURATE_PASTE': True, 'HEAD_DIM': 256},
 'PREPROC': {'MAX_SIZE': 1344.0,
             'PIXEL_MEAN': [123.675, 116.28, 103.53],
             'PIXEL_STD': [58.395, 57.12, 57.375],
             'TEST_SHORT_EDGE_SIZE': 800,
             'TRAIN_SHORT_EDGE_SIZE': [600, 1200]},
 'RPN': {'ANCHOR_RATIOS': (0.5, 1.0, 2.0),
         'ANCHOR_SIZES': (32, 64, 128, 256, 512),
         'ANCHOR_STRIDE': 16,
         'BATCH_PER_IM': 256,
         'CROWD_OVERLAP_THRESH': 9.99,
         'FG_RATIO': 0.5,
         'HEAD_DIM': 1024,
         'MIN_SIZE': 0,
         'NEGATIVE_ANCHOR_THRESH': 0.3,
         'NUM_ANCHOR': 15,
         'POSITIVE_ANCHOR_THRESH': 0.7,
         'PROPOSAL_NMS_THRESH': 0.7,
         'TEST_PER_LEVEL_NMS_TOPK': 1000,
         'TEST_POST_NMS_TOPK': 1000,
         'TEST_PRE_NMS_TOPK': 6000,
         'TRAIN_PER_LEVEL_NMS_TOPK': 2000,
         'TRAIN_POST_NMS_TOPK': 2000,
         'TRAIN_PRE_NMS_TOPK': 12000},
 'TEST': {'FRCNN_NMS_THRESH': 0.5,
          'RESULTS_PER_IM': 100,
          'RESULT_SCORE_THRESH': 0.05,
          'RESULT_SCORE_THRESH_VIS': 0.5},
 'TRAIN': {'BASE_LR': 0.001,
           'CHECKPOINT_PERIOD': 1,
           'EVAL_PERIOD': 0,
           'LR_SCHEDULE': [1000],
           'NUM_GPUS': 1,
           'STARTING_EPOCH': 1,
           'STEPS_PER_EPOCH': 500,
           'WARMUP': 1000,
           'WARMUP_INIT_LR': 1e-05,
           'WEIGHT_DECAY': 0.0001},
 'TRAINER': 'replicated'}
[0402 21:41:22 @train.py:67] Warm Up Schedule (steps, value): [(0, 1e-05), (1000, 0.001)]
[0402 21:41:22 @train.py:68] LR Schedule (epochs, value): [(2, 0.001)]
[0402 21:41:22 @data.py:62] Ground-Truth category distribution:
|  class  | #box   |
|:-------:|:-------|
| balloon | 255    |
|  total  | 255    |
[0402 21:41:22 @data.py:352] Filtered 0 images which contain no non-crowd groudtruth boxes. Total #images for training: 61
[0402 21:41:22 @train.py:72] Total passes of the training set is: 131.15
[0402 21:41:22 @sessinit.py:298] Loading dictionary from /code/temp_code/balloon/COCO-MaskRCNN-R50FPN2x.npz ...
[0402 21:41:22 @input_source.py:221] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0402 21:41:23 @training.py:110] Building graph for training tower 0 on device /gpu:0 ...
[0402 21:41:23 @argtools.py:138] WRN Some BatchNorm layer uses moving_mean/moving_variance in training.
[0402 21:41:23 @registry.py:90] 'conv0': [1, 3, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'pool0': [1, 64, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block0/conv1': [1, 64, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block0/conv2': [1, 64, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block0/conv3': [1, 64, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block0/convshortcut': [1, 64, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block1/conv1': [1, 256, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block1/conv2': [1, 64, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block1/conv3': [1, 64, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block2/conv1': [1, 256, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block2/conv2': [1, 64, ?, ?] --> [1, 64, ?, ?]
[0402 21:41:23 @registry.py:90] 'group0/block2/conv3': [1, 64, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block0/conv1': [1, 256, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block0/conv2': [1, 128, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block0/conv3': [1, 128, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block0/convshortcut': [1, 256, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block1/conv1': [1, 512, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block1/conv2': [1, 128, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block1/conv3': [1, 128, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block2/conv1': [1, 512, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block2/conv2': [1, 128, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block2/conv3': [1, 128, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block3/conv1': [1, 512, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block3/conv2': [1, 128, ?, ?] --> [1, 128, ?, ?]
[0402 21:41:23 @registry.py:90] 'group1/block3/conv3': [1, 128, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:23 @registry.py:90] 'group2/block0/conv1': [1, 512, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:23 @registry.py:90] 'group2/block0/conv2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:23 @registry.py:90] 'group2/block0/conv3': [1, 256, ?, ?] --> [1, 1024, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block0/convshortcut': [1, 512, ?, ?] --> [1, 1024, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block1/conv1': [1, 1024, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block1/conv2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block1/conv3': [1, 256, ?, ?] --> [1, 1024, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block2/conv1': [1, 1024, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block2/conv2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block2/conv3': [1, 256, ?, ?] --> [1, 1024, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block3/conv1': [1, 1024, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block3/conv2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block3/conv3': [1, 256, ?, ?] --> [1, 1024, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block4/conv1': [1, 1024, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block4/conv2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block4/conv3': [1, 256, ?, ?] --> [1, 1024, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block5/conv1': [1, 1024, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block5/conv2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:24 @registry.py:90] 'group2/block5/conv3': [1, 256, ?, ?] --> [1, 1024, ?, ?]
[0402 21:41:24 @registry.py:90] 'group3/block0/conv1': [1, 1024, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:24 @registry.py:90] 'group3/block0/conv2': [1, 512, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:24 @registry.py:90] 'group3/block0/conv3': [1, 512, ?, ?] --> [1, 2048, ?, ?]
[0402 21:41:24 @registry.py:90] 'group3/block0/convshortcut': [1, 1024, ?, ?] --> [1, 2048, ?, ?]
[0402 21:41:25 @registry.py:90] 'group3/block1/conv1': [1, 2048, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:25 @registry.py:90] 'group3/block1/conv2': [1, 512, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:25 @registry.py:90] 'group3/block1/conv3': [1, 512, ?, ?] --> [1, 2048, ?, ?]
[0402 21:41:25 @registry.py:90] 'group3/block2/conv1': [1, 2048, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:25 @registry.py:90] 'group3/block2/conv2': [1, 512, ?, ?] --> [1, 512, ?, ?]
[0402 21:41:25 @registry.py:90] 'group3/block2/conv3': [1, 512, ?, ?] --> [1, 2048, ?, ?]
[0402 21:41:25 @registry.py:80] 'fpn' input: [1, 256, ?, ?], [1, 512, ?, ?], [1, 1024, ?, ?], [1, 2048, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/lateral_1x1_c2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/lateral_1x1_c3': [1, 512, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/lateral_1x1_c4': [1, 1024, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/lateral_1x1_c5': [1, 2048, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/upsample_lat5': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/upsample_lat4': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/upsample_lat3': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/posthoc_3x3_p2': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/posthoc_3x3_p3': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/posthoc_3x3_p4': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/posthoc_3x3_p5': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'fpn/maxpool_p6': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:93] 'fpn' output: [1, 256, ?, ?], [1, 256, ?, ?], [1, 256, ?, ?], [1, 256, ?, ?], [1, 256, ?, ?]
[0402 21:41:25 @registry.py:80] 'rpn' input: [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'rpn/conv0': [1, 256, ?, ?] --> [1, 256, ?, ?]
[0402 21:41:25 @registry.py:90]   'rpn/class': [1, 256, ?, ?] --> [1, 3, ?, ?]
[0402 21:41:25 @registry.py:90]   'rpn/box': [1, 256, ?, ?] --> [1, 12, ?, ?]
[0402 21:41:25 @registry.py:93] 'rpn' output: [?, ?, 3], [?, ?, 3, 4]
[0402 21:41:27 @registry.py:80] 'fastrcnn' input: [?, 256, 7, 7]
[0402 21:41:27 @registry.py:90]   'fastrcnn/fc6': [?, 256, 7, 7] --> [?, 1024]
[0402 21:41:27 @registry.py:90]   'fastrcnn/fc7': [?, 1024] --> [?, 1024]
[0402 21:41:27 @registry.py:93] 'fastrcnn' output: [?, 1024]
[0402 21:41:27 @registry.py:80] 'fastrcnn/outputs' input: [?, 1024]
[0402 21:41:27 @registry.py:90]   'fastrcnn/outputs/class': [?, 1024] --> [?, 2]
[0402 21:41:27 @registry.py:90]   'fastrcnn/outputs/box': [?, 1024] --> [?, 8]
[0402 21:41:27 @registry.py:93] 'fastrcnn/outputs' output: [?, 2], [?, 2, 4]
[0402 21:41:28 @registry.py:80] 'maskrcnn' input: [?, 256, 14, 14]
[0402 21:41:28 @registry.py:90]   'maskrcnn/fcn0': [?, 256, 14, 14] --> [?, 256, 14, 14]
[0402 21:41:28 @registry.py:90]   'maskrcnn/fcn1': [?, 256, 14, 14] --> [?, 256, 14, 14]
[0402 21:41:28 @registry.py:90]   'maskrcnn/fcn2': [?, 256, 14, 14] --> [?, 256, 14, 14]
[0402 21:41:28 @registry.py:90]   'maskrcnn/fcn3': [?, 256, 14, 14] --> [?, 256, 14, 14]
[0402 21:41:28 @registry.py:90]   'maskrcnn/deconv': [?, 256, 14, 14] --> [?, 256, 28, 28]
[0402 21:41:28 @registry.py:90]   'maskrcnn/conv': [?, 256, 28, 28] --> [?, 1, 28, 28]
[0402 21:41:28 @registry.py:93] 'maskrcnn' output: [?, 1, 28, 28]
[0402 21:41:28 @regularize.py:97] regularize_cost() found 63 variables to regularize.
[0402 21:41:28 @regularize.py:21] The following tensors will be regularized: group1/block0/conv1/W:0, group1/block0/conv2/W:0, group1/block0/conv3/W:0, group1/block0/convshortcut/W:0, group1/block1/conv1/W:0, group1/block1/conv2/W:0, group1/block1/conv3/W:0, group1/block2/conv1/W:0, group1/block2/conv2/W:0, group1/block2/conv3/W:0, group1/block3/conv1/W:0, group1/block3/conv2/W:0, group1/block3/conv3/W:0, group2/block0/conv1/W:0, group2/block0/conv2/W:0, group2/block0/conv3/W:0, group2/block0/convshortcut/W:0, group2/block1/conv1/W:0, group2/block1/conv2/W:0, group2/block1/conv3/W:0, group2/block2/conv1/W:0, group2/block2/conv2/W:0, group2/block2/conv3/W:0, group2/block3/conv1/W:0, group2/block3/conv2/W:0, group2/block3/conv3/W:0, group2/block4/conv1/W:0, group2/block4/conv2/W:0, group2/block4/conv3/W:0, group2/block5/conv1/W:0, group2/block5/conv2/W:0, group2/block5/conv3/W:0, group3/block0/conv1/W:0, group3/block0/conv2/W:0, group3/block0/conv3/W:0, group3/block0/convshortcut/W:0, group3/block1/conv1/W:0, group3/block1/conv2/W:0, group3/block1/conv3/W:0, group3/block2/conv1/W:0, group3/block2/conv2/W:0, group3/block2/conv3/W:0, fpn/lateral_1x1_c2/W:0, fpn/lateral_1x1_c3/W:0, fpn/lateral_1x1_c4/W:0, fpn/lateral_1x1_c5/W:0, fpn/posthoc_3x3_p2/W:0, fpn/posthoc_3x3_p3/W:0, fpn/posthoc_3x3_p4/W:0, fpn/posthoc_3x3_p5/W:0, rpn/conv0/W:0, rpn/class/W:0, rpn/box/W:0, fastrcnn/fc6/W:0, fastrcnn/fc7/W:0, fastrcnn/outputs/class/W:0, fastrcnn/outputs/box/W:0, maskrcnn/fcn0/W:0, maskrcnn/fcn1/W:0, maskrcnn/fcn2/W:0, maskrcnn/fcn3/W:0, maskrcnn/deconv/W:0, maskrcnn/conv/W:0

```

Got the following error when I ran train.py

Traceback (most recent call last):
  File "./train.py", line 119, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/.local/lib/python3.6/site-packages/tensorpack/train/interface.py", line 89, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "/.local/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/.local/lib/python3.6/site-packages/tensorpack/train/tower.py", line 219, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/.local/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 212, in _setup_graph
    self.train_op, post_init_op = self._builder.build(grad_list, get_opt_fn)
  File "/.local/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 301, in build
    grad_and_vars, name='apply_grad_{}'.format(idx)))
  File "/.local/lib/python3.6/site-packages/tensorpack/tfutils/optimizer.py", line 214, in apply_gradients
    op = tf.cond(pred, update_grad, tf.no_op)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1396, in cond_for_tf_v2
    return cond(pred, true_fn=true_fn, false_fn=false_fn, strict=True, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 538, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1180, in cond
    return cond_v2.cond_v2(pred, true_fn, false_fn, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py", line 106, in cond_v2
    name=scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py", line 312, in _build_cond
    if_op, tensors = _run_as_function_for_tape_gradients(make_op, cond_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py", line 224, in _run_as_function_for_tape_gradients
    return _get_op_and_outputs(make_op())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/cond_v2.py", line 311, in make_op
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_functional_ops.py", line 401, in _if
    else_branch=else_branch, output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 438, in _apply_op_helper
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1608, in internal_convert_n_to_tensor
    ctx=ctx))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/profiler/trace.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor

### 3. What you expected, if not obvious.
FasterRCNN example was expected to train like it does under 1.15.4

### 4. Your environment:

2021-04-02 21:55:34.126131: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'tensorpack.tfutils.collect_env' found in sys.modules after import of package 'tensorpack.tfutils', but prior to execution of 'tensorpack.tfutils.collect_env'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
-----------------------  -------------------------------------------------------------------------------
sys.platform             linux
Python                   3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
Tensorpack               v0.11-2-g88530083-dirty @/.local/lib/python3.6/site-packages/tensorpack
Numpy                    1.19.5
TensorFlow               2.4.1/v2.4.0-49-g85c8b2a817f @/usr/local/lib/python3.6/dist-packages/tensorflow
TF Compiler Version      7.3.1 20180303
TF CUDA support          True
TF MKL support           False
TF XLA support           False
Nvidia Driver            /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.460.67
CUDA libs                /usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudart.so.11.0.221
CUDNN libs               /usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
TF compute capabilities  sm_35,sm_50,sm_60,sm_70,sm_75,80
TF built with CUDA       11.0
TF built with CUDNN      8
NCCL libs
CUDA_VISIBLE_DEVICES     Unspecified
GPU 0                    GeForce RTX 2080 SUPER
Free RAM                 61.24/62.57 GB
CPU Count                8
cv2                      4.5.1
msgpack                  1.0.2
python-prctl             True
-----------------------  -------------------------------------------------------------------------------
Detecting GPUs using TensorFlow:
2021-04-02 21:55:35.530501: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-02 21:55:35.531202: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-04-02 21:55:35.578428: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-02 21:55:35.579096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:04:00.0 name: GeForce RTX 2080 SUPER computeCapability: 7.5
coreClock: 1.845GHz coreCount: 48 deviceMemorySize: 7.79GiB deviceMemoryBandwidth: 462.00GiB/s
2021-04-02 21:55:35.579128: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-04-02 21:55:35.580922: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-04-02 21:55:35.581026: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-04-02 21:55:35.581836: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2021-04-02 21:55:35.582079: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2021-04-02 21:55:35.583933: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2021-04-02 21:55:35.584484: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2021-04-02 21:55:35.584623: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-04-02 21:55:35.584765: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-02 21:55:35.585547: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-02 21:55:35.586181: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
GPUs: /physical_device:GPU:0

**Comment by ppwwyyxx** [comment]
TF2 is not supported

**Comment by vijaygill** [comment]
@ppwwyyxx Ah sorry! I assumed from the commit messages that TF2 support has been added. Thanks for quick response.
