### ISSUE TITLE
Error when training.

### ISSUE THREAD

**Issue by herrickli** [tensorpack/tensorpack#1525]
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1)I want to train cascade-rcnn(resnet 101 fpn) with my own 8-category coco format dataset.

(2) I only change the class_names in examples/FasterRCNN/dataset/coc.py line 232 to my own custom class names.

(3) I use ImageNet-R101-AlignPadding.npz weight file.

(4) Here is the commond I run
```
python3 train.py --config BACKBONE.WEIGHTS=tensorpack/checkpoint/ImageNet-R101-AlignPadding.npz DATA.BASEDIR=/tensorpack/examples/FasterRCNN/dataset/coco-format MODE_MASK=False FPN.CASCADE=True BACKBONE.RESNET_NUM_BLOCKS=[3,4,23,3] TEST.RESULT_SCORE_THRESH=1e-4 PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800] TRAIN.LR_SCHEDULE=1x

```

### 2. What you observed:

(1) **I got this error:**
```
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    session_init = SmartInit(cfg.BACKBONE.WEIGHTS)
  File "/home/c/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/tfutils/sessinit.py", line 302, in SmartInit
    obj = dict(np.load(filename))
  File "/home/c/anaconda3/envs/tensorpack/lib/python3.7/site-packages/numpy/lib/npyio.py", line 250, in __getitem__
    magic = bytes.read(len(format.MAGIC_PREFIX))
  File "/home/c/anaconda3/envs/tensorpack/lib/python3.7/zipfile.py", line 930, in read
    data = self._read1(n)
  File "/home/c/anaconda3/envs/tensorpack/lib/python3.7/zipfile.py", line 1006, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -2 while decompressing data: inconsistent stream state

```
It seems the weight file is not right.

### 4. Your environment:

Paste the output of this command: `python -m tensorpack.tfutils.collect_env`
```
/home/c/anaconda3/envs/tensorpack/lib/python3.7/runpy.py:125: RuntimeWarning: 'tensorpack.tfutils.collect_env' found in sys.modules after import of package 'tensorpack.tfutils', but prior to execution of 'tensorpack.tfutils.collect_env'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
--------------------  ------------------------------------------------------------------------------------------------------
sys.platform          linux
Python                3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
Tensorpack            v0.11-4-g5845ead-dirty @/home/c/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack
Numpy                 1.20.1
TensorFlow            1.15.0/unknown @/home/c/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow
TF Compiler Version   5.4.0
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.460.56
CUDA libs             /usr/local/cuda-9.0/lib64/libcudart.so.9.0.176
CUDNN libs            /usr/local/cuda-9.0/lib64/libcudnn.so.7.6.4
TF built with CUDA    10.0
TF built with CUDNN   7.6
NCCL libs
CUDA_VISIBLE_DEVICES  Unspecified
GPU 0                 GeForce GTX 1080 Ti
Free RAM              27.96/31.34 GB
CPU Count             12
cv2                   4.5.1
msgpack               1.0.2
python-prctl          False
--------------------  ------------------------------------------------------------------------------------------------------
Detecting GPUs using TensorFlow:
2021-05-06 18:42:28.946296: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-05-06 18:42:28.983345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.645
pciBusID: 0000:03:00.0
2021-05-06 18:42:29.003897: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-05-06 18:42:29.182196: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-05-06 18:42:29.270158: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-05-06 18:42:29.315760: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-05-06 18:42:29.521632: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-05-06 18:42:29.625566: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-05-06 18:42:29.991765: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-05-06 18:42:29.993297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
GPUs: /physical_device:GPU:0
```

**Comment by ppwwyyxx** [comment]
You can check whether the weight file is correctly downloaded by the sha256 sum in the model zoo: http://models.tensorpack.com/

**Comment by herrickli** [comment]
@ppwwyyxx The weight file is correctly downloaded, sha245 sum is same. Error still exist as above.

**Comment by ppwwyyxx** [comment]
The file can be loaded here: https://colab.research.google.com/drive/1GXPHFO7YvyPTtq4ppJmFcFznRD9Dsu65#scrollTo=_YAfAGqDFI3y

If you'd like someone to investigate it, we'll need proof that the issue exists

**Comment by herrickli** [comment]
@ppwwyyxx Hi, After I changed a mechine, obove issue is disappered. But I meet a new error as follows:
```
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/interface.py", line 89, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/utils/argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/tower.py", line 219, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/trainers.py", line 211, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 228, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 123, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 117, in call_for_each_tower
    ret.append(func())
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/tower.py", line 276, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/tower.py", line 250, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/tfutils/tower.py", line 294, in __call__
    output = self._tower_fn(*args)
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py", line 73, in build_graph
    head_losses = self.roi_heads(image, features, proposals, targets)
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py", line 287, in roi_heads
    (gt_boxes, gt_labels), image_shape2d, cfg.DATA.NUM_CATEGORY)
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 46, in __init__
    B1_proposal = self.match_box_with_gt(B1, ious[1])
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 92, in match_box_with_gt
    lambda: tf.zeros([tf.shape(iou)[0]], dtype=tf.int64))
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1235, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1061, in BuildCondBranch
    original_result = fn()
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 92, in <lambda>
    lambda: tf.zeros([tf.shape(iou)[0]], dtype=tf.int64))
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2338, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2295, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/cond/strided_slice:0) to a numpy array.
(tensorpack) licheng@amax:/data/lc/tensorpack/examples/FasterRCNN$ python train.py --config BACKBONE.WEIGHTS=/data/lc/tensorpack/checkpoint/ImageNet-R101-AlignPadding.npz DATA.BASEDIR=/data/lc/tensorpack/examples/FasterRCNN/dataset/coco-format MODE_MASK=False FPN.CASCADE=True BACKBONE.RESNET_NUM_BLOCKS=[3,4,23,3] TEST.RESULT_SCORE_THRESH=1e-4 PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800] TRAIN.LR_SCHEDULE=1x
```
It only happened if I add `FPN.CASCADE=True` option, means I successful train Faster RCNN, but Failed to train Cascade RCNN. How can I solve this error. Thanks for kindly reply.

**Comment by herrickli** [comment]
@ppwwyyxx Hi, After I changed a mechine, obove issue is disappered. But I meet a new error as follows:
```
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/interface.py", line 89, in launch_train_with_config
    model.build_graph, model.get_optimizer)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/utils/argtools.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/tower.py", line 219, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/trainers.py", line 211, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 228, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 123, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/graph_builder/training.py", line 117, in call_for_each_tower
    ret.append(func())
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/tower.py", line 276, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/train/tower.py", line 250, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorpack/tfutils/tower.py", line 294, in __call__
    output = self._tower_fn(*args)
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py", line 73, in build_graph
    head_losses = self.roi_heads(image, features, proposals, targets)
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py", line 287, in roi_heads
    (gt_boxes, gt_labels), image_shape2d, cfg.DATA.NUM_CATEGORY)
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 46, in __init__
    B1_proposal = self.match_box_with_gt(B1, ious[1])
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 92, in match_box_with_gt
    lambda: tf.zeros([tf.shape(iou)[0]], dtype=tf.int64))
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1235, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1061, in BuildCondBranch
    original_result = fn()
  File "/data/lc/tensorpack/examples/FasterRCNN/modeling/model_cascade.py", line 92, in <lambda>
    lambda: tf.zeros([tf.shape(iou)[0]], dtype=tf.int64))
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2338, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py", line 2295, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "/home/licheng/anaconda3/envs/tensorpack/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 736, in __array__
    " array.".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (tower0/cascade_rcnn_stage2/match_box_with_gt_0.6/cond/strided_slice:0) to a numpy array.
(tensorpack) licheng@amax:/data/lc/tensorpack/examples/FasterRCNN$ python train.py --config BACKBONE.WEIGHTS=/data/lc/tensorpack/checkpoint/ImageNet-R101-AlignPadding.npz DATA.BASEDIR=/data/lc/tensorpack/examples/FasterRCNN/dataset/coco-format MODE_MASK=False FPN.CASCADE=True BACKBONE.RESNET_NUM_BLOCKS=[3,4,23,3] TEST.RESULT_SCORE_THRESH=1e-4 PREPROC.TRAIN_SHORT_EDGE_SIZE=[640,800] TRAIN.LR_SCHEDULE=1x
```
It only happened if I add `FPN.CASCADE=True` option, means I successful train Faster RCNN, but Failed to train Cascade RCNN. How can I solve this error. Thanks for kindly reply.

**Comment by ppwwyyxx** [comment]
this issue about cascade R-CNN should be fixed now by the above commit
