### ISSUE TITLE
Saving lmdb file using LMDBSerializer.save leads to lmdb with one entry

### ISSUE THREAD

**Issue by ivana-13** [tensorpack/tensorpack#1548]
### 1. What you did:
 I am trying to replicate a model from https://github.com/e-bug/volta/tree/183ae3c00afd0b0ae42cb3373ea6b45cb6e3c67e where for pretraining they use Conceptual Captions dataset. This is too large for me to pretrained on, so I decided to use MS-COCO. I editted the process of preparation of data for COCO (https://github.com/e-bug/volta/blob/183ae3c00afd0b0ae42cb3373ea6b45cb6e3c67e/data/conceptual_captions/preprocess_cc_train.py ) which uses tensorpack.dataflow. I tired to follow the lead in Save and Load a Single-File DataFlow and so I created this code for saving lstm file. 

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "3"
import time
import numpy as np
import tensorpack.dataflow as td
import json
import csv
FIELDNAMES = ["img_id", "img_h", "img_w", "objects_id", "objects_conf",
              "attrs_id", "attrs_conf", "num_boxes", "boxes", "features",
              "cls_prob", "attrs", "classes"]
import sys
import pandas as pd
import zlib
import base64

maxInt = sys.maxsize

while True:
    # decrease the maxInt value by factor 10 
    # as long as the OverflowError occurs.

    try:
        csv.field_size_limit(maxInt)
        break
    except OverflowError:
        maxInt = int(maxInt/10)

class Conceptual_Caption(td.DataFlow):
    """
    """
    def __init__(self, corpus_path, shuffle=False):
        """
        Same as in :class:`ILSVRC12`.
        """
        self.shuffle = shuffle
        self.name = os.path.join(corpus_path, 'resnet101_faster_rcnn_genome_imgfeats/train2014_obj36-36.tsv')
        self.infiles = [self.name]
        self.counts = []

        self.captions = {}
        df = json.load(open(os.path.join(corpus_path, 'annotations/train_ann.jsonl')))

        for annotation in df["annotations"]:
            caption = annotation['sentences'][0]
            image_id = annotation['id']
            self.captions[image_id] = caption
        

        with open(os.path.join(corpus_path, 'annotations/train_ann.jsonl')) as f:
            captions = json.load(f)
        self.num_caps = len(captions)

    def __len__(self):
        return self.num_caps

    def __iter__(self):
        count = 0
        for infile in self.infiles:
            with open(infile) as tsv_in_file:
                reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames=FIELDNAMES)
                for item in reader: 
                    count += 1                   
                    image_id = item['img_id']
                    img_id = int(item['img_id'].split('_')[-1])
                    image_h = item['img_h']
                    image_w = item['img_w']
                    num_boxes = item['num_boxes']
                    boxes = np.frombuffer(base64.b64decode(item['boxes']), dtype=np.float32).reshape(int(num_boxes), 4)
                    features = np.frombuffer(base64.b64decode(item['features']), dtype=np.float32).reshape(int(num_boxes), 2048)
                    cls_prob = np.frombuffer(base64.b64decode(item['cls_prob']), dtype=np.float32).reshape(int(num_boxes), 1601)
                    objects_id = np.frombuffer(base64.b64decode(item['objects_id']), dtype=np.int64)
                    objects_conf = np.frombuffer(base64.b64decode(item['objects_conf']), dtype=np.float32)
                    attrs_id = np.frombuffer(base64.b64decode(item['attrs_id']), dtype=np.int64)
                    attrs_conf = np.frombuffer(base64.b64decode(item['attrs_conf']), dtype=np.float32)
                    # cls_scores = np.frombuffer(base64.b64decode(item['classes']), dtype=np.float32).reshape(int(num_boxes), -1)
                    attr_scores = np.frombuffer(base64.b64decode(item['attrs']), dtype=np.float32).reshape(int(num_boxes), -1)
                    caption = self.captions[img_id]

                    yield [features, cls_prob, objects_id, objects_conf, attrs_id, attrs_conf, attr_scores, boxes, num_boxes, image_h, image_w, image_id, caption]


if __name__ == '__main__':
    corpus_path = sys.argv[1]
    ds = Conceptual_Caption(corpus_path)
    ds1 = td.PrefetchDataZMQ(ds, 16)
    td.LMDBSerializer.save(ds1, os.path.join(corpus_path, 'imgfeats/volta/training_feat_all.lmdb'))
```

### 2. What you observed:

The code runs very quickly (less than second?), I even think that it is too quick as the tsv file has around 80GB. Then when I try to load the lstm file it only has 1 entry. I use this code for loading

```
...
ds = td.LMDBSerializer.load(lmdb_file, shuffle=False)
        self.num_dataset = len(ds)
        ds = td.LocallyShuffleData(ds, cache)
ds = td.PrefetchData(ds, 5000, 1)
        ds = td.MapData(ds, preprocess_function)
        ds = td.PrefetchDataZMQ(ds, num_workers)
        self.ds = td.BatchData(ds, batch_size)
        self.ds.reset_state()
...
```

 The output in console for saving lstm and loading lstm are:

```
python data/conceptual_captions/preprocess_cc_train.py datasets/mscoco
[0129 18:11:15 @argtools.py:138] WRN Starting a process with 'fork' method is efficient but not safe and may cause deadlock or crash.Use 'forkserver' or 'spawn' method instead if you run into such issues.See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods on how to set them.
[0129 18:11:15 @argtools.py:138] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.
  0%|                                                                                                                                                                              |0/1[00:00<?,?it/s][0129 18:11:15 @serialize.py:103] Flushing database ...
100%|######################################################################################################################################################################|1/1[00:00<00:00,36.00it/s]
MultiProcessRunnerZMQ successfully cleaned-up.


python train_concap.py --config_file config/MMT_COCO.json --train_batch_size 128 --gradient_accumulation_steps 1 --max_seq_length 38  --learning_rate 1e-4 --adam_epsilon 1e-6 --adam_betas 0.9 0.999 --weight_decay 0.01 --warmup_proportion 0.1 --clip_grad_norm 5.0 --objective 1 --annotations_path datasets/mscoco/annotations --features_path datasets/mscoco/imgfeats/volta --output_dir checkpoints/conceptual_captions/MMT_COCO --logdir logs/conceptual_captions --num_train_epochs 10 
01/29/2022 18:11:32 - INFO - __main__ -   device: cuda n_gpu: 1, distributed training: False
Loading from datasets/mscoco/imgfeats/volta/training_feat_all.lmdb
[0129 18:11:37 @format.py:91] Found 1 entries in datasets/mscoco/imgfeats/volta/training_feat_all.lmdb
Traceback (most recent call last):
  File "train_concap.py", line 362, in <module>
    main()
  File "train_concap.py", line 163, in main
    train_dataset = ConceptCapLoaderTrain(args.annotations_path, args.features_path, tokenizer,
  File "/home/ivana_benova/replication_study/volta/datasets/concept_cap_dataset.py", line 221, in __init__
    self.ds = td.BatchData(ds, batch_size)
  File "/opt/anacondas/anaconda3/envs/phd-benova/lib/python3.8/site-packages/tensorpack/dataflow/common.py", line 98, in __init__
    assert batch_size <= len(ds)
AssertionError
```

### 3. What you expected, if not obvious.

I want to create lmdb file which obviously has more than 1 entry. MS-COCO has hundreds of captions.

### 4. Your environment:
sys.platform             linux
Python                   3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
Tensorpack               v0.11-0-gdb541e8e @/opt/anacondas/anaconda3/envs/phd-benova/lib/python3.8/site-packages/tensorpack
Numpy                    1.21.2
TensorFlow               2.7.0/v2.7.0-rc1-69-gc256c071bb2 @/opt/anacondas/anaconda3/envs/phd-benova/lib/python3.8/site-packages/tensorflow
TF Compiler Version      7.3.1 20180303
TF CUDA support          True
TF MKL support           False
TF XLA support           False
Nvidia Driver            /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.86
CUDA libs                /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.4.148
CUDNN libs
TF compute capabilities  sm_35,sm_50,sm_60,sm_70,sm_75,80
TF built with CUDA       11.2
TF built with CUDNN      8
NCCL libs                /usr/lib/x86_64-linux-gnu/libnccl.so.2.11.4
CUDA_VISIBLE_DEVICES     Unspecified
GPU 0,1,2,3              NVIDIA GeForce RTX 3090
Free RAM                 27.56/125.66 GB
CPU Count                64
msgpack                  1.0.3
python-prctl             False

The output of this command: `python -m tensorpack.tfutils.collect_env`

I dont know what am I doing wrong. please help me solve this. Thank you.

**Comment by ivana-13** [comment]
Okey, I think I solve it myself. The problem was in 
```
def __len__(self):
        return self.num_caps
```
Which I thought was not that important so I didnt pay enough attention when working on self.num_caps and all of my annotations where list of lists so the len was 1. Therfore it always processed only one input. Now it is running and I can see the progress x out of 113287 inputs which is more likely when working with MS-COCO.
