### ISSUE TITLE
ops are assigned to gpu when run DistributedTrainerParameterServer 

### ISSUE THREAD

**Issue by yogurfrul** [tensorpack/tensorpack#782]
I want to run   DistributedTrainerParameterServer example , so I modify thr examples/basics/mnist-convnet.py as below:

    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(gpus=args.gpu.split(",")))
===>
 cluster = tf.train.ClusterSpec({"ps":["localhost:2222"], "worker":["localhost:2223"]})
    server = tf.train.Server(cluster,
                             job_name=args.job_name,
                             task_index=int(args.task_index))
    launch_train_with_config(config, DistributedTrainerParameterServer([int(x) for x in args.gpu.split(",")], server))

and run it in two window:
python distributed-mnist-convnet.py --gpu=0 --job_name=ps --task_index=0
python distributed-mnist-convnet.py --gpu=0 --job_name=worker --task_index=0

then  I got the error:

`
[0606 09:37:48 @summary.py:75] Summarizing collection 'summaries' of size 19.
[0606 09:37:48 @base.py:197] Creating the session ...
2018-06-06 09:37:48.721536: I tensorflow/core/distributed_runtime/master_session.cc:1024] Start master session 840fd3c8777697e2 with config:
Traceback (most recent call last):
  File "distributed-mnist-convnet.py", line 145, in <module>
    launch_train_with_config(config, DistributedTrainerParameterServer([int(x) for x in args.gpu.split(",")], server))
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/interface.py", line 90, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/base.py", line 301, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/base.py", line 272, in train
    self.initialize(session_creator, session_init)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/trainers.py", line 199, in initialize
    get_distributed_session_creator(self.server), session_init)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/base.py", line 200, in initialize
    self.sess = session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/tfutils/distributed.py", line 40, in create_session
    return sm.prepare_session(master=server.target, init_op=init_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'tower0/lr': Could not satisfy explicit device specification '/job:worker/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Registered kernels:
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]

         [[Node: tower0/lr = ScalarSummary[T=DT_FLOAT, _device="/job:worker/task:0/device:GPU:0"](tower0/lr/tags, tower0/learning_rate)]]

`

**Comment by ppwwyyxx** [comment]
This is a TensorFlow error that ops cannot be placed on GPU.
You need to initialize the server with a tensorflow sessionconfig, which enables soft placement.
In tensorpack, you can just pass `config=get_default_sess_config()` to `tf.Server`.

**Comment by ppwwyyxx** [comment]
Btw, as mentioned in the docs, you're not recommended to use TensorFlow's native distributed trainer because they are not as efficient as HorovodTrainer.

**Comment by yogurfrul** [comment]
it works when I pass config=get_default_sess_config() to tf.Server

Then I got error  Master init: Unavailabel: OS Error when I run worker before ps,while it's ok when I run ps firstly.

[0608 05:55:08 @base.py:197] Creating the session ...
2018-06-08 05:55:09.075000: E tensorflow/core/distributed_runtime/master.cc:269] Master init: Unavailable: OS Error
2018-06-08 05:55:09.147089: E tensorflow/core/distributed_runtime/master.cc:269] Master init: Unavailable: OS Error
Traceback (most recent call last):
  File "distributed-ps-mnist-convnet.py", line 145, in <module>
    launch_train_with_config(config, DistributedTrainerParameterServer([int(x) for x in args.gpu.split(",")], server))
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/interface.py", line 90, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/base.py", line 302, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/base.py", line 273, in train
    self.initialize(session_creator, session_init)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/trainers.py", line 199, in initialize
    get_distributed_session_creator(self.server), session_init)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/train/base.py", line 200, in initialize
    self.sess = session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorpack-0.8.5-py2.7.egg/tensorpack/tfutils/distributed.py", line 40, in create_session
    return sm.prepare_session(master=server.target, init_op=init_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnavailableError: OS Error

**Comment by ppwwyyxx** [comment]
Looks like a tensorflow bug: https://github.com/tensorflow/benchmarks/issues/165.
And Google's team also suggests you to use horovod for the moment.
Horovod trainer also has better support in tensorpack than the native trainers, e.g.: https://github.com/tensorpack/benchmarks/tree/master/ResNet-Horovod
