### ISSUE TITLE
TF model pruning APIs and tensorpack

### ISSUE THREAD

**Issue by asit03in** [tensorpack/tensorpack#784]
Issue: Usage Questions

1. What you did:
I am trying to use TF model pruning API through tensorpack. For this, I did the following:
(a) modified tensorpack's conv2d function to include the weight pruning "apply_mask" functionality. For this, I simply added a "masking" variable which is set if I want to turn on the pruning functionality. See line 120-165 (line 157 is where this is done). File attached.
(b) Included the other pruning APIs in the trainer side of code as tensorpack callbacks -- see PruningCallback in sparse-cifar-convnet.py. It is a mod of cifar-convnet.py is examples/basics.

2. What you observed, e.g. the entire log:
Log file is attached. The problem is that the sparsity summaries report 0 sparsity which says that pruning is not taking place.

```
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv1.1//mask_0/sparsity: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv1.1//threshold/threshold: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv1.2//mask_0/sparsity: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv1.2//threshold/threshold: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv2.1//mask_0/sparsity: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv2.1//threshold/threshold: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv2.2//mask_0/sparsity: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv2.2//threshold/threshold: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv3.1//mask_0/sparsity: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv3.1//threshold/threshold: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv3.2//mask_0/sparsity: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/conv3.2//threshold/threshold: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/last_mask_update_step: 0
[0607 14:37:29 @monitor.py:433] PruningCallback/cifar10_pruning_summaries/sparsity: 0.43051
```

3. What you expected, if not obvious.
Pruning was expected to happen, but its not when looking at the summaries in the log file. The `last_mask_update_step: 0` tells me that mask is never updated. So, may be something to do with the way I wrote the callback

4. Your environment:
	+ Python version: 2.7
	+ TF version: ('v1.8.0-0-g93bc2e2072', '1.8.0')
	+ Tensorpack version:  0.8.5
        + Run command: python sparse-cifar-convnet.py --gpu 0

Files: (I appended .txt to all file names to upload here)
[conv2d.py.txt](https://github.com/tensorpack/tensorpack/files/2082218/conv2d.py.txt)
[graph-0607-143646.meta.txt](https://github.com/tensorpack/tensorpack/files/2082219/graph-0607-143646.meta.txt)
[log.log.txt](https://github.com/tensorpack/tensorpack/files/2082220/log.log.txt)
[sparse-cifar-convnet.py.txt](https://github.com/tensorpack/tensorpack/files/2082221/sparse-cifar-convnet.py.txt)

Question: How to best/correctly integrate the pruning APIs to use with tensorpack and what is currently wrong with the Pruning Callback?

**Comment by ppwwyyxx** [comment]
From the docs https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/model_pruning it looks like you want to run extra ops after each iteration. 

`SessionRunArgs` is only for `before_run` and `after_run`, to provided an interface to tensorflow's `SessionRunHooks`. It is for running extra ops __along with__ each iteration.

`trigger_step` is for running anything after each iteration. It is just a plain python function so you need `self.trainer.sess.run(mask_update_op)`.

**Comment by asit03in** [comment]
Thanks!
Things work for me with your edits. 

The baseline network was getting to 90% validation accuracy.
With 90% sparsity I am getting very close to it (89.4%).

Attached is the training script and log file with the results.

[log.log.txt](https://github.com/tensorpack/tensorpack/files/2082449/log.log.txt)
[sparse-cifar-convnet.py.txt](https://github.com/tensorpack/tensorpack/files/2082450/sparse-cifar-convnet.py.txt)

**Comment by asit03in** [comment]
A small note.
Things work if I use `self.trainer.sess.run(self.mask_update_op)`
If I use, `self.mask_update_op.run()`, I get the following error.

```
2018-06-07 17:04:47.019623: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "sparse-cifar-convnet.py", line 176, in <module>
    launch_train_with_config(config, trainer)
  File "/home/akmishr1/sparse_lowprecision/tensorpack/tensorpack/train/interface.py", line 90, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
[0607 17:04:47 @input_source.py:148] EnqueueThread QueueInput/input_queue Exited.
  File "/home/akmishr1/sparse_lowprecision/tensorpack/tensorpack/train/base.py", line 301, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/akmishr1/sparse_lowprecision/tensorpack/tensorpack/train/base.py", line 273, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/akmishr1/sparse_lowprecision/tensorpack/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/akmishr1/sparse_lowprecision/tensorpack/tensorpack/train/base.py", line 239, in main_loop
    self._callbacks.trigger_step()
  File "/home/akmishr1/sparse_lowprecision/tensorpack/tensorpack/callbacks/group.py", line 85, in trigger_step
    cb.trigger_step()
  File "/home/akmishr1/sparse_lowprecision/tensorpack/tensorpack/callbacks/base.py", line 138, in trigger_step
    self._trigger_step()
  File "sparse-cifar-convnet.py", line 101, in _trigger_step
    self.mask_update_op.run()
AttributeError: 'Tensor' object has no attribute 'run'
```

Closing this thread for now.

**Comment by ppwwyyxx** [comment]
Ah, if mask_update_op a tensor, then it should be `.eval()` instead of `.run()`.
