### ISSUE TITLE
AlexNet-Dorefa Train error

### ISSUE THREAD

**Issue by xuke225** [tensorpack/tensorpack#793]
test tensorpack example alexnet-dorefa.py
`python alexnet-dorefa.py --dorefa 8,8,32 --data /mnt/temp/ --gpu 2,3`
just Tain 1 epoch and error as follow:
```sh

[0616 17:34:42 @input_source.py:513] Pre-filling StagingArea ...
[0616 17:34:42 @input_source.py:517] 1 element was put into StagingArea.
100%|###########################################################################################################################################################################################|5000/5000[17:53<00:00, 1.38it/s]
[0616 17:52:35 @base.py:252] Epoch 1 (global_step 5000) finished, time:17 minutes 53 seconds.
[0616 17:52:35 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
 19%|###################################4                                                                                                                                                          |73/391[00:05<00:22,14.38it/s]Exception in thread Thread-7:
Traceback (most recent call last):
  File "/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "tensorflow/tensorpack/tensorpack/dataflow/parallel_map.py", line 125, in run
    obj = self.func(dp)
  File "tensorflow/tensorpack/examples/DoReFa-Net/imagenet_utils.py", line 114, in mapf
    im = aug.augment(im)
  File "tensorflow/tensorpack/tensorpack/dataflow/imgaug/base.py", line 39, in augment
    d, params = self._augment_return_params(d)
  File "tensorflow/tensorpack/tensorpack/dataflow/imgaug/base.py", line 151, in _augment_return_params
    check_dtype(img)
  File "tensorflow/tensorpack/tensorpack/dataflow/image.py", line 17, in check_dtype
    if isinstance(img.dtype, np.integer):
AttributeError: 'NoneType' object has no attribute 'dtype'

 42%|################################################################################2                                                                                                            |166/391[00:29<00:16,13.99it/s]

```
After stooping at 42% on response

**Comment by ppwwyyxx** [comment]
That means some images cannot be read. You may have a corrupted dataset

**Comment by xuke225** [comment]
It is indeed this reason，Thanks a lot!
