### ISSUE TITLE
Problem when training DiscoGAN

### ISSUE THREAD

**Issue by taneslle** [tensorpack/tensorpack#801]
I wrote a style transfer model according to _DiscoGAN-CelebA.py_ in tensorpack/examples/GAN/, but when I trained it, there was a TypeError said 

> Traceback (most recent call last):
  File "train.py", line 267, in <module>
    QueueInput(data), model, d_period=3).train_with_defaults(
  File "/home/yinsixing/TJ/unetgan_tp/GAN.py", line 117, in __init__
    cbs = input.setup(model.get_inputs_desc())
  File "/home/yinsixing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorpack/graph_builder/model_desc.py", line 105, in get_inputs_desc
    inputs = self.inputs()
  **File "train.py", line 51, in inputs
    return [tf.placeholder(tf.float32, (None, cfg.crop_size, cfg.crop_size, 3), 'celeba'), tf.placeholder(tf.float32, (None, cfg.crop_size, cfg.crop_size, 1), 'sketch')]**
  File "/home/yinsixing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1599, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/yinsixing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3087, in _placeholder
    shape = _execute.make_shape(shape, "shape")
  File "/home/yinsixing/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/eager/execute.py", line 146, in make_shape
    raise TypeError("Error converting %s to a TensorShape: %s." % (arg_name, e))
TypeError: Error converting shape to a TensorShape: int() argument must be a string, a bytes-like object or a number, not 'list'.

but the bold line is just code I copied from line 38 and 39 in [_DiscoGAN-CelebA.py_](https://github.com/tensorpack/tensorpack/blob/e9fa7eb6f95547b4ec2c496d75a504d110b7b60a/examples/GAN/DiscoGAN-CelebA.py#L38) , so I was wondering the problem is from my tensorpack version or my other codes?

**Comment by ppwwyyxx** [comment]
If the example runs fine it's probably unrelated to tensorpack.
Please check that `cfg.crop_size` is an integer.

**Comment by taneslle** [comment]
Yes, I just tried the example and it runs fine, and `cfg.crop_size` is an int, I'll check my other codes.
Thanks a lot.

**Comment by ppwwyyxx** [comment]
```
╰─$python3 -c 'import tensorflow as tf; tf.placeholder(tf.float32, (None, [32], 32, 1), "abc")'
Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 141, in make_shape                                                                                  
    shape = tensor_shape.as_shape(v)
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 946, in as_shape                                                                           
    return TensorShape(shape)
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 541, in __init__                                                                           
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 541, in <listcomp>                                                                         
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 482, in as_dimension                                                                       
    return Dimension(value)
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 37, in __init__                                                                            
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1734, in placeholder                                                                                
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4922, in placeholder                                                                            
    shape = _execute.make_shape(shape, "shape")
  File "/home/XXX/.local/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 143, in make_shape                                                                                  
    raise TypeError("Error converting %s to a TensorShape: %s." % (arg_name, e))
TypeError: Error converting shape to a TensorShape: int() argument must be a string, a bytes-like object or a number, not 'list'. 
```
I seriously doubt that..

**Comment by ivy94419** [comment]
@ppwwyyxx Have you solve this problems? I encounter a similar issues..... Waiting for your answers. Thank you very much!

**Comment by ppwwyyxx** [comment]
I did not see any tensorpack issue in this thread.
If you meet unexpected problems, please post details according to the [issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE.md).
