### ISSUE TITLE
Assertion error while trying to train the HED pretrained model.

### ISSUE THREAD

**Issue by h44rd** [tensorpack/tensorpack#805]
After running the following command ` ./hed.py --load HED_pretrained_bsds.npz --gpu 0` I get the following error:
```
./hed.py --load HED_pretrained_bsds.npz --gpu 0
[0628 14:02:40 @logger.py:109] WRN Log directory train_log/hed exists! Use 'd' to delete it. 
[0628 14:02:40 @logger.py:112] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):d
[0628 14:02:41 @logger.py:74] Argv: ./hed.py --load HED_pretrained_bsds.npz --gpu 0
[0628 14:02:41 @fs.py:88] WRN Env var $TENSORPACK_DATASET not set, using /home/phaard/tensorpack_data for datasets.
[0628 14:02:44 @param.py:194] Use train_log/hed/hyper.txt to set hyperparam: 'learning_rate'.
[0628 14:02:44 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0628 14:02:44 @input_source.py:195] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0628 14:02:44 @training.py:113] Building graph for training tower 0 ...
[0628 14:02:44 @registry.py:121] conv1_1 input: [None, None, None, 3]
[0628 14:02:44 @registry.py:129] conv1_1 output: [None, None, None, 64]
[0628 14:02:44 @registry.py:121] conv1_2 input: [None, None, None, 64]
[0628 14:02:44 @registry.py:129] conv1_2 output: [None, None, None, 64]
[0628 14:02:44 @registry.py:121] branch1/convfc input: [None, None, None, 64]
[0628 14:02:44 @registry.py:129] branch1/convfc output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] pool1 input: [None, None, None, 64]
[0628 14:02:44 @registry.py:129] pool1 output: [None, None, None, 64]
[0628 14:02:44 @registry.py:121] conv2_1 input: [None, None, None, 64]
[0628 14:02:44 @registry.py:129] conv2_1 output: [None, None, None, 128]
[0628 14:02:44 @registry.py:121] conv2_2 input: [None, None, None, 128]
[0628 14:02:44 @registry.py:129] conv2_2 output: [None, None, None, 128]
[0628 14:02:44 @registry.py:121] branch2/convfc input: [None, None, None, 128]
[0628 14:02:44 @registry.py:129] branch2/convfc output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch2/upsample2 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch2/upsample2 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] pool2 input: [None, None, None, 128]
[0628 14:02:44 @registry.py:129] pool2 output: [None, None, None, 128]
[0628 14:02:44 @registry.py:121] conv3_1 input: [None, None, None, 128]
[0628 14:02:44 @registry.py:129] conv3_1 output: [None, None, None, 256]
[0628 14:02:44 @registry.py:121] conv3_2 input: [None, None, None, 256]
[0628 14:02:44 @registry.py:129] conv3_2 output: [None, None, None, 256]
[0628 14:02:44 @registry.py:121] conv3_3 input: [None, None, None, 256]
[0628 14:02:44 @registry.py:129] conv3_3 output: [None, None, None, 256]
[0628 14:02:44 @registry.py:121] branch3/convfc input: [None, None, None, 256]
[0628 14:02:44 @registry.py:129] branch3/convfc output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch3/upsample4 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch3/upsample4 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch3/upsample2 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch3/upsample2 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] pool3 input: [None, None, None, 256]
[0628 14:02:44 @registry.py:129] pool3 output: [None, None, None, 256]
[0628 14:02:44 @registry.py:121] conv4_1 input: [None, None, None, 256]
[0628 14:02:44 @registry.py:129] conv4_1 output: [None, None, None, 512]
[0628 14:02:44 @registry.py:121] conv4_2 input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] conv4_2 output: [None, None, None, 512]
[0628 14:02:44 @registry.py:121] conv4_3 input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] conv4_3 output: [None, None, None, 512]
[0628 14:02:44 @registry.py:121] branch4/convfc input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] branch4/convfc output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch4/upsample8 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch4/upsample8 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch4/upsample4 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch4/upsample4 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch4/upsample2 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch4/upsample2 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] pool4 input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] pool4 output: [None, None, None, 512]
[0628 14:02:44 @registry.py:121] conv5_1 input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] conv5_1 output: [None, None, None, 512]
[0628 14:02:44 @registry.py:121] conv5_2 input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] conv5_2 output: [None, None, None, 512]
[0628 14:02:44 @registry.py:121] conv5_3 input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] conv5_3 output: [None, None, None, 512]
[0628 14:02:44 @registry.py:121] branch5/convfc input: [None, None, None, 512]
[0628 14:02:44 @registry.py:129] branch5/convfc output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch5/upsample16 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch5/upsample16 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch5/upsample8 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch5/upsample8 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch5/upsample4 input: [None, None, None, 1]
[0628 14:02:44 @registry.py:129] branch5/upsample4 output: [None, None, None, 1]
[0628 14:02:44 @registry.py:121] branch5/upsample2 input: [None, None, None, 1]
[0628 14:02:45 @registry.py:129] branch5/upsample2 output: [None, None, None, 1]
[0628 14:02:45 @registry.py:121] convfcweight input: [None, None, None, 5]
[0628 14:02:45 @registry.py:129] convfcweight output: [None, None, None, 1]
[0628 14:02:45 @regularize.py:88] regularize_cost() found 19 variables to regularize.
[0628 14:02:45 @regularize.py:19] The following tensors will be regularized: conv1_1/W:0, conv1_2/W:0, branch1/convfc/W:0, conv2_1/W:0, conv2_2/W:0, branch2/convfc/W:0, conv3_1/W:0, conv3_2/W:0, conv3_3/W:0, branch3/convfc/W:0, conv4_1/W:0, conv4_2/W:0, conv4_3/W:0, branch4/convfc/W:0, conv5_1/W:0, conv5_2/W:0, conv5_3/W:0, branch5/convfc/W:0, convfcweight/W:0
Traceback (most recent call last):
  File "./hed.py", line 259, in <module>
    SyncMultiGPUTrainer(max(get_nr_gpu(), 1)))
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/interface.py", line 81, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/tower.py", line 173, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/trainers.py", line 91, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 161, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 118, in build_on_towers
    ret.append(func())
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/tower.py", line 200, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/tfutils/tower.py", line 255, in __call__
    output = self._tower_fn(*args)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 235, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "./hed.py", line 118, in build_graph
    add_moving_summary(costs + [wrong, total_cost])
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/tfutils/summary.py", line 232, in add_moving_summary
    assert isinstance(x, (tf.Tensor, tf.Variable)), x
AssertionError: [<tf.Tensor 'tower0/xentropy1:0' shape=() dtype=float32>, <tf.Tensor 'tower0/xentropy2:0' shape=() dtype=float32>, <tf.Tensor 'tower0/xentropy3:0' shape=() dtype=float32>, <tf.Tensor 'tower0/xentropy4:0' shape=() dtype=float32>, <tf.Tensor 'tower0/xentropy5:0' shape=() dtype=float32>, <tf.Tensor 'tower0/xentropy6:0' shape=() dtype=float32>, <tf.Tensor 'tower0/wd_cost:0' shape=() dtype=float32>, <tf.Tensor 'tower0/train_error:0' shape=() dtype=float32>, <tf.Tensor 'tower0/cost:0' shape=() dtype=float32>]

```

My python version is 2.7 
Cudnn version: 6.0

**Comment by ppwwyyxx** [comment]
Oops. That's a deprecated usage of `add_moving_summary`.

**Comment by h44rd** [comment]
Thank you for the quick reply! What should I use instead? I could make the change in the repo too.
