### ISSUE TITLE
Error in the BSDS500 dataloader

### ISSUE THREAD

**Issue by h44rd** [tensorpack/tensorpack#806]
Hello!

I ran `python -m tensorpack.dataflow.dataset.bsds500` on python 2.7 and got the following error:

```
[0702 11:30:58 @fs.py:88] WRN Env var $TENSORPACK_DATASET not set, using ~/tensorpack_data for datasets.
Traceback (most recent call last):
  File "~/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "~/anaconda2/envs/tensorflow/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "~/EdgeDet/tensorpack/tensorpack/dataflow/dataset/bsds500.py", line 98, in <module>
    for k in a.get_data():
  File "~/EdgeDet/tensorpack/tensorpack/dataflow/dataset/bsds500.py", line 84, in get_data
    self.rng.shuffle(idxs)
AttributeError: 'BSDS500' object has no attribute 'rng'

```
Any help would be appreciated.

Thanks!

**Comment by ppwwyyxx** [comment]
It's not expected to be run like that. And there is a small error in the `__main__` part of the file  (http://tensorpack.readthedocs.io/tutorial/dataflow.html#use-dataflow-outside-tensorpack).
