### ISSUE TITLE
Error while creating summary

### ISSUE THREAD

**Issue by h44rd** [tensorpack/tensorpack#808]
Hello!
I have encountered another error while training the HED model running the command `./hed.py --load HED_pretrained_bsds.npz --gpu 0`:

```
[0702 15:35:54 @logger.py:109] WRN Log directory train_log/hed exists! Use 'd' to delete it. 
[0702 15:35:54 @logger.py:112] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):d
[0702 15:35:56 @logger.py:74] Argv: ./hed.py --load HED_pretrained_bsds.npz --gpu 0
[0702 15:35:57 @param.py:194] Use train_log/hed/hyper.txt to set hyperparam: 'learning_rate'.
[0702 15:35:57 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0702 15:35:57 @input_source.py:195] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0702 15:35:57 @training.py:103] Building graph for training tower 0 ...
[0702 15:35:57 @registry.py:121] conv1_1 input: [None, None, None, 3]
[0702 15:35:57 @registry.py:129] conv1_1 output: [None, None, None, 64]
[0702 15:35:57 @registry.py:121] conv1_2 input: [None, None, None, 64]
[0702 15:35:57 @registry.py:129] conv1_2 output: [None, None, None, 64]
[0702 15:35:57 @registry.py:121] branch1/convfc input: [None, None, None, 64]
[0702 15:35:57 @registry.py:129] branch1/convfc output: [None, None, None, 1]
[0702 15:35:57 @registry.py:121] pool1 input: [None, None, None, 64]
[0702 15:35:57 @registry.py:129] pool1 output: [None, None, None, 64]
[0702 15:35:57 @registry.py:121] conv2_1 input: [None, None, None, 64]
[0702 15:35:58 @registry.py:129] conv2_1 output: [None, None, None, 128]
[0702 15:35:58 @registry.py:121] conv2_2 input: [None, None, None, 128]
[0702 15:35:58 @registry.py:129] conv2_2 output: [None, None, None, 128]
[0702 15:35:58 @registry.py:121] branch2/convfc input: [None, None, None, 128]
[0702 15:35:58 @registry.py:129] branch2/convfc output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch2/upsample2 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch2/upsample2 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] pool2 input: [None, None, None, 128]
[0702 15:35:58 @registry.py:129] pool2 output: [None, None, None, 128]
[0702 15:35:58 @registry.py:121] conv3_1 input: [None, None, None, 128]
[0702 15:35:58 @registry.py:129] conv3_1 output: [None, None, None, 256]
[0702 15:35:58 @registry.py:121] conv3_2 input: [None, None, None, 256]
[0702 15:35:58 @registry.py:129] conv3_2 output: [None, None, None, 256]
[0702 15:35:58 @registry.py:121] conv3_3 input: [None, None, None, 256]
[0702 15:35:58 @registry.py:129] conv3_3 output: [None, None, None, 256]
[0702 15:35:58 @registry.py:121] branch3/convfc input: [None, None, None, 256]
[0702 15:35:58 @registry.py:129] branch3/convfc output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch3/upsample4 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch3/upsample4 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch3/upsample2 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch3/upsample2 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] pool3 input: [None, None, None, 256]
[0702 15:35:58 @registry.py:129] pool3 output: [None, None, None, 256]
[0702 15:35:58 @registry.py:121] conv4_1 input: [None, None, None, 256]
[0702 15:35:58 @registry.py:129] conv4_1 output: [None, None, None, 512]
[0702 15:35:58 @registry.py:121] conv4_2 input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] conv4_2 output: [None, None, None, 512]
[0702 15:35:58 @registry.py:121] conv4_3 input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] conv4_3 output: [None, None, None, 512]
[0702 15:35:58 @registry.py:121] branch4/convfc input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] branch4/convfc output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch4/upsample8 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch4/upsample8 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch4/upsample4 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch4/upsample4 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch4/upsample2 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch4/upsample2 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] pool4 input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] pool4 output: [None, None, None, 512]
[0702 15:35:58 @registry.py:121] conv5_1 input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] conv5_1 output: [None, None, None, 512]
[0702 15:35:58 @registry.py:121] conv5_2 input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] conv5_2 output: [None, None, None, 512]
[0702 15:35:58 @registry.py:121] conv5_3 input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] conv5_3 output: [None, None, None, 512]
[0702 15:35:58 @registry.py:121] branch5/convfc input: [None, None, None, 512]
[0702 15:35:58 @registry.py:129] branch5/convfc output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch5/upsample16 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch5/upsample16 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch5/upsample8 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch5/upsample8 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch5/upsample4 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch5/upsample4 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] branch5/upsample2 input: [None, None, None, 1]
[0702 15:35:58 @registry.py:129] branch5/upsample2 output: [None, None, None, 1]
[0702 15:35:58 @registry.py:121] convfcweight input: [None, None, None, 5]
[0702 15:35:58 @registry.py:129] convfcweight output: [None, None, None, 1]
[0702 15:35:58 @regularize.py:88] regularize_cost() found 19 variables to regularize.
[0702 15:35:58 @regularize.py:19] The following tensors will be regularized: conv1_1/W:0, conv1_2/W:0, branch1/convfc/W:0, conv2_1/W:0, conv2_2/W:0, branch2/convfc/W:0, conv3_1/W:0, conv3_2/W:0, conv3_3/W:0, branch3/convfc/W:0, conv4_1/W:0, conv4_2/W:0, conv4_3/W:0, branch4/convfc/W:0, conv5_1/W:0, conv5_2/W:0, conv5_3/W:0, branch5/convfc/W:0, convfcweight/W:0
[0702 15:35:58 @gradproc.py:251] Apply lr multiplier 5 for conv5_1/W
[0702 15:35:58 @gradproc.py:251] Apply lr multiplier 5 for conv5_1/b
[0702 15:35:58 @gradproc.py:251] Apply lr multiplier 5 for conv5_2/W
[0702 15:35:58 @gradproc.py:251] Apply lr multiplier 5 for conv5_2/b
[0702 15:35:58 @gradproc.py:251] Apply lr multiplier 5 for conv5_3/W
[0702 15:35:58 @gradproc.py:251] Apply lr multiplier 5 for conv5_3/b
[0702 15:35:58 @gradproc.py:251] Apply lr multiplier 0.1 for convfcweight/W
[0702 15:35:59 @model_utils.py:63] Trainable Variables: 
name                shape                 dim
------------------  ----------------  -------
conv1_1/W:0         [3, 3, 3, 64]        1728
conv1_1/b:0         [64]                   64
conv1_2/W:0         [3, 3, 64, 64]      36864
conv1_2/b:0         [64]                   64
branch1/convfc/W:0  [1, 1, 64, 1]          64
branch1/convfc/b:0  [1]                     1
conv2_1/W:0         [3, 3, 64, 128]     73728
conv2_1/b:0         [128]                 128
conv2_2/W:0         [3, 3, 128, 128]   147456
conv2_2/b:0         [128]                 128
branch2/convfc/W:0  [1, 1, 128, 1]        128
branch2/convfc/b:0  [1]                     1
conv3_1/W:0         [3, 3, 128, 256]   294912
conv3_1/b:0         [256]                 256
conv3_2/W:0         [3, 3, 256, 256]   589824
conv3_2/b:0         [256]                 256
conv3_3/W:0         [3, 3, 256, 256]   589824
conv3_3/b:0         [256]                 256
branch3/convfc/W:0  [1, 1, 256, 1]        256
branch3/convfc/b:0  [1]                     1
conv4_1/W:0         [3, 3, 256, 512]  1179648
conv4_1/b:0         [512]                 512
conv4_2/W:0         [3, 3, 512, 512]  2359296
conv4_2/b:0         [512]                 512
conv4_3/W:0         [3, 3, 512, 512]  2359296
conv4_3/b:0         [512]                 512
branch4/convfc/W:0  [1, 1, 512, 1]        512
branch4/convfc/b:0  [1]                     1
conv5_1/W:0         [3, 3, 512, 512]  2359296
conv5_1/b:0         [512]                 512
conv5_2/W:0         [3, 3, 512, 512]  2359296
conv5_2/b:0         [512]                 512
conv5_3/W:0         [3, 3, 512, 512]  2359296
conv5_3/b:0         [512]                 512
branch5/convfc/W:0  [1, 1, 512, 1]        512
branch5/convfc/b:0  [1]                     1
convfcweight/W:0    [1, 1, 5, 1]            5
Total #vars=37, #params=14716170, size=56.14MB
[0702 15:35:59 @base.py:179] Setup callbacks graph ...
[0702 15:35:59 @predict.py:41] Building predictor tower 'InferenceTower' on device /gpu:0 ...
[0702 15:35:59 @summary.py:38] Maintain moving average summary of 9 tensors in collection MOVING_SUMMARY_OPS.
[0702 15:35:59 @summary.py:75] Summarizing collection 'summaries' of size 29.
[0702 15:36:00 @base.py:197] Creating the session ...
2018-07-02 15:36:00.678514: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-07-02 15:36:00.903149: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 11.90GiB freeMemory: 10.66GiB
2018-07-02 15:36:00.903194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
[0702 15:36:01 @base.py:203] Initializing the session ...
[0702 15:36:01 @sessinit.py:207] Variables to restore from dict: branch1/convfc/b:0, conv5_3/b:0, conv5_1/b:0, conv1_1/b:0, branch4/convfc/W:0, conv2_1/W:0, conv3_2/W:0, conv5_3/W:0, conv3_3/b:0, branch4/convfc/b:0, conv4_3/W:0, branch3/convfc/b:0, conv1_2/W:0, branch2/convfc/b:0, conv2_2/W:0, branch2/convfc/W:0, branch5/convfc/b:0, conv5_2/b:0, conv3_1/W:0, conv5_2/W:0, conv4_2/W:0, conv2_2/b:0, conv1_1/W:0, conv3_1/b:0, conv3_3/W:0, conv4_3/b:0, conv3_2/b:0, branch1/convfc/W:0, conv4_2/b:0, branch5/convfc/W:0, conv4_1/b:0, conv5_1/W:0, conv2_1/b:0, convfcweight/W:0, conv1_2/b:0, branch3/convfc/W:0, conv4_1/W:0
[0702 15:36:01 @sessinit.py:90] WRN The following variables are in the graph, but not found in the dict: beta1_power:0, beta2_power:0, global_step:0, learning_rate:0
[0702 15:36:01 @sessinit.py:90] WRN The following variables are in the dict, but not found in the graph: branchg/convfc/W:0
[0702 15:36:01 @sessinit.py:220] Restoring from dict ...
[0702 15:36:02 @base.py:210] Graph Finalized.
[0702 15:36:02 @concurrency.py:37] Starting EnqueueThread QueueInput/input_queue ...
[0702 15:36:03 @inference_runner.py:99] InferenceRunner will eval 141 iterations
[0702 15:36:03 @base.py:242] Start Epoch 1 ...
  7%|###########1                                                                                                                                                 7%|###                                    100%|########################################################################################################################################################################|680/680[19:21<00:00, 1.07it/s]
[0702 15:55:24 @base.py:252] Epoch 1 (global_step 680) finished, time:19 minutes 21 seconds.
[0702 15:55:24 @saver.py:84] Model saved to train_log/hed/model-680.
100%|########################################################################################################################################################################|141/141[00:03<00:00,37.38it/s]
2018-07-02 15:55:28.766212: W tensorflow/core/kernels/queue_base.cc:295] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "./hed.py", line 270, in <module>
[0702 15:55:28 @input_source.py:150] EnqueueThread QueueInput/input_queue Exited.
    SyncMultiGPUTrainer(max(get_nr_gpu(), 1)))
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 311, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 283, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/train/base.py", line 255, in main_loop
    self._callbacks.trigger_epoch()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
    self._trigger_epoch()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/group.py", line 93, in _trigger_epoch
    cb.trigger_epoch()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
    self._trigger_epoch()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 155, in _trigger_epoch
    self.trigger()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 158, in trigger
    self._trigger()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/inference_runner.py", line 172, in _trigger
    inf.trigger_epoch()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
    self._trigger_epoch()
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/inference.py", line 44, in _trigger_epoch
    self.trainer.monitors.put_scalar(k, v)
  File "/home/phaard/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorpack/callbacks/monitor.py", line 165, in put_scalar
    s = tb.summary.scalar_pb(name, val)
AttributeError: 'module' object has no attribute 'summary'
PrefetchDataZMQ successfully cleaned-up.

```

**Comment by ppwwyyxx** [comment]
Please upgrade tensorpack to github master. The change to use `tb.summary` was reverted last week

**Comment by ppwwyyxx** [comment]
Or use latest version of tensorflow + tensorboard. Then you'll have `tb.summary`
