### ISSUE TITLE
error running alexnet_dorefa.py

### ISSUE THREAD

**Issue by brisker** [tensorpack/tensorpack#810]
environment:
tensorflow1.13.0(in docker) cuda8.0 cudnn6 anaconda2

error running alexnet_dorefa.py.
it is weird that in the /root/tensorpack_data, there is a caffe_ilsvrc12.tar.gz file but it is only 4kb in size, which should be in 17MB in size. These are a little confusing to me. Any help is appreciated! 
@ppwwyyxx 
the error looks like this:
```
root@997991b14e71:/data/home/users/ccc/projects/tensorpack/examples/DoReFa-Net# ./alexnet-dorefa.py --dorefa 1,2,6 --data /data/data/ImageNetOrigin --gpu 4,5,6,7
/root/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[0703 06:54:57 @logger.py:109] WRN Log directory train_log/alexnet-dorefa-1,2,6 exists! Use 'd' to delete it. 
[0703 06:54:57 @logger.py:112] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):d
[0703 06:54:58 @logger.py:74] Argv: ./alexnet-dorefa.py --dorefa 1,2,6 --data /data/data/ImageNetOrigin --gpu 4,5,6,7
[0703 06:54:58 @alexnet-dorefa.py:222] Batch per tower: 64
[0703 06:54:58 @fs.py:88] WRN Env var $TENSORPACK_DATASET not set, using /root/tensorpack_data for datasets.
caffe_ilsvrc12.tar.gz: 8.19kB [00:00, 26.0kB/s]
Succesfully downloaded caffe_ilsvrc12.tar.gz. 2942 bytes.
Traceback (most recent call last):
  File "./alexnet-dorefa.py", line 224, in <module>
    config = get_config()
  File "./alexnet-dorefa.py", line 147, in get_config
    data_train = get_data('train')
  File "./alexnet-dorefa.py", line 143, in get_data
    args.data, dataset_name, BATCH_SIZE, augmentors)
  File "/data/home/users/ccc/projects/tensorpack/examples/DoReFa-Net/imagenet_utils.py", line 101, in get_imagenet_dataflow
    ds = dataset.ILSVRC12(datadir, name, shuffle=True)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/dataflow/dataset/ilsvrc.py", line 247, in __init__
    dir, name, meta_dir, shuffle, dir_structure)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/dataflow/dataset/ilsvrc.py", line 158, in __init__
    meta = ILSVRCMeta(meta_dir)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/dataflow/dataset/ilsvrc.py", line 32, in __init__
    self._download_caffe_meta()
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/dataflow/dataset/ilsvrc.py", line 57, in _download_caffe_meta
    tarfile.open(fpath, 'r:gz').extractall(self.dir)
  File "/root/anaconda2/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/root/anaconda2/lib/python2.7/tarfile.py", line 1751, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
```

**Comment by ppwwyyxx** [comment]
You have a network failure or something that made the download fail. Please download it by yourself at http://dl.caffe.berkeleyvision.org/caffe_ilsvrc12.tar.gz

**Comment by brisker** [comment]
@ppwwyyxx 
I have downloaded this and put it into the  ~/tensorpack_data/ilsvrc_metadata, but it seems that the code will delete what I have manually downloaded.

**Comment by ppwwyyxx** [comment]
Ah right. Please download __and decompress__ it.

**Comment by brisker** [comment]
@ppwwyyxx 
still this error
![image](https://user-images.githubusercontent.com/13804492/42204185-88560f44-7ed3-11e8-80fe-b3d424a7c4d2.png)

**Comment by ppwwyyxx** [comment]
You should `tar xzf caffe_ilsvrc12.tar.gz`. There should be files such as `ilsvrc_metadata/synsets.txt`

**Comment by brisker** [comment]
@ppwwyyxx 
new error:
```
root@997991b14e71:/data/home/users/ccc/projects/tensorpack/examples/DoReFa-Net# ./alexnet-dorefa.py --dorefa 1,2,6 --data /data/data/ImageNetOrigin --gpu 4,5,6,7
/root/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[0703 07:15:20 @logger.py:109] WRN Log directory train_log/alexnet-dorefa-1,2,6 exists! Use 'd' to delete it. 
[0703 07:15:20 @logger.py:112] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):d
[0703 07:15:22 @logger.py:74] Argv: ./alexnet-dorefa.py --dorefa 1,2,6 --data /data/data/ImageNetOrigin --gpu 4,5,6,7
[0703 07:15:22 @alexnet-dorefa.py:222] Batch per tower: 64
[0703 07:15:22 @fs.py:88] WRN Env var $TENSORPACK_DATASET not set, using /root/tensorpack_data for datasets.
[0703 07:15:23 @parallel.py:290] [PrefetchDataZMQ] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0703 07:15:23 @ilsvrc.py:128] [ILSVRC12] Assuming directory /data/data/ImageNetOrigin/val has 'original' structure.
[0703 07:15:23 @training.py:51] [DataParallel] Training a model of 4 towers.
[0703 07:15:23 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0703 07:15:23 @interface.py:42] Automatically applying StagingInput on the DataFlow.
[0703 07:15:23 @input_source.py:195] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0703 07:15:23 @training.py:111] Building graph for training tower 0 on device /gpu:0 ...
[0703 07:15:23 @registry.py:121] conv0 input: [None, 3, 224, 224]
[0703 07:15:23 @registry.py:129] conv0 output: [None, 96, 54, 54]
[0703 07:15:23 @registry.py:121] conv1 input: [None, 96, 54, 54]
[0703 07:15:23 @alexnet-dorefa.py:79] Quantizing weight conv1/W
[0703 07:15:23 @registry.py:129] conv1 output: [None, 256, 54, 54]
[0703 07:15:23 @registry.py:121] pool1 input: [None, 256, 54, 54]
[0703 07:15:23 @registry.py:129] pool1 output: [None, 256, 27, 27]
[0703 07:15:23 @registry.py:121] conv2 input: [None, 256, 27, 27]
[0703 07:15:23 @alexnet-dorefa.py:79] Quantizing weight conv2/W
[0703 07:15:23 @registry.py:129] conv2 output: [None, 384, 27, 27]
[0703 07:15:23 @registry.py:121] pool2 input: [None, 384, 27, 27]
[0703 07:15:23 @registry.py:129] pool2 output: [None, 384, 14, 14]
[0703 07:15:23 @registry.py:121] conv3 input: [None, 384, 14, 14]
[0703 07:15:23 @alexnet-dorefa.py:79] Quantizing weight conv3/W
[0703 07:15:24 @registry.py:129] conv3 output: [None, 384, 14, 14]
[0703 07:15:24 @registry.py:121] conv4 input: [None, 384, 14, 14]
[0703 07:15:24 @alexnet-dorefa.py:79] Quantizing weight conv4/W
[0703 07:15:24 @registry.py:129] conv4 output: [None, 256, 14, 14]
[0703 07:15:24 @registry.py:121] pool4 input: [None, 256, 14, 14]
[0703 07:15:24 @registry.py:129] pool4 output: [None, 256, 6, 6]
[0703 07:15:24 @registry.py:121] fc0 input: [None, 256, 6, 6]
[0703 07:15:24 @alexnet-dorefa.py:79] Quantizing weight fc0/W
[0703 07:15:24 @registry.py:129] fc0 output: [None, 4096]
Traceback (most recent call last):
  File "./alexnet-dorefa.py", line 227, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerReplicated(nr_tower))
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/interface.py", line 81, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/tower.py", line 172, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/trainers.py", line 166, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 222, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 118, in build_on_towers
    ret.append(func())
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/tower.py", line 199, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/tfutils/tower.py", line 255, in __call__
    output = self._tower_fn(*args)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/graph_builder/model_desc.py", line 235, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "/data/home/users/ccc/projects/tensorpack/examples/DoReFa-Net/imagenet_utils.py", line 181, in build_graph
    logits = self.get_logits(image)
  File "./alexnet-dorefa.py", line 122, in get_logits
    .BatchNorm('bnfc0')
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/models/linearwrap.py", line 47, in layer_func
    ret = layer(name, self._t, *args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/models/tflayer.py", line 64, in decorated_func
    return func(inputs, **ret)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/models/batch_norm.py", line 176, in BatchNorm
    xn = layer.apply(inputs, training=training, scope=tf.get_variable_scope())
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 503, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 443, in __call__
    self.build(input_shapes[0])
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 150, in build
    'to its original shape. Got input rank: ', ndim)
ValueError: ('Only 4D inputs are currently supported with fused batch norm. Consider reshaping the input to 4D and reshape the output back to its original shape. Got input rank: ', 2)
```

**Comment by ppwwyyxx** [comment]
It works fine under TF 1.8. Maybe an early version of TF cause this failure. Which version are you using? I can try to add some code to work around early versions.

**Comment by brisker** [comment]
@ppwwyyxx 
environment:
tensorflow1.13.0(in docker) cuda8.0 cudnn6 anaconda2

**Comment by brisker** [comment]
@ppwwyyxx 
still error

**Comment by brisker** [comment]
@ppwwyyxx 
sorry, I forgort to modify the batch_norm.py in the anaconda/lib/python2.7/xxxxx ..
after modifying that file, the error changes to:
```
root@997991b14e71:/data/home/users/wangdu/projects/tensorpack/examples/DoReFa-Net# ./alexnet-dorefa.py --dorefa 1,2,6 --data /data/data/ImageNetOrigin --gpu 4,5,6,7
/root/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[0703 07:51:08 @logger.py:109] WRN Log directory train_log/alexnet-dorefa-1,2,6 exists! Use 'd' to delete it. 
[0703 07:51:08 @logger.py:112] WRN If you're resuming from a previous run, you can choose to keep it.
Press any other key to exit. 
Select Action: k (keep) / d (delete) / q (quit):d
[0703 07:51:10 @logger.py:74] Argv: ./alexnet-dorefa.py --dorefa 1,2,6 --data /data/data/ImageNetOrigin --gpu 4,5,6,7
[0703 07:51:10 @alexnet-dorefa.py:222] Batch per tower: 64
[0703 07:51:10 @fs.py:88] WRN Env var $TENSORPACK_DATASET not set, using /root/tensorpack_data for datasets.
[0703 07:51:12 @parallel.py:290] [PrefetchDataZMQ] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[0703 07:51:12 @ilsvrc.py:128] [ILSVRC12] Assuming directory /data/data/ImageNetOrigin/val has 'original' structure.
[0703 07:51:12 @training.py:51] [DataParallel] Training a model of 4 towers.
[0703 07:51:12 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0703 07:51:12 @interface.py:42] Automatically applying StagingInput on the DataFlow.
[0703 07:51:12 @input_source.py:195] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0703 07:51:12 @training.py:111] Building graph for training tower 0 on device /gpu:0 ...
[0703 07:51:12 @registry.py:121] conv0 input: [None, 3, 224, 224]
[0703 07:51:12 @registry.py:129] conv0 output: [None, 96, 54, 54]
[0703 07:51:12 @registry.py:121] conv1 input: [None, 96, 54, 54]
[0703 07:51:12 @alexnet-dorefa.py:79] Quantizing weight conv1/W
[0703 07:51:12 @registry.py:129] conv1 output: [None, 256, 54, 54]
[0703 07:51:12 @registry.py:121] pool1 input: [None, 256, 54, 54]
[0703 07:51:12 @registry.py:129] pool1 output: [None, 256, 27, 27]
[0703 07:51:12 @registry.py:121] conv2 input: [None, 256, 27, 27]
[0703 07:51:12 @alexnet-dorefa.py:79] Quantizing weight conv2/W
[0703 07:51:12 @registry.py:129] conv2 output: [None, 384, 27, 27]
[0703 07:51:12 @registry.py:121] pool2 input: [None, 384, 27, 27]
[0703 07:51:12 @registry.py:129] pool2 output: [None, 384, 14, 14]
[0703 07:51:12 @registry.py:121] conv3 input: [None, 384, 14, 14]
[0703 07:51:12 @alexnet-dorefa.py:79] Quantizing weight conv3/W
[0703 07:51:12 @registry.py:129] conv3 output: [None, 384, 14, 14]
[0703 07:51:12 @registry.py:121] conv4 input: [None, 384, 14, 14]
[0703 07:51:12 @alexnet-dorefa.py:79] Quantizing weight conv4/W
[0703 07:51:12 @registry.py:129] conv4 output: [None, 256, 14, 14]
[0703 07:51:12 @registry.py:121] pool4 input: [None, 256, 14, 14]
[0703 07:51:12 @registry.py:129] pool4 output: [None, 256, 6, 6]
[0703 07:51:12 @registry.py:121] fc0 input: [None, 256, 6, 6]
[0703 07:51:12 @alexnet-dorefa.py:79] Quantizing weight fc0/W
[0703 07:51:12 @registry.py:129] fc0 output: [None, 4096]
[0703 07:51:12 @registry.py:121] fc1 input: [None, 4096]
[0703 07:51:12 @alexnet-dorefa.py:79] Quantizing weight fc1/W
[0703 07:51:12 @registry.py:129] fc1 output: [None, 4096]
[0703 07:51:12 @registry.py:121] fct input: [None, 4096]
[0703 07:51:12 @registry.py:129] fct output: [None, 1000]
[0703 07:51:12 @regularize.py:88] regularize_cost() found 3 variables to regularize.
[0703 07:51:12 @regularize.py:19] The following tensors will be regularized: fc0/W:0, fc1/W:0, fct/W:0
[0703 07:51:13 @training.py:111] Building graph for training tower 1 on device /gpu:1 ...
[0703 07:51:13 @alexnet-dorefa.py:79] Quantizing weight tower1/conv1/W
[0703 07:51:13 @alexnet-dorefa.py:79] Quantizing weight tower1/conv2/W
[0703 07:51:13 @alexnet-dorefa.py:79] Quantizing weight tower1/conv3/W
[0703 07:51:13 @alexnet-dorefa.py:79] Quantizing weight tower1/conv4/W
[0703 07:51:13 @alexnet-dorefa.py:79] Quantizing weight tower1/fc0/W
[0703 07:51:13 @alexnet-dorefa.py:79] Quantizing weight tower1/fc1/W
[0703 07:51:13 @regularize.py:88] regularize_cost() found 3 variables to regularize.
[0703 07:51:14 @training.py:111] Building graph for training tower 2 on device /gpu:2 ...
[0703 07:51:14 @alexnet-dorefa.py:79] Quantizing weight tower2/conv1/W
[0703 07:51:14 @alexnet-dorefa.py:79] Quantizing weight tower2/conv2/W
[0703 07:51:14 @alexnet-dorefa.py:79] Quantizing weight tower2/conv3/W
[0703 07:51:14 @alexnet-dorefa.py:79] Quantizing weight tower2/conv4/W
[0703 07:51:14 @alexnet-dorefa.py:79] Quantizing weight tower2/fc0/W
[0703 07:51:14 @alexnet-dorefa.py:79] Quantizing weight tower2/fc1/W
[0703 07:51:15 @regularize.py:88] regularize_cost() found 3 variables to regularize.
[0703 07:51:15 @training.py:111] Building graph for training tower 3 on device /gpu:3 ...
[0703 07:51:15 @alexnet-dorefa.py:79] Quantizing weight tower3/conv1/W
[0703 07:51:15 @alexnet-dorefa.py:79] Quantizing weight tower3/conv2/W
[0703 07:51:16 @alexnet-dorefa.py:79] Quantizing weight tower3/conv3/W
[0703 07:51:16 @alexnet-dorefa.py:79] Quantizing weight tower3/conv4/W
[0703 07:51:16 @alexnet-dorefa.py:79] Quantizing weight tower3/fc0/W
[0703 07:51:16 @alexnet-dorefa.py:79] Quantizing weight tower3/fc1/W
[0703 07:51:16 @regularize.py:88] regularize_cost() found 3 variables to regularize.
[0703 07:51:18 @training.py:318] 'sync_variables_from_main_tower' includes 243 operations.
[0703 07:51:18 @model_utils.py:63] Trainable Variables: 
name           shape                  dim
-------------  ----------------  --------
conv0/W:0      [12, 12, 3, 96]      41472
conv0/b:0      [96]                    96
conv1/W:0      [5, 5, 48, 256]     307200
bn1/beta:0     [256]                  256
bn1/gamma:0    [256]                  256
conv2/W:0      [3, 3, 256, 384]    884736
bn2/beta:0     [384]                  384
bn2/gamma:0    [384]                  384
conv3/W:0      [3, 3, 192, 384]    663552
bn3/beta:0     [384]                  384
bn3/gamma:0    [384]                  384
conv4/W:0      [3, 3, 192, 256]    442368
bn4/beta:0     [256]                  256
bn4/gamma:0    [256]                  256
fc0/W:0        [9216, 4096]      37748736
fc0/b:0        [4096]                4096
bnfc0/beta:0   [4096]                4096
bnfc0/gamma:0  [4096]                4096
fc1/W:0        [4096, 4096]      16777216
bnfc1/beta:0   [4096]                4096
bnfc1/gamma:0  [4096]                4096
fct/W:0        [4096, 1000]       4096000
fct/b:0        [1000]                1000
Total #vars=23, #params=60985416, size=232.64MB
[0703 07:51:18 @base.py:174] Setup callbacks graph ...
[0703 07:51:18 @parallel.py:52] WRN TENSORPACK_PIPEDIR is not used on Linux any more! Abstract sockets will be used.
Traceback (most recent call last):
  File "./alexnet-dorefa.py", line 227, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerReplicated(nr_tower))
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/interface.py", line 90, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/base.py", line 306, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/base.py", line 276, in train
    self.setup_callbacks(callbacks, monitors)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/train/base.py", line 176, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/callbacks/group.py", line 66, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack/input_source/input_source.py", line 507, in _setup_graph
    unstage_op = tf.group(unstage_ops, name='unstage_all')
  File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2895, in group
    dev = inp.device
AttributeError: 'list' object has no attribute 'device'
PrefetchDataZMQ successfully cleaned-up.
```

**Comment by ppwwyyxx** [comment]
The above commit should fix this one (and the other ones in this issue).

The dorefa-net example actually explicitly said in the read me that it requires TF>=1.7: https://github.com/tensorpack/tensorpack/tree/master/examples/DoReFa-Net#use.
To really use TF1.3 you'll need to copy-paste an older version of `dorefa.py` as well (I assume you've done that already?)

**Comment by brisker** [comment]
@ppwwyyxx 
I will give a try instantly. Before this, I want to ask that, I have installed the tensorpack using "pip install -U git+https://github.com/tensorpack/tensorpack.git" , in the anaconda2 environment. So if I  want to manually make modifications based on your new commits, I need to modified the code files in the anaconda/lib/python2.7/xxx ?

**Comment by ppwwyyxx** [comment]
You can `print(tensorpack.__file__)` to see where to modify. You can also run `pip install -U git+https://github.com/tensorpack/tensorpack.git` again to upgrade.

**Comment by brisker** [comment]
@ppwwyyxx 
no training error now . thanks a lot
besides,  if I want to train the quantized model based on the 32-bit full precision model, will simply "--load alexnet.npz" work?

**Comment by ppwwyyxx** [comment]
1. http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
2. Don't know where the npz is from. But you'll need to modify the code to load from npz instead of checkpoint. http://tensorpack.readthedocs.io/tutorial/save-load.html#load-a-model
4. http://tensorpack.readthedocs.io/modules/callbacks.html#tensorpack.callbacks.PeriodicTrigger
3. https://github.com/tensorpack/tensorpack/blob/master/tensorpack/dataflow/dataset/cifar.py#L23-L40
Looks like the code is expecting a directory called "cifar-100-python"

**Comment by ppwwyyxx** [comment]
btw, even with 4 TitanX and TF 1.3, and standard alexnet (in https://github.com/tensorpack/tensorpack/tree/master/examples/ImageNetModels), I can see 4.8 it/s where each iteration is a total batch of 256.

This is not a standard alexnet. On 4 TitanX and TF 1.3 I saw around 1.5it/s -- just a reference. You still need to figure out why your environment is slow. It's probably caused by slow data loader (i.e. slow cpu or disk). Since you're using anaconda, it's worth noticing that opencv in anaconda is usually very very slow: https://github.com/tensorpack/benchmarks/blob/master/ImageNet/benchmark-opencv-resize.py .
You might want to check that and use a different opencv (e.g. `pip install opencv-python`)

**Comment by ppwwyyxx** [comment]
As the website says it is a caffe version of AlexNet, which has many differences from the `alexnet-dorefa` code.

**Comment by brisker** [comment]
@ppwwyyxx 
but still error after I downloaded the cifar-100 data manully and run the cifar-convnet in the /examples/basics foler.
![image](https://user-images.githubusercontent.com/13804492/42253196-338e7118-7f73-11e8-94da-444278fefd9e.png)

**Comment by ppwwyyxx** [comment]
Extract it where it is supposed to be downloaded, i.e. tensorpack_data/cifar100_data. Not tensorpack_data.

**Comment by brisker** [comment]
@ppwwyyxx 
given that there is clip operation to [0,1] for the activations in dorefa-net, what is the pixel value range of the  network input?
[-1,1] or [-255,255] (since you have substracted mean). Will this influence the result?

**Comment by ppwwyyxx** [comment]
See the class ImageNetModel

**Comment by brisker** [comment]
@ppwwyyxx 
In dorefa-net, most of the convoluion and fully connected layers have **no bias term**, right? Why?

**Comment by ppwwyyxx** [comment]
1. https://twitter.com/karpathy/status/1013244313327681536?s=19
2. I have no comments.

**Comment by brisker** [comment]
@ppwwyyxx 
in the paper the author mentioned the training-from-scratch and fineuning-from-full-precision experiments, so can you provide the alexnet-float32 full precision model?

**Comment by ppwwyyxx** [comment]
1. This open source code does not contain the experiment you mentioned. We will not provide the full precision model.
2. `PeriodicTrigger(ModelSaver(), every_k_epochs=5)`.

**Comment by brisker** [comment]
@ppwwyyxx 
1. Given that there is clip operation to [0,1] on the activations, we need to zero the gradients corresponding to these 0s and 1s. But I can not find this zero-gradient operation in the code. Is this due to the auto-grad mechanism of tensorflow?
2. It seems that there is no "de-normalization" process in the code, since there is the following formula to normalize the weight to range[-1,1]
![image](https://user-images.githubusercontent.com/13804492/42389616-dbcaa02c-817b-11e8-9c34-9103a975f453.png)
If there is no de-normalization (or call it de-quantization), the data distribution seems to be different from the original weights. Is this correct? Or have I understood something wrong?

**Comment by ppwwyyxx** [comment]
1. I don't know what you mean by "zero the gradients". TensorFlow has correct gradients for the clip operation.
2. It's correct. But there is also a BatchNorm layer that will bring the distribution back.

**Comment by brisker** [comment]
@ppwwyyxx 
But what I am refering to is the weights of convolutions, not activations. Why can batchnorm bring the data distribution of convolution weights back?

**Comment by ppwwyyxx** [comment]
You're correct. For weights it's not related to batchnorm.

**Comment by brisker** [comment]
@ppwwyyxx 
So did you mean that this implementation does not have the de-normalization process? This does not influence the accuracy？

**Comment by ppwwyyxx** [comment]
This is the official implementation of the paper. It never has the so-called de-normalization process.

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/tutorial/save-load.html
`--load model-xxxxxxx`

**Comment by brisker** [comment]
@ppwwyyxx 
I run --load 2925, and
the log has the following hints:
[0707 06:52:15 @steps.py:126] Start training with global_step=2925

so this restore just load the weights, not any more information loaded right? (for example load the **learning rate stored in the model-2925**)

**Comment by ppwwyyxx** [comment]
It restores anything stored in the checkpoint.

**Comment by brisker** [comment]
@ppwwyyxx 
what if I only want to load the weights?
Does tensorpack support this?

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/tutorial/save-load.html#work-with-tf-checkpoint
The page has explained it.

**Comment by ppwwyyxx** [comment]
The docs also has it: http://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.sessinit.SaverRestore.__init__

**Comment by brisker** [comment]
@ppwwyyxx 
so did you mean I can simply run the 
`python dump-model-params.py --input model-2925 --output weights.npz`
and then I can load this weights.npz file **for only loading the weights?**

**Comment by ppwwyyxx** [comment]
Conceptually yes. It loads whatever in `weights.npz`.
But your command line arguments are incorrect. Please read the docs `dump-model-params.py -h`

**Comment by brisker** [comment]
@ppwwyyxx 
I have successfully generate this weights.npz, but when I load this for finetuning, error is like this:
```
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ~/projects/tensorpack/examples/DoReFa-Net/float32/cifar100/train_log/alexnet-dorefa-32,32,32/model-7800-weights.npz: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
PrefetchDataZMQ successfully cleaned-up.
```

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/tutorial/save-load.html
The page has explained it.

**Comment by brisker** [comment]
@ppwwyyxx 
--load "weights.npz"
changing to DictRestore() still error......
```
Traceback (most recent call last):
  File "alexnet-dorefa.py", line 279, in <module>
    config.session_init = DictRestore(args.load)
  File "/root/anaconda2/lib/python2.7/site-packages/tensorpack-0.8.6-py2.7.egg/tensorpack/tfutils/sessinit.py", line 195, in __init__
    assert isinstance(variable_dict, dict), type(variable_dict)
AssertionError: <type 'str'>
```

**Comment by ppwwyyxx** [comment]
http://tensorpack.readthedocs.io/modules/tfutils.html#tensorpack.tfutils.sessinit.DictRestore
The docs said it needs a dict.

**Comment by brisker** [comment]
@ppwwyyxx 
But this weights.npz file is created from python dump-model-params.py --meta graph.meta model-2925 weights.npz.... This should be a dict, right?

**Comment by ppwwyyxx** [comment]
You wrote `DictRestore(args.load)`.
`args.load` is a filename of type `str`, as printed in the error message.

**Comment by ppwwyyxx** [comment]
I think so. The paper was >2 years old and I did not perform this experiment at that time so I do not remember what was the setting.

**Comment by brisker** [comment]
@ppwwyyxx
I run a --dorefa 8,8,8 experiment, but why the val-error-top1 is still >90% after 45 epoches? I just set the default settings in the alexnet_dorefa.py file

```
[0710 01:38:19 @base.py:237] Start Epoch 45 ...
100%|################################################################################################|5000/5000[16:57<00:00, 4.92it/s]
[0710 01:55:16 @base.py:247] Epoch 45 (global_step 225000) finished, time:16 minutes 57 seconds.
[0710 01:55:16 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
[0710 01:55:28 @saver.py:84] Model saved to train_log/alexnet-dorefa-8,8,8/model-225000.
100%|##################################################################################################|782/782[01:53<00:00, 6.90it/s]
[0710 01:57:21 @monitor.py:440] QueueInput/queue_size: 49.05
[0710 01:57:21 @monitor.py:440] l2_regularize_loss: 1.0566
[0710 01:57:21 @monitor.py:440] param-summary/conv0/W-rms: 0.093548
[0710 01:57:21 @monitor.py:440] param-summary/conv1/W-rms: 0.10669
[0710 01:57:21 @monitor.py:440] param-summary/conv2/W-rms: 0.1022
[0710 01:57:21 @monitor.py:440] param-summary/conv3/W-rms: 0.1015
[0710 01:57:21 @monitor.py:440] param-summary/conv4/W-rms: 0.10491
[0710 01:57:21 @monitor.py:440] param-summary/fc0/W-rms: 0.0076856
[0710 01:57:21 @monitor.py:440] param-summary/fc1/W-rms: 0.0070158
[0710 01:57:21 @monitor.py:440] param-summary/fct/W-rms: 0.016896
[0710 01:57:21 @monitor.py:440] train-error-top1: 0.46866
[0710 01:57:21 @monitor.py:440] train-error-top5: 0.2167
[0710 01:57:21 @monitor.py:440] val-error-top1: 0.95656
[0710 01:57:21 @monitor.py:440] val-error-top5: 0.87892
[0710 01:57:21 @monitor.py:440] xentropy-loss: 2.0036
```

**Comment by ppwwyyxx** [comment]
For unexpected problems, please post issues following the [issue template](https://github.com/tensorpack/tensorpack/blob/master/.github/ISSUE_TEMPLATE.md)
