### ISSUE TITLE
Type of PyArrow.Lib.Buffer for dump_dataflow_to_tfrecord w/ pyarrow

### ISSUE THREAD

**Issue by hsienkaikuo** [tensorpack/tensorpack#816]
I am trying to dump a dataflow to both LMDB/TFRecord. While dumping LMDB is fine, but TFRecord will hit the following Error:

====TraceBack====
Traceback (most recent call last):
  File "RecordIO2TFRecord.py", line 24, in <module>
    tensorpack.dataflow.dftools.dump_dataflow_to_tfrecord(ds, args.tfrecord)
  File "/home/hsienkai.kuo/.local/lib/python2.7/site-packages/tensorpack/dataflow/dftools.py", line 124, in dump_dataflow_to_tfrecord
    writer.write(dumps(dp))
  File "/home/hsienkai.kuo/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/tf_record.py", line 128, in write
    self._writer.WriteRecord(record)
  File "/home/hsienkai.kuo/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 503, in WriteRecord
    return _pywrap_tensorflow_internal.PyRecordWriter_WriteRecord(self, record)
**TypeError: expected string or Unicode object, pyarrow.lib.Buffer found**

After a quick check of PyArrow, found a workaround is to add "to_pybytes()" a pyarrow.lib.buffer object (utils/serialize.py). The patch is tested w/ dump_dataflow_to_tfrecord.

```
def dumps_pyarrow(obj):     
    """
    Serialize an object.

    Returns:
        Implementation-dependent bytes-like object
    """    
    return pa.serialize(obj).to_buffer().to_pybytes()
```

Please any check/comment if the workaround is reasonable, and if it is good as a patch. Thanks

**Comment by ppwwyyxx** [comment]
The latest commit has also fixed it, since #802 will need some improvement before it can be merged.
