### ISSUE TITLE
What is TowerContext error when the code set up the queue##Usage Questions

### ISSUE THREAD

**Issue by yuyijie1995** [tensorpack/tensorpack#860]
When I use the FaterRCNN example to train my own data ,there is always a error like below
[0813 14:01:42 @input_source.py:202] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
Traceback (most recent call last):
  File "/home/jsu/yuyijie/tensorpack/tensorpack/examples/FasterRCNN/train.py", line 628, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/train/interface.py", line 85, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/train/tower.py", line 202, in setup_graph
    input_callbacks = self._setup_input(inputs_desc, input)
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/train/tower.py", line 218, in _setup_input
    return input.setup(inputs_desc)
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/input_source/input_source_base.py", line 99, in setup
    return self.get_callbacks()
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/input_source/input_source_base.py", line 126, in get_callbacks
    before_train=lambda _: self.reset_state())] + self._get_callbacks()
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 245, in _get_callbacks
    return [cb, self._create_ema_callback(), _get_reset_callback(self._inf_ds)]
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 235, in _create_ema_callback
    size_ema_op = add_moving_summary(size, collection=None, decay=0.5)[0].op
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/tfutils/summary.py", line 222, in add_moving_summary
    ctx = get_current_tower_context()
  File "/home/jsu/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 222, in get_current_tower_context
    assert _CurrentTowerContext is not None, "The function is supposed to be called under a TowerContext!"
AssertionError: The function is supposed to be called under a TowerContext!
I  can not understand what it is mean and how to fix it .
Can you give me some suggestions?Thanks a lot
my file structure like this 
/home/jsu/图片/2018-08-13 14-08-34屏幕截图.png

**Comment by yuyijie1995** [comment]
![2018-08-13 14-08-34](https://user-images.githubusercontent.com/30818917/44015235-a214e848-9f02-11e8-9f82-d175d2a95b87.png)

**Comment by yuyijie1995** [comment]
Thankyou !
