### ISSUE TITLE
Error running Shufflenet-v2

### ISSUE THREAD

**Issue by jwook1004** [tensorpack/tensorpack#862]
An issue has to be one of the following:
- Potential Bugs

## For any unexpected problems, __PLEASE ALWAYS INCLUDE__:
1. What you did:
> In ImageNetModels directory, type the following command:
$ python3 shufflenet.py --gpu 0,1,2,3 --data /home/choij/disk/Data/ILSVRC2012 --v2 --r=0.5

2. What you observed, including but not limited to the __entire__ logs.
> Got the following error:

Traceback (most recent call last):
  File "shufflenet.py", line 285, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_tower))
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/train/interface.py", line 85, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/train/tower.py", line 203, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/train/trainers.py", line 93, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/graph_builder/training.py", line 160, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/graph_builder/training.py", line 118, in build_on_towers
    ret.append(func())
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/train/tower.py", line 231, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/tfutils/tower.py", line 284, in __call__
    output = self._tower_fn(*args)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/graph_builder/model_desc.py", line 233, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "/nvme0/choij/workspace/tensorpack_sentient/examples/ImageNetModels/imagenet_utils.py", line 181, in build_graph
    logits = self.get_logits(image)
  File "shufflenet.py", line 151, in get_logits
    l = shufflenet_stage('stage2', l, channels[0], 4, group)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "shufflenet.py", line 111, in shufflenet_stage
    l = shufflenet_unit_v2(name, l, channel, 2 if i == 0 else 1)
  File "/nvme0/choij/workspace/tensorpack_sentient/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "shufflenet.py", line 94, in shufflenet_unit_v2
    l = Conv2D('conv2', l, out_channel - shortcut_channel, 1, activation=BNReLU)
TypeError: unsupported operand type(s) for -: 'int' and 'Dimension'

> A potential simple fix would be: 
in line 90, replace "shortcut_channel = shortcut.shape[1]" into "shortcut_channel = shortcut.shape[1].value"

3. What you expected, if not obvious.
4. Your environment:
  + Python version. 
> Python3
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`.
> v1.6.0-0-gd2e24b6039 1.6.0
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__)'`.
> 0.8.8

**Comment by ppwwyyxx** [comment]
Thanks. The code works for newer version of tensorflow. But I'll adopt your fix.
