### ISSUE TITLE
AssertionError: Fine tuning a BatchNorm model with fixed statistics is only supported after https://github.com/tensorflow/tensorflow/pull/12580

### ISSUE THREAD

**Issue by PacteraOliver** [tensorpack/tensorpack#865]
Hi,

I update tensorflow and tensorflow-gpu to latest (1.10.0), then In Faster RCNN

I could evaluate but when training:

```
Traceback (most recent call last):
  File "train.py", line 993, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/interface.py", line 83, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 172, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/trainers.py", line 172, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 222, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 118, in build_on_towers
    ret.append(func())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 200, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/tower.py", line 255, in __call__
    output = self._tower_fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/model_desc.py", line 233, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "train.py", line 553, in build_graph
    c2345 = resnet_fpn_backbone(image, cfg.BACKBONE.RESNET_NUM_BLOCK)
  File "/home/yaooxii/pedestrian-detection/model/tensorpack/examples/CascadeRCNN/basemodel.py", line 187, in resnet_fpn_backbone
    l = Conv2D('conv0', l, 64, 7, strides=2, padding='VALID')
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/tflayer.py", line 64, in decorated_func
    return func(inputs, **ret)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/conv2d.py", line 68, in Conv2D
    ret = layer.apply(inputs, scope=tf.get_variable_scope())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 213, in call
    return self.activation(outputs)
  File "/home/yaooxii/pedestrian-detection/model/tensorpack/examples/CascadeRCNN/basemodel.py", line 61, in nonlin
    x = get_norm()(x)
  File "/home/yaooxii/pedestrian-detection/model/tensorpack/examples/CascadeRCNN/basemodel.py", line 105, in <lambda>
    return lambda x: Norm(layer_name, x, gamma_initializer=tf.zeros_initializer() if zero_init else None)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/tflayer.py", line 64, in decorated_func
    return func(inputs, **ret)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/batch_norm.py", line 161, in BatchNorm
    "Fine tuning a BatchNorm model with fixed statistics is only " \
AssertionError: Fine tuning a BatchNorm model with fixed statistics is only supported after https://github.com/tensorflow/tensorflow/pull/12580 
```

**Comment by PacteraOliver** [comment]
I read the #578 , but its problem it version is before 1.4.0.

**Comment by ppwwyyxx** [comment]
Upgrade tensorpack.

**Comment by PacteraOliver** [comment]
Solved by upgrading.
