### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

### ISSUE THREAD

**Issue by sgzqc** [tensorpack/tensorpack#874]
Error message:  
```
[0828 17:01:29 @base.py:262] Start Epoch 5 ...
100%|#########9|498/500[06:01<00:01, 1.38it/s][0828 17:07:33 @input_source.py:149] EnqueueThread QueueInput/input_queue Exited.
100%|#########9|499/500[06:03<00:00, 1.37it/s]
2018-08-28 17:07:33.153894: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tf_py3/lane_stopline_tensorpack_model/tensorpack-master-lane/examples/train_model.py", line 515, in <module>
    launch_train_with_config(cfg, trainer)
  File "/home/tf_py3/lane_stopline_tensorpack_model/tensorpack-master-lane/tensorpack/train/interface.py", line 91, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/tf_py3/lane_stopline_tensorpack_model/tensorpack-master-lane/tensorpack/train/base.py", line 331, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/tf_py3/lane_stopline_tensorpack_model/tensorpack-master-lane/tensorpack/train/base.py", line 303, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/home/tf_py3/lane_stopline_tensorpack_model/tensorpack-master-lane/tensorpack/utils/argtools.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/home/tf_py3/lane_stopline_tensorpack_model/tensorpack-master-lane/tensorpack/train/base.py", line 268, in main_loop
    self.run_step()  # implemented by subclass
  File "/home/tf_py3/lane_stopline_tensorpack_model/tensorpack-master-lane/tensorpack/train/base.py", line 181, in run_step
    self.hooked_sess.run(self.train_op)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/home/tf_py3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value
PrefetchDataZMQ successfully cleaned-up.
```

Just as i have train Epoch 4 ,and everything goes right, however when training Epoch5 ,  the error happens.I really want to know how this error happen?

**Comment by ppwwyyxx** [comment]
Please post issues following the issue template (new issues -> unexpected problems).
