### ISSUE TITLE
AttributeError: 'ResNetFPNModel' object has no attribute 'input_names'

### ISSUE THREAD

**Issue by liningxiao** [tensorpack/tensorpack#875]
command:  ./train.py --config     MODE_MASK=False MODE_FPN=True     DATA.BASEDIR=/run/media/qdu/qd/lnx/coco2014/     BACKBONE.WEIGHTS=./data/models/COCO-R101FPN-MaskRCNN-Standard.npz BACKBONE.RESNET_NUM_BLOCK=[3,4,23,3]

[0828 19:18:08 @data.py:309] Filtered 1021 images which contain no non-crowd groudtruth boxes. Total #images for training: 117266
[0828 19:18:08 @training.py:51] [DataParallel] Training a model of 2 towers.
[0828 19:18:08 @interface.py:46] Automatically applying StagingInput on the DataFlow.
[0828 19:18:08 @input_source.py:202] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0828 19:18:08 @training.py:111] Building graph for training tower 0 on device /gpu:0 ...
Traceback (most recent call last):
  File "./train.py", line 587, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/train/interface.py", line 85, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/train/tower.py", line 194, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/train/trainers.py", line 172, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 222, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/graph_builder/training.py", line 118, in build_on_towers
    ret.append(func())
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/train/tower.py", line 222, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/tfutils/tower.py", line 255, in __call__
    output = self._tower_fn(*args)
  File "/usr/local/python3/lib/python3.5/site-packages/tensorpack/graph_builder/model_desc.py", line 233, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "./train.py", line 229, in build_graph
    inputs = dict(zip(self.input_names, inputs))
**AttributeError: 'ResNetFPNModel' object has no attribute 'input_names'**

There was no such problem in the previous version.
I did not change the source code. i tried to trace the error but couldn't figure out. Could you please give me some advices? Thanks a lot!

**Comment by ppwwyyxx** [comment]
upgrade tensorpack from github.

**Comment by Myeongjoon** [comment]
I found the same error.
If install tensorpack by `pip install tensorpack` this will return this error.
So to solve this error, must use github code.

**Comment by liningxiao** [comment]
> I found the same error.
> If install tensorpack by `pip install tensorpack` this will return this error.
> So to solve this error, must use github code.

thanks! it works!
