### ISSUE TITLE
Could tensorpack trainer work with slim.prefetch_queue?

### ISSUE THREAD

**Issue by fanq15** [tensorpack/tensorpack#877]
+ Your question is probably answered in [tutorials](http://tensorpack.readthedocs.io/en/latest/tutorial/index.html#user-tutorials). Read it first.

+ We answer "HOW to do X with Tensorpack" for a well-defined X.
  We also answer "HOW/WHY Tensorpack does X" for some X that Tensorpack or its examples are doing.

  We __don't__ answer general machine learning questions, such as "why my training doesn't converge", "what networks to use" or "I don't understand the paper".

You can also use gitter (https://gitter.im/tensorpack/users) for more casual discussions.

**Comment by fanq15** [comment]
What I really want to do is just using the dataflow to handle my data.
The data format is 
`
{'width': <tf.Tensor 'batch:4' shape=(16,) dtype=int64>, 'image': <tf.Tensor 'batch:1' shape=(16, 513, 513, 3) dtype=float32>, 'label': <tf.Tensor 'batch:3' shape=(16, 513, 513, 1) dtype=int32>, 'image_name': <tf.Tensor 'batch:2' shape=(16,) dtype=string>, 'height': <tf.Tensor 'batch:0' shape=(16,) dtype=int64>}
` which is processed by tf.train.batch
or
`
{'width': <tf.Tensor 'Reshape_6:0' shape=() dtype=int64>, 'image': <tf.Tensor 'cond/Merge:0' shape=(513, 513, 3) dtype=float32>, 'label': <tf.Tensor 'cond/Merge_1:0' shape=(513, 513, 1) dtype=int32>, 'image_name': <tf.Tensor 'Reshape_1:0' shape=() dtype=string>, 'height': <tf.Tensor 'Reshape_3:0' shape=() dtype=int64>}
` which is not processed by tf.train.batch

**Comment by ppwwyyxx** [comment]
Can you make sure your dataflow __can actually run__? You can check it by `TestDataSpeed(ds).start()`.
If it does, what does the elements look like? Can you print the first element?
You can print it by:
```python
ds.reset_state()
print(next(ds.get_data()))
```
If you don't know how to write a dataflow, read https://tensorpack.readthedocs.io/tutorial/extend/dataflow.html .
Data does not have to come from files. It can be arbitrary python code.

**Comment by fanq15** [comment]
Thank you for your kind reply!
When run 
``` 
ds.reset_state()
print(next(ds.get_data()))
TestDataSpeed(ds).start()
``
The print is :
```
=================
[<tf.Tensor 'cond/Merge:0' shape=(513, 513, 3) dtype=float32>, <tf.Tensor 'Squeeze_2:0' shape=(513, 513) dtype=int32>]
  0%|                                                                                                                                                                                                                   |0/5000[00:00<?,?it/s]
[0830 01:19:38 @param.py:194] Use train_log/hed/hyper.txt to set hyperparam: 'learning_rate'.
[0830 01:19:42 @training.py:51] [DataParallel] Training a model of 4 towers.
```

My generator is:
```
slim = tf.contrib.slim

dataset_data_provider = slim.dataset_data_provider
def _get_data(data_provider, dataset_split):
  if common.LABELS_CLASS not in data_provider.list_items():
    raise ValueError('Failed to find labels.')

  image, height, width = data_provider.get(
      [common.IMAGE, common.HEIGHT, common.WIDTH])

  # Some datasets do not contain image_name.
  if common.IMAGE_NAME in data_provider.list_items():
    image_name, = data_provider.get([common.IMAGE_NAME])
  else:
    image_name = tf.constant('')

  label = None
  if dataset_split != common.TEST_SET:
    label, = data_provider.get([common.LABELS_CLASS])

  return image, label, image_name, height, width


def get(dataset,
        crop_size,
        batch_size,
        min_resize_value=None,
        max_resize_value=None,
        resize_factor=None,
        min_scale_factor=1.,
        max_scale_factor=1.,
        scale_factor_step_size=0,
        num_readers=1,
        num_threads=1,
        dataset_split=None,
        is_training=True,
        model_variant=None):

  if dataset_split is None:
    raise ValueError('Unknown dataset split.')
  if model_variant is None:
    tf.logging.warning('Please specify a model_variant. See '
                       'feature_extractor.network_map for supported model '
                       'variants.')

  data_provider = dataset_data_provider.DatasetDataProvider(
      dataset,
      num_readers=num_readers,
      num_epochs=None if is_training else 1,
      shuffle=is_training)
  image, label, image_name, height, width = _get_data(data_provider,
                                                      dataset_split)
  if label is not None:
                                                                                                                                                                                                                                if label.shape.ndims == 2:
      label = tf.expand_dims(label, 2)
    elif label.shape.ndims == 3 and label.shape.dims[2] == 1:
      pass
    else:
      raise ValueError('Input label shape must be [height, width], or '
                       '[height, width, 1].')

    label.set_shape([None, None, 1])
  original_image, image, label = input_preprocess.preprocess_image_and_label(
      image,
      label,
      crop_height=crop_size[0],
      crop_width=crop_size[1],
      min_resize_value=min_resize_value,
      max_resize_value=max_resize_value,
      resize_factor=resize_factor,
      min_scale_factor=min_scale_factor,
      max_scale_factor=max_scale_factor,
      scale_factor_step_size=scale_factor_step_size,
      ignore_label=dataset.ignore_label,
      is_training=is_training,
      model_variant=model_variant)
  sample = {
      common.IMAGE: image,
      common.IMAGE_NAME: image_name,
      common.HEIGHT: height,
      common.WIDTH: width
  }
  if label is not None:
    sample[common.LABEL] = tf.squeeze(label, -1)

  if not is_training:
    # Original image is only used during visualization.
    sample[common.ORIGINAL_IMAGE] = original_image,
    num_threads = 1
  yield [sample[common.IMAGE], sample[common.LABEL]]
```
And I generate my dataflow through:
```
def get_data():
    dataset = segmentation_dataset.get_dataset(
      FLAGS.dataset, FLAGS.train_split, dataset_dir=FLAGS.dataset_dir)

    #tf.gfile.MakeDirs(FLAGS.train_logdir)
    #tf.logging.info('Training on %s set', FLAGS.train_split)

    #samples = MyDataFlow(
    samples = input_generator_sync.get(
          dataset,
          FLAGS.train_crop_size,
          FLAGS.train_batch_size,
          min_resize_value=FLAGS.min_resize_value,
          max_resize_value=FLAGS.max_resize_value,
          resize_factor=FLAGS.resize_factor,
          min_scale_factor=FLAGS.min_scale_factor,
          max_scale_factor=FLAGS.max_scale_factor,
          scale_factor_step_size=FLAGS.scale_factor_step_size,
          dataset_split=FLAGS.train_split,
          is_training=True,
          model_variant=FLAGS.model_variant)

    ds = DataFromGenerator(samples)
    #ds = BatchDataByShape(ds, 8, idx=0) # when remove it and the PrefecthDataZMQ, the test works.

    #ds = PrefetchDataZMQ(ds, 1) #
    return ds
```
and 
```
    dataset_train = get_data() #get_data('train')
    #dataset_train = input_generator_sync()
    steps_per_epoch = 100 # dataset_train.size() * 40
    #dataset_val = get_data('val')
    print '================='
    dataset_train.reset_state()
    print(next(dataset_train.get_data()))
    TestDataSpeed(dataset_train).start()
```
And the dataset is generated by:
```
def get_dataset(dataset_name, split_name, dataset_dir):
  """Gets an instance of slim Dataset.

  Args:
    dataset_name: Dataset name.
    split_name: A train/val Split name.
    dataset_dir: The directory of the dataset sources.

  Returns:
    An instance of slim Dataset.

  Raises:
    ValueError: if the dataset_name or split_name is not recognized.
  """
  if dataset_name not in _DATASETS_INFORMATION:
    raise ValueError('The specified dataset is not supported yet.')

  splits_to_sizes = _DATASETS_INFORMATION[dataset_name].splits_to_sizes

  if split_name not in splits_to_sizes:
    raise ValueError('data split name %s not recognized' % split_name)

  # Prepare the variables for different datasets.
  num_classes = _DATASETS_INFORMATION[dataset_name].num_classes
  ignore_label = _DATASETS_INFORMATION[dataset_name].ignore_label

  file_pattern = _FILE_PATTERN
  file_pattern = os.path.join(dataset_dir, file_pattern % split_name)

  # Specify how the TF-Examples are decoded.
  keys_to_features = {
      'image/encoded': tf.FixedLenFeature(
          (), tf.string, default_value=''),
      'image/filename': tf.FixedLenFeature(
          (), tf.string, default_value=''),
      'image/format': tf.FixedLenFeature(
          (), tf.string, default_value='jpeg'),
      'image/height': tf.FixedLenFeature(
          (), tf.int64, default_value=0),
      'image/width': tf.FixedLenFeature(
          (), tf.int64, default_value=0),
      'image/segmentation/class/encoded': tf.FixedLenFeature(
          (), tf.string, default_value=''),
      'image/segmentation/class/format': tf.FixedLenFeature(
          (), tf.string, default_value='png'),
  }
  items_to_handlers = {
      'image': tfexample_decoder.Image(
          image_key='image/encoded',
          format_key='image/format',
          channels=3),
      'image_name': tfexample_decoder.Tensor('image/filename'),
      'height': tfexample_decoder.Tensor('image/height'),
      'width': tfexample_decoder.Tensor('image/width'),
      'labels_class': tfexample_decoder.Image(
          image_key='image/segmentation/class/encoded',
          format_key='image/segmentation/class/format',
          channels=1),
  }

  decoder = tfexample_decoder.TFExampleDecoder(
      keys_to_features, items_to_handlers)

  return dataset.Dataset(
      data_sources=file_pattern,
      reader=tf.TFRecordReader,
      decoder=decoder,
      num_samples=splits_to_sizes[split_name],
      items_to_descriptions=_ITEMS_TO_DESCRIPTIONS,
      ignore_label=ignore_label,
      num_classes=num_classes,
      name=dataset_name,
      multi_label=True)
```

**Comment by ppwwyyxx** [comment]
Dataflow is unrelated to tensorflow, it should produce numpy arrays.

To use tensorflow tensors as inputs, you can check the "input pipeline"
tutorial for options other than dataflow.

**Comment by fanq15** [comment]
You mean that I can use the tensorflow tensors as inputs in the tensorpack trainer?

**Comment by fanq15** [comment]
But it seems that other data formats can't be used in tensorpack trainer:
```
AssertionError: <tensorflow.python.ops.data_flow_ops.FIFOQueue object at 0x7f374c4a1310>
AssertionError: <class 'tensorflow.python.ops.data_flow_ops.FIFOQueue'>
AssertionError: <class 'tensorpack.input_source.input_source.TensorInput'>

```

**Comment by ppwwyyxx** [comment]
Next time please post full error. I do not know how you get those errors but it feels like you did not use the correct API: https://tensorpack.readthedocs.io/modules/train.html#tensorpack.train.TrainConfig

You should use `dataflow=` if using a dataflow, or `data=` if using an InputSource.

**Comment by fanq15** [comment]
Sorry, it is my fault... 
But when I use the `data=inputs_queue`, where the `inputs_queue=prefetch_queue.prefetch_queue(
          samples, capacity=128 * config.num_clones)`
I got the error:
```
Traceback (most recent call last):
  File "deeplab/hed.py", line 495, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/hed.py", line 484, in main
    config = get_config()
  File "deeplab/hed.py", line 440, in get_config
    max_epoch=100,
  File "/usr/local/lib/python2.7/site-packages/tensorpack/train/config.py", line 101, in __init__
    assert_type(data, InputSource)
  File "/usr/local/lib/python2.7/site-packages/tensorpack/train/config.py", line 94, in assert_type
    assert isinstance(v, tp), v.__class__
AssertionError: <class 'tensorflow.python.ops.data_flow_ops.FIFOQueue'>
``` 
Can the `data=` accept the `FIFOQueue` as inputs?

**Comment by ppwwyyxx** [comment]
No. As the [document](https://tensorpack.readthedocs.io/modules/train.html#tensorpack.train.TrainConfig) said, `data=` takes a [InputSource](https://tensorpack.readthedocs.io/modules/input_source.html#tensorpack.input_source.InputSource). FIFOQueue is not an `InputSource`. Please use the functions according to the docs.

If you have created a `tf.data.Dataset`, you can use [TFDatasetInput](https://tensorpack.readthedocs.io/modules/input_source.html#tensorpack.input_source.TFDatasetInput). If you have a function that creates `tf.Tensors` directly, use [TensorInput](https://tensorpack.readthedocs.io/modules/input_source.html#tensorpack.input_source.TensorInput).

**Comment by fanq15** [comment]
Alright, is there any `InputSource` suitable for the `FIFOQueue`?

I want to handle the `smaples` which has the data format: `{'image': <tf.Tensor 'batch:0' shape=(8, 513, 513, 3) dtype=float32>, 'label': <tf.Tensor 'batch:1' shape=(8, 513, 513, 1) dtype=int32>}`. It is a dict, and cannot be processed by the `TensorInput`.

Or I can handle the `dataset_train` which has the data format: `<class 'tensorflow.python.ops.data_flow_ops.FIFOQueue'>`.
It seems that there is not suitable `InputSource` for my data.

**Comment by ppwwyyxx** [comment]
`InputSource` requires a __list__ of tensors as inputs that match the order you declared in your model.
You can make a list from a dict by `[dic['image'], dic['label']]`, assuming that's the order you declared them.

**Comment by fanq15** [comment]
It doesn't work...
I change the samples to `list` with the format:
```
===========samples: [<tf.Tensor 'cond/Merge:0' shape=(513, 513, 3) dtype=float32>, <tf.Tensor 'cond/Merge_1:0' shape=(513, 513, 1) dtype=int32>]
```
But I get the error:
```
Traceback (most recent call last):
  File "deeplab/hed.py", line 495, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "deeplab/hed.py", line 489, in main
    SyncMultiGPUTrainer(max(get_num_gpu(), 1)))
  File "/usr/local/lib/python2.7/site-packages/tensorpack/train/interface.py", line 85, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/usr/local/lib/python2.7/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorpack/train/tower.py", line 194, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/usr/local/lib/python2.7/site-packages/tensorpack/train/trainers.py", line 93, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/usr/local/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 160, in build
    grad_list = DataParallelBuilder.build_on_towers(self.towers, get_grad_fn, devices)
  File "/usr/local/lib/python2.7/site-packages/tensorpack/graph_builder/training.py", line 118, in build_on_towers
    ret.append(func())
  File "/usr/local/lib/python2.7/site-packages/tensorpack/train/tower.py", line 222, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/usr/local/lib/python2.7/site-packages/tensorpack/input_source/input_source_base.py", line 81, in get_input_tensors
    return self._get_input_tensors()
  File "/usr/local/lib/python2.7/site-packages/tensorpack/input_source/input_source.py", line 352, in _get_input_tensors
    ret = self.get_tensor_fn()
TypeError: 'list' object is not callable
```

**Comment by ppwwyyxx** [comment]
As the [document](https://tensorpack.readthedocs.io/modules/input_source.html#tensorpack.input_source.TensorInput) of TensorInput said, it takes __a function which returns a list__, not a list directly.

**Comment by fanq15** [comment]
Alright. I find an example in the PTB training example. I should read the document more carefully. Thank you for your kind help! And I will reply later after I solve it.

**Comment by fanq15** [comment]
It works!
I use the 
```
samples = input_generator.get(
          dataset,
          FLAGS.train_crop_size,
          FLAGS.train_batch_size,
          min_resize_value=FLAGS.min_resize_value,
          max_resize_value=FLAGS.max_resize_value,
          resize_factor=FLAGS.resize_factor,
          min_scale_factor=FLAGS.min_scale_factor,
          max_scale_factor=FLAGS.max_scale_factor,
          scale_factor_step_size=FLAGS.scale_factor_step_size,
          dataset_split=FLAGS.train_split,
          is_training=True,
          model_variant=FLAGS.model_variant)
```
to generate input tensor list.
And it is wrong to just put the `samples` into the `TensorInput`, which is `data=TensorInput(samples)`.
It should be a lambda function to make the function callable:
`data=TensorInput(lambda samples, iter_steps)`
We can see the details in the `tensorpack/examples/PennTreebank`.
BTW, tensorpack is really a powerful tool! Thank you for your contribution! And I think the document about the use of tensorflow tensor input should be easier to access.
