### ISSUE TITLE
Load fp32-pretrained model into fp16-based graph.

### ISSUE THREAD

**Issue by junsukchoe** [tensorpack/tensorpack#895]
Hi,

I have tried to load a pre-trained vgg16 model (from tensorpack model zoo) to fp16-based vgg16 graph. However, it cannot be done because of datatype mismatching.

I use get_model_loader for loading pretrained model. The error message is:

```
[0917 08:50:52 @base.py:198] Initializing the session ...
[0917 08:50:52 @sessinit.py:207] Variables to restore from dict: conv1_1/b:0, conv2_2/b:0, conv4_2/b:0, conv3_2/b:0, conv4_2/W:0, conv5_2/W:0, conv1_2/b:0, conv3_3/W:0, conv5_3/W:0, conv2_2/W:0, conv3_3/b:0, conv2_1/b:0, conv5_3/b:0, conv1_1/W:0, conv3_1/b:0, conv4_1/W:0, conv3_2/W:0, conv5_1/W:0, conv5_1/b:0, conv4_3/W:0, conv4_3/b:0, conv3_1/W:0, conv4_1/b:0, conv2_1/W:0, conv5_2/b:0, conv1_2/W:0
[0917 08:50:52 @sessinit.py:90] WRN The following variables are in the graph, but not found in the dict: global_step:0, learning_rate:0, linear/W:0, linear/b:0, new/W:0, new/b:0
[0917 08:50:52 @sessinit.py:90] WRN The following variables are in the dict, but not found in the graph: fc6/W:0, fc6/b:0, fc7/W:0, fc7/b:0, fc8/W:0, fc8/b:0
[0917 08:50:52 @sessinit.py:220] Restoring from dict ...
Traceback (most recent call last):
  File "codes/CAM-vgg.py", line 118, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_gpu))
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/interface.py", line 93, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 306, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 277, in train
    self.initialize(session_creator, session_init)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 199, in initialize
    session_init._run_init(self.sess)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/sessinit.py", line 221, in _run_init
    upd.update({name: value for name, value in six.iteritems(self._prms) if name in intersect})
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/varmanip.py", line 108, in update
    SessionUpdate.load_value_to_var(v, value)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/tfutils/varmanip.py", line 92, in load_value_to_var
    assert vartype == val.dtype, msg
AssertionError: Variable conv1_1/W has dtype <dtype: 'float16'> but was given a value of dtype float32.

```

How can I load fp32 pretrained model to fp16-based graph? 
Do I have to load the numpy dict in python and then cast to numpy float 16?

Any advice will help a lot.

Thank you.

**Comment by ppwwyyxx** [comment]
If your model is fp16 then you certainly need to load fp16 weights.

> Do I have to load the numpy dict in python and then cast to numpy float 16?

yes.

**Comment by junsukchoe** [comment]
Thank you!
