### ISSUE TITLE
AttributeError: 'TrainLoop' object has no attribute 'starting_epoch'

### ISSUE THREAD

**Issue by thuzhf** [tensorpack/tensorpack#904]
The problem occurred when L318 below is executed if `stats is not None` (e.g. when you restore training from a log dir). The full error message is attached in the end.
https://github.com/tensorpack/tensorpack/blob/36b05bb71a498da3ea430c3a109cf9a9dddecbd8/tensorpack/callbacks/monitor.py#L309-L318

It can be seen `self.starting_epoch` is defined in L48 below.
https://github.com/tensorpack/tensorpack/blob/36b05bb71a498da3ea430c3a109cf9a9dddecbd8/tensorpack/train/base.py#L44-L48

And `config()` is called in L241 below in the `main_loop()` function.
https://github.com/tensorpack/tensorpack/blob/36b05bb71a498da3ea430c3a109cf9a9dddecbd8/tensorpack/train/base.py#L233-L241

And `setup_callbacks()` (L289 below) is executed before `main_loop()` (L291 below).
https://github.com/tensorpack/tensorpack/blob/36b05bb71a498da3ea430c3a109cf9a9dddecbd8/tensorpack/train/base.py#L274-L291

And L318 in the first file (monitor.py) will be finally executed in the calling of `setup_callbacks()` above. Actually you already have `load_existing_epoch_number ` in L298 below.
https://github.com/tensorpack/tensorpack/blob/36b05bb71a498da3ea430c3a109cf9a9dddecbd8/tensorpack/callbacks/monitor.py#L298

And the above function is only called in the following class:
https://github.com/tensorpack/tensorpack/blob/36b05bb71a498da3ea430c3a109cf9a9dddecbd8/tensorpack/train/config.py#L177-L240

Even if I changed `TrainConfig()` to `AutoResumeTrainConfig()`, the same problem still occurred due to the same reason. Although `self.starting_epoch` is also defined below, it is the `config`'s attribute instead of the `train.loop`'s:
https://github.com/tensorpack/tensorpack/blob/7b8728f96b76774a5d345390cfb5607c8935d9e3/tensorpack/train/config.py#L146

 I think some easy workarounds will be: 
* Defining `starting_epoch` earlier as the `train.loop`'s attribute (that way `AutoResumeTrainConfig()` will probably work).
* Changing L318 in the first file (monitor.py) to use function `load_existing_epoch_number()` (that way maybe will make `AutoResumeTrainConfig()` useless, but this is handy because users can always use `TrainConfig()`).

However, to be consistent with the logic of your `Trainer.train()` function (including 3 functions), it seems it needs more consideration on how to fix this.

The following is the full error message:
```
Traceback (most recent call last):
  File "main.py", line 307, in <module>
    main()
  File "main.py", line 303, in main
    launch_train_with_config(config, trainer)
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/train/interface.py", line 95, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 319, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 289, in train
    self.setup_callbacks(callbacks, monitors)
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 189, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 70, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/monitor.py", line 55, in setup_graph
    self._setup_graph()
  File "/data/fangzhang/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/monitor.py", line 318, in _setup_graph
    starting_epoch = self.trainer.loop.starting_epoch
AttributeError: 'TrainLoop' object has no attribute 'starting_epoch'
```

**Comment by ppwwyyxx** [comment]
This is an issue I fixed before but forgot to take a note about it. Unfortunately it was introduced again lately..
I will think about how to properly address this.
