### ISSUE TITLE
ERR [MultiProcessMapDataZMQ] buffer_size cannot be larger than the size of the DataFlow!

### ISSUE THREAD

**Issue by horizonheart** [tensorpack/tensorpack#941]
WRN Install python-prctl so that processes can be cleaned with guarantee.
[1022 13:15:12 @parallel_map.py:53] ERR [MultiProcessMapDataZMQ] buffer_size cannot be larger than the size of the DataFlow!
Traceback (most recent call last):
  File "train.py", line 603, in <module>
    launch_train_with_config(traincfg, trainer)
  File "../../tensorpack/train/interface.py", line 97, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "../../tensorpack/train/base.py", line 341, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "../../tensorpack/train/base.py", line 311, in train
    self.setup_callbacks(callbacks, monitors)
  File "../../tensorpack/utils/argtools.py", line 181, in wrapper
    return func(*args, **kwargs)
  File "../../tensorpack/train/base.py", line 211, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "../../tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "../../tensorpack/callbacks/group.py", line 70, in _setup_graph
    cb.setup_graph(self.trainer)

**Comment by ywpkwon** [comment]
I experienced a similar issue. I guess https://github.com/tensorpack/tensorpack/issues/945 might be related..?

**Comment by yuyijie1995** [comment]
Did you solve this error ? @ywpkwon @horizonheart
