### ISSUE TITLE
Multiple-Input Batched Data

### ISSUE THREAD

**Issue by brunoalano** [tensorpack/tensorpack#947]
I'm trying to feed a RNN+LSTM Network using the `KerasModel` layer, and in my case, I need to use 2 inputs, and get a `Dense(1)` output.

```python
train, test, val = dataset.get('train'), dataset.get('test'), dataset.get('val')
train_ds = BatchData(train, batch_size, use_list=True)
test_ds = BatchData(test, batch_size, use_list=True)

M = KerasModel(create_model,
               inputs_desc=[
                    InputDesc(tf.float32, [
                        None, timesteps_val, len(features_per_timestep)], 'input_a'),
                    InputDesc(tf.float32, [
                        None, timesteps_val, 96, 96, 1], 'input_b'),
               ],
               targets_desc=[InputDesc(tf.float32, [None, 1], 'labels')],
               input=QueueInput(train_ds))
```

If I remove the `use_list=True`, I got an error saying that batched data only works in Numpy Arrays. If I remove batching, or keep the way that its above, I got:

```
[1024 15:03:14 @input_source.py:168] ERR Exception in EnqueueThread QueueInput/input_queue:
Traceback (most recent call last):
  File "/Users/brunoalano/.local/share/virtualenvs/research-laYaeRqi/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 159, in run
    feed = _make_feeds(self.placehdrs, dp)
  File "/Users/brunoalano/.local/share/virtualenvs/research-laYaeRqi/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 41, in _make_feeds
    len(datapoint), len(placeholders))
AssertionError: Size of datapoint and placeholders are different: 2 != 3
```

Details:

- Python Version: Python 3.6.5
- TF Version: v1.11.0-rc2-4-gc19e29306c 1.11.0
- Tensorpack Version (from git): 0.8.9

**Comment by brunoalano** [comment]
If I remove the `None` from the `input_a` input, it passes, but then I got an issue from my model, because it was expecting `ndim=3` and received `ndim=2`.

```
ValueError: Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=2
```

**Comment by brunoalano** [comment]
My mistake: On my `DataFlow`, I was generating data as `[[input_a, input_b], y]`, but changing that to `[input_a, input_b, y]` solved the case.
