### ISSUE TITLE
a model's input is another model's output

### ISSUE THREAD

**Issue by stoensin** [tensorpack/tensorpack#982]
#### hi! I am working on a task that uses the Faster R-CNN to implement an Image Caption network. As i use the Faster R-CNN example to start my work，then i build a  model to get the output of Node: 'faster r-cnn/outpt'  as inputs, the architecture like this:
```
class DetectionModel(ModelDesc):
     ...

class ResNetFPNModel(DetectionModel):
     ...
     final_cost = Dense2pModel().create_architecture( head_feature)
     return final_cost

class Dense2pModel(ModelDesc):
    def __init__(self):
           ...
    def create_architecture(self, inputs):
        ...
```

##### The above code is now case a problem  when i training my network ,the error is:

```
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    main()
  File "train.py", line 39, in main
    Dense2pModel.train_net(args=args)
  File "/content/dense2p/dense2p.py", line 687, in train_net
    launch_train_with_config(traincfg, trainer)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/interface.py", line 87, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 204, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/trainers.py", line 186, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 223, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 119, in build_on_towers
    ret.append(func())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 242, in get_grad_fn
    opt = get_opt_fn()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/model_desc.py", line 230, in get_optimizer
    return self.optimizer()
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/scope_utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/content/dense2p/dense2p.py", line 66, in optimizer
    lr = tf.get_variable('learning_rate', initializer=0.003, trainable=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 879, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable learning_rate does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?
```
### In order to resolve this error, I made sure that the variables in my code use the tensorpack rules，but the error still happen ,Please point out where my mistake is.

**Comment by ppwwyyxx** [comment]
Do not use `reuse_variables()` in the root scope. It affects all other code. This sounds like the issue you're having.

**Comment by ppwwyyxx** [comment]
Added it as another rule at https://tensorpack.readthedocs.io/tutorial/trainer.html#rules-of-tower-function

> Do not modify the reuse option (e.g., by `scope.reuse_variables()`) of a variable
     scope that is not created by you. This affects other's code.

**Comment by stoensin** [comment]
#### yeah, i removed some 'reuse_variables' in my model, it's working, thanks a lot.
