### ISSUE TITLE
an error of Faster R-CNN group normalization

### ISSUE THREAD

**Issue by stoensin** [tensorpack/tensorpack#985]
### 1. What you did:

(1) As i use the faster r-cnn example to build a image caption network, i get the region features [here](https://github.com/stoensin/IC/blob/755fb3e8b2bb8698ad76e93c17bd5c6a6be20559/dense2p/dense2p.py#L277) to my rnn-model [here](https://github.com/stoensin/IC/blob/755fb3e8b2bb8698ad76e93c17bd5c6a6be20559/dense2p/dense2p.py#L319) 

(2) **If you're using examples, have you made any changes to the examples? Paste them here:**
#### 2、  i changed the faster r-cnn default config file about :
```
**_C.TRAIN.STEPS_PER_EPOCH = 50**
**_C.FRCNN.BATCH_PER_IM = 32** 
```
 i used the mod is 
`MODE_FPN=True MODE_MASK = False
FPN.NORM=GN BACKBONE.NORM=GN
FPN.FRCNN_HEAD_FUNC=fastrcnn_4conv1fc_gn_head
FPN.MRCNN_HEAD_FUNC=maskrcnn_up4conv_gn_head`

#### the pretrained model i used is: http://models.tensorpack.com/FasterRCNN/COCO-R50FPN-MaskRCNN-StandardGN.npz

(3) **If not using examples, tell us what you did here:**

### 2. What you observed:
as when run the train steps , it was interrupted since the following lines：
```
[1118 12:29:24 @base.py:240] Graph Finalized.
[1118 12:29:25 @concurrency.py:37] Starting EnqueueThread QueueInput/input_queue ...
[1118 12:29:25 @graph.py:73] Running Op sync_variables/sync_variables_from_main_tower ...
[1118 12:29:42 @param.py:158] [HyperParamSetter] At global_step=0, learning_rate is set to 0.003300
[1118 12:29:43 @base.py:272] Start Epoch 1 ...
  0% 0/20 [00:00<?, ?it/s]
2018-11-18 12:30:43.984557: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 401408 values, but the requested shape has 627200
	 [[{{node tower0/fastrcnn/gn0/output_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _class=["loc:@tower0/gradients/tower0/fastrcnn/gn0/output_1_grad/Reshape"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower0/fastrcnn/gn0/output/add_1, tower0/fastrcnn/gn0/Shape)]]
	 [[{{node tower0/gradients/tower0/fastrcnn/conv0/Conv2D_grad/Conv2DBackpropInput/_3311}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_76151...kpropInput", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 401408 values, but the requested shape has 627200
	 [[node tower0/fastrcnn/gn0/output_1 (defined at /content/dense2p/region_detector/basemodel.py:44)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _class=["loc:@tower0/gradients/tower0/fastrcnn/gn0/output_1_grad/Reshape"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower0/fastrcnn/gn0/output/add_1, tower0/fastrcnn/gn0/Shape)]]
	 [[{{node tower0/gradients/tower0/fastrcnn/conv0/Conv2D_grad/Conv2DBackpropInput/_3311}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_76151...kpropInput", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```
### 3. What you expected, if not obvious.
`My goal for the example modification is that he can generate a 4096-dimension output about RIOS, that the RNN model will receive it.`

### 4. Your environment:
  + Python 3 
  + TF version: v1.12.0-0-ga6d8ffae09 1.12.0
  + Tensorpack version: 0.9.0.1
  + Hardware information  1GPU Tesla K80

### the whole error msg is here:
```
[1118 03:56:28 @param.py:158] [HyperParamSetter] At global_step=0, learning_rate is set to 0.003300
[1118 03:56:29 @base.py:272] Start Epoch 1 ...
  0% 0/20 [00:00<?, ?it/s]
2018-11-18 03:57:27.528065: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 401408 values, but the requested shape has 627200
	 [[{{node tower0/fastrcnn/gn0/output_1}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _class=["loc:@tower0/gradients/tower0/fastrcnn/gn0/output_1_grad/Reshape"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower0/fastrcnn/gn0/output/add_1, tower0/fastrcnn/gn0/Shape)]]
	 [[{{node tower0/gradients/tower0/fastrcnn/conv0/Conv2D_grad/Conv2DBackpropInput/_3311}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_74285...kpropInput", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:
.....

Caused by op 'tower0/fastrcnn/gn0/output_1', defined at:
  File "train.py", line 43, in <module>
    main()
  File "train.py", line 39, in main
    Dense2pModel.train_net(args=args)
  File "/content/dense2p/dense2p.py", line 659, in train_net
    launch_train_with_config(traincfg, trainer)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/interface.py", line 87, in launch_train_with_config
    model._build_graph_get_cost, model.get_optimizer)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 204, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/trainers.py", line 186, in _setup_graph
    self._make_get_grad_fn(input, get_cost_fn, get_opt_fn), get_opt_fn)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 223, in build
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/training.py", line 119, in build_on_towers
    ret.append(func())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/tower.py", line 232, in get_grad_fn
    cost = get_cost_fn(*input.get_input_tensors())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/tower.py", line 284, in __call__
    output = self._tower_fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/graph_builder/model_desc.py", line 246, in _build_graph_get_cost
    ret = self.build_graph(*inputs)
  File "/content/dense2p/dense2p.py", line 276, in build_graph
    head_feature = fastrcnn_head_func('fastrcnn', roi_feature_fastrcnn)
  File "/content/dense2p/region_detector/model_frcnn.py", line 298, in fastrcnn_4conv1fc_gn_head
    return fastrcnn_conv1fc_head(*args, num_convs=4, norm='GN', **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/content/dense2p/region_detector/model_frcnn.py", line 287, in fastrcnnconv1fc_head
    l = GroupNorm('gn{}'.format(k), l)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/content/dense2p/region_detector/basemodel.py", line 44, in GroupNorm
    return tf.reshape(out, orig_shape, name='output')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 6482, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 401408 values, but the requested shape has 627200
	 [[node tower0/fastrcnn/gn0/output_1 (defined at /content/dense2p/region_detector/basemodel.py:44)  = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _class=["loc:@tower0/gradients/tower0/fastrcnn/gn0/output_1_grad/Reshape"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower0/fastrcnn/gn0/output/add_1, tower0/fastrcnn/gn0/Shape)]]
	 [[{{node tower0/gradients/tower0/fastrcnn/conv0/Conv2D_grad/Conv2DBackpropInput/_3311}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_74285...kpropInput", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

MultiProcessMapDataZMQ successfully cleaned-up.
```
##### the training logs is [here](https://github.com/stoensin/IC/blob/f821b8e6cf0e00781e4ed20b8c43a72c0b126ade/dense2p/logs/log.log#L1)

**Comment by ppwwyyxx** [comment]
For anyone to be able to understand your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs").

**Comment by ppwwyyxx** [comment]
Running the FasterRCNN example with the configuration you provided does not produce any errors in my test.

Since you're making nontrivial modifications to the code. If your modifications to the code causes errors, it's likely not a tensorpack issue and not what we'll help with.

**Comment by stoensin** [comment]
Thank you for your patience, I have rewritten the format of the issue.
The model I am working on now refactors the model I implemented with tensorflow. The original model is already working properly. For the part of image feature extraction, I will now use the faster r-cnn example, the other part from the original Some models are migrated;
The error that now appears looks like a dimension mismatch in GroupNorm, but the only part of the network that uses GroupNorm is the code for faster r-cnn, but I have not made any changes to it.

**Comment by ppwwyyxx** [comment]
> but the only part of the network that uses GroupNorm is the code for faster r-cnn, but I have not made any changes to it

The error does come from faster r-cnn. However this does not imply that it is due to a problem of faster r-cnn.
As you can probably verify yourself (and you'd better do so in case this is a bug of tensorflow), that things will work if you train faster r-cnn with the above configurations.

Another option that may help is that perhaps you can distill a [MCVE](https://stackoverflow.com/help/mcve) that anyone can easily run and see the errors. It's almost impossible to debug something that may not be a tensorpack issue at all, just from the logs.

**Comment by ppwwyyxx** [comment]
Your code here https://github.com/stoensin/IC/blob/755fb3e8b2bb8698ad76e93c17bd5c6a6be20559/dense2p/dense2p.py#L421-L427 looks very wrong and please double check their shapes and dimensions.
