### ISSUE TITLE
Train Faster-rcnn error by using one GTX1080Ti.

### ISSUE THREAD

**Issue by xtanitfy** [tensorpack/tensorpack#986]
(1) $cd examples/FasterRCNN and run follow:
          ./train.py --config \
        MODE_MASK=False MODE_FPN=True \
       DATA.BASEDIR=/disk1/DataSet/COCO \
        BACKBONE.WEIGHTS=pretrain_model/ImageNet-R50-AlignPadding.npz
(2) error log as follow:
     2018-11-22 11:23:07.634189: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
    self._extend_graph()
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: PeakMemoryTracker/MaxBytesInUse = MaxBytesInUse[_device="/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 618, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/interface.py", line 97, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 341, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 312, in train
    self.initialize(session_creator, session_init)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/tower.py", line 144, in initialize
    super(TowerTrainer, self).initialize(session_creator, session_init)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 229, in initialize
    self.sess = session_creator.create_session()
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/tfutils/sesscreate.py", line 43, in create_session
    sess.run(tf.global_variables_initializer())
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: PeakMemoryTracker/MaxBytesInUse = MaxBytesInUse[_device="/device:GPU:0"]()]]

Caused by op 'PeakMemoryTracker/MaxBytesInUse', defined at:
  File "./train.py", line 618, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/interface.py", line 97, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 341, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 311, in train
    self.setup_callbacks(callbacks, monitors)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 211, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 70, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/prof.py", line 211, in _setup_graph
    ops.append(MaxBytesInUse())
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/memory_stats/python/ops/memory_stats_ops.py", line 41, in MaxBytesInUse
    return gen_memory_stats_ops.max_bytes_in_use()
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/memory_stats/ops/gen_memory_stats_ops.py", line 152, in max_bytes_in_use
    "MaxBytesInUse", name=name)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/disk3/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'MaxBytesInUse' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'

	 [[Node: PeakMemoryTracker/MaxBytesInUse = MaxBytesInUse[_device="/device:GPU:0"]()]]

MultiProcessMapDataZMQ successfully cleaned-up.

 (4) tensorflow-gpu == 1.8.0,cuda=9.0 cudnn=7.0.5,gpu-hardware is one GTX1080TI.,cpu-memory is 8G

**Comment by ppwwyyxx** [comment]
Please always include entire logs.

It looks like it's an environment issue of your environment and your tensorflow cannot use your GPUs. You can debug by, e.g. runing the mnist examples and see if the GPU is used.

**Comment by csuquan** [comment]
@xtanitfy 
I face the same error ,could you tell me how to solve it??thanks!

**Comment by csuquan** [comment]
@xtanitfy 
您可以把联系方式给我一下吗~谢谢

**Comment by ppwwyyxx** [comment]
Tensorflow cannot access your GPU. That is your own environment problem and others' solution is unlikely to be helpful you.

**Comment by itmessager** [comment]
> It can run now.Thank you very much!

I face the same error ,could you tell me how to solve it?

**Comment by 13266828291** [comment]
I reinstall the environment by  using conda. 
pip install tensorflow-gpu==1.9.0

**Comment by xtanitfy** [comment]
I reinstall the environment by using conda.
pip install tensorflow-gpu==1.9.0

**Comment by ppwwyyxx** [comment]
To future readers again: this is an environment problem, and other people's solution is unlikely to solve your problem. Please do not just blindly follow how others solve the issue without knowing the cause of the issue.
