### ISSUE TITLE
Train faster rcnn 

### ISSUE THREAD

**Issue by CYang0515** [tensorpack/tensorpack#991]
If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

I run faster rcnn example with replicated mode. But there is an unexpected problem.

Traceback (most recent call last):
  File "train.py", line 694, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/train/interface.py", line 97, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 341, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 311, in train
    self.setup_callbacks(callbacks, monitors)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/train/base.py", line 211, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 70, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 52, in setup_graph
    self._setup_graph()
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 308, in _setup_graph
    self._cb_setup_graph(self)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 35, in <lambda>
    return CallbackFactory(setup_graph=lambda _: df.reset_state())
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/base.py", line 172, in reset_state
    self.ds.reset_state()
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/base.py", line 172, in reset_state
    self.ds.reset_state()
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 276, in reset_state
    _MultiProcessZMQDataFlow.reset_state(self)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 107, in reset_state
    self._reset_once()  # build processes
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 273, in _reset_once
    self._fill_buffer()     # pre-fill the bufer
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 50, in _fill_buffer
    self._send(dp)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 279, in _send
    msg = [b"", dumps(dp)]
  File "/home/amax/anaconda3/lib/python3.6/site-packages/tensorpack/utils/serialize.py", line 19, in dumps_msgpack
    return msgpack.dumps(obj, use_bin_type=True)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/msgpack_numpy.py", line 196, in packb
    return Packer(**kwargs).pack(o)
  File "/home/amax/anaconda3/lib/python3.6/site-packages/msgpack_numpy.py", line 162, in __init__
    strict_types=strict_types)
  File "msgpack/_packer.pyx", line 84, in msgpack._packer.Packer.__init__ (msgpack/_packer.cpp:1242)
TypeError: __init__() got an unexpected keyword argument 'strict_types'
MultiProcessMapDataZMQ successfully cleaned-up.

**Comment by ppwwyyxx** [comment]
For anyone to better understand and diagnose your issue, please post relevant details following the issue template. See the first line of your issue.

Tensorpack requires:
https://github.com/tensorpack/tensorpack/blob/c4a68c6c5b4e6c7dc7b73014870edeee6e1cfe76/setup.py#L31
but you do not have it.

**Comment by CYang0515** [comment]
I'm sorry, Next time I will pay attention.
I use pip to install tensorpack, pip list includes msgpack (0.5.6) moudle.

**Comment by CYang0515** [comment]
so，please, how can I solve it?




    
    
        
            
                
                    
                        
                    
                    
                        
                            454232091
                            
                            
                                
                                    邮箱：454232091@qq.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


On 11/28/2018 01:28, Yuxin Wu wrote: msgpack 0.5.6 has the strict_types option: https://github.com/msgpack/msgpack-python/blob/0.5.6/msgpack/_packer.pyx#L117-L119
Therefore you're not using msgpack 0.5.6. You may have different versions installed at different places.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tensorpack/tensorpack","title":"tensorpack/tensorpack","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/tensorpack/tensorpack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ppwwyyxx in #991: msgpack 0.5.6 has the `strict_types` option: https://github.com/msgpack/msgpack-python/blob/0.5.6/msgpack/_packer.pyx#L117-L119\r\n\r\nTherefore you're not using msgpack 0.5.6. You may have different versions installed at different places."}],"action":{"name":"View Issue","url":"https://github.com/tensorpack/tensorpack/issues/991#issuecomment-442146143"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tensorpack/tensorpack/issues/991#issuecomment-442146143",
"url": "https://github.com/tensorpack/tensorpack/issues/991#issuecomment-442146143",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [tensorpack/tensorpack] Train faster rcnn  (#991)",
"sections": [
{
"text": "",
"activityTitle": "**Yuxin Wu**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ppwwyyxx",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"tensorpack/tensorpack\",\n\"issueId\": 991,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"tensorpack/tensorpack\",\n\"issueId\": 991\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/tensorpack/tensorpack/issues/991#issuecomment-442146143"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 416716672\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by ppwwyyxx** [comment]
I would recommend you to uninstall all msgpack related packages in your system and reinstall it.
How to install msgpack is unrelated to tensorpack so I'm closing this issue.
